name: parlai-hydra
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.13.1
  - cudatoolkit=10.0.130
  - cudnn=7.6.0
  - intel-openmp=2019.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libstdcxx-ng=9.1.0
  - mkl=2019.4
  - nccl=1.3.5
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.17.2
  - openssl=1.1.1c
  - pip=19.3.1
  - pycparser=2.19
  - python=3.6.7
  - pytorch=1.3.0
  - readline=8.0
  - setuptools=41.4.0
  - sqlite=3.30.1
  - tk=8.6.9
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - apex==0.1
    - aspy-yaml==1.3.0
    - attrs==19.3.0
    - babel==2.7.0
    - boto3==1.9.246
    - botocore==1.12.246
    - cfgv==2.0.1
    - chardet==3.0.4
    - docutils==0.14
    - entrypoints==0.3
    - flake8==3.7.8
    - flake8-bugbear==19.8.0
    - flake8-docstrings==1.5.0
    - gitdb2==2.0.6
    - gitpython==3.0.3
    - h5py==2.10.0
    - hydra-core==0.10.0
    - identify==1.4.7
    - idna==2.8
    - imagesize==1.1.0
    - importlib-metadata==0.23
    - importlib-resources==1.0.2
    - jinja2==2.10.3
    - jmespath==0.9.4
    - joblib==0.14.0
    - markdown==2.6.11
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - more-itertools==7.2.0
    - nltk==3.4.5
    - nodeenv==1.3.3
    - omegaconf==1.3.0
    - packaging==19.2
    - pexpect==4.7.0
    - pillow==6.2.0
    - pre-commit==1.18.3
    - ptyprocess==0.6.0
    - py-gfm==0.1.4
    - py-rouge==1.1
    - pycodestyle==2.5.0
    - pydocstyle==4.0.1
    - pyflakes==2.1.1
    - pygments==2.4.2
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - pytz==2019.3
    - pyyaml==5.1.2
    - pyzmq==18.1.0
    - regex==2019.8.19
    - requests==2.22.0
    - requests-mock==1.7.0
    - restructuredtext-lint==1.3.0
    - s3transfer==0.2.1
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - sh==1.12.14
    - six==1.12.0
    - smmap2==2.0.5
    - snowballstemmer==2.0.0
    - sphinx==2.2.0
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - toml==0.10.0
    - tqdm==4.36.1
    - unidecode==1.1.1
    - urllib3==1.25.6
    - virtualenv==16.7.7
    - websocket-client==0.56.0
    - zipp==0.6.0
