var searchData=
[
  ['tfidf_20retriever',['TFIDF Retriever',['../md_parlai_agents_tfidf_retriever_README.html',1,'']]],
  ['task_3a_20aqua',['Task: AQuA',['../md_parlai_tasks_aqua_README.html',1,'']]],
  ['task_3a_20babi_201k',['Task: bAbI 1k',['../md_parlai_tasks_babi_README.html',1,'']]],
  ['task_3a_20booktest',['Task: BookTest',['../md_parlai_tasks_booktest_README.html',1,'']]],
  ['task_3a_20children_27s_20book_20test_20_28cbt_29',['Task: Children&apos;s Book Test (CBT)',['../md_parlai_tasks_cbt_README.html',1,'']]],
  ['task_3a_20clevr',['Task: CLEVR',['../md_parlai_tasks_clevr_README.html',1,'']]],
  ['task_3a_20cnn_2fdm_20summarisation',['Task: CNN/DM Summarisation',['../md_parlai_tasks_cnn_dm_README.html',1,'']]],
  ['task_3a_20coco_5fcaptions',['Task: COCO_Captions',['../md_parlai_tasks_coco_caption_README.html',1,'']]],
  ['task_3a_20convai2',['Task: ConvAI2',['../md_parlai_tasks_convai2_README.html',1,'']]],
  ['task_3a_20convai2_5fwild_5fevaluation',['Task: ConvAI2_wild_evaluation',['../md_parlai_tasks_convai2_wild_evaluation_README.html',1,'']]],
  ['task_3a_20convai_5fchitchat',['Task: ConvAI_ChitChat',['../md_parlai_tasks_convai_chitchat_README.html',1,'']]],
  ['task_3a_20choice_20of_20plausible_20alternatives',['Task: Choice of Plausible Alternatives',['../md_parlai_tasks_copa_README.html',1,'']]],
  ['task_3a_20conversational_20question_20answering_20challenge',['Task: Conversational Question Answering Challenge',['../md_parlai_tasks_coqa_README.html',1,'']]],
  ['task_3a_20cornell_20movie',['Task: Cornell Movie',['../md_parlai_tasks_cornell_movie_README.html',1,'']]],
  ['task_3a_20daily_20dialog',['Task: Daily Dialog',['../md_parlai_tasks_dailydialog_README.html',1,'']]],
  ['task_3a_20dialog_20based_20language_20learning_3a_20babi_20task',['Task: Dialog Based Language Learning: bAbI Task',['../md_parlai_tasks_dbll_babi_README.html',1,'']]],
  ['task_3a_20dialog_20based_20language_20learning_3a_20wikimovies_20task',['Task: Dialog Based Language Learning: WikiMovies Task',['../md_parlai_tasks_dbll_movie_README.html',1,'']]],
  ['task_3a_20deal_20or_20no_20deal',['Task: Deal or No Deal',['../md_parlai_tasks_dealnodeal_README.html',1,'']]],
  ['task_3a_20decanlp_3a_20the_20natural_20language_20decathlon',['Task: DecaNLP: The Natural Language Decathlon',['../md_parlai_tasks_decanlp_README.html',1,'']]],
  ['task_3a_20dialog_20babi_2b',['Task: Dialog bAbI+',['../md_parlai_tasks_dialog_babi_plus_README.html',1,'']]],
  ['task_3a_20dialog_20babi',['Task: Dialog bAbI',['../md_parlai_tasks_dialog_babi_README.html',1,'']]],
  ['task_3a_20dialogue_5fqe',['Task: Dialogue_QE',['../md_parlai_tasks_dialogue_qe_README.html',1,'']]],
  ['task_3a_20empathetic_20dialogues',['Task: Empathetic Dialogues',['../md_parlai_tasks_empathetic_dialogues_README.html',1,'']]],
  ['task_3a_20flickr30k',['Task: Flickr30k',['../md_parlai_tasks_flickr30k_README.html',1,'']]],
  ['task_3a_20fvqa',['Task: FVQA',['../md_parlai_tasks_fvqa_README.html',1,'']]],
  ['task_3a_20hotpotqa',['Task: HotpotQA',['../md_parlai_tasks_hotpotqa_README.html',1,'']]],
  ['task_3a_20image_5fchat',['Task: Image_Chat',['../md_parlai_tasks_image_chat_README.html',1,'']]],
  ['task_3a_20insuranceqa',['Task: InsuranceQA',['../md_parlai_tasks_insuranceqa_README.html',1,'']]],
  ['task_3a_20integration_20tests',['Task: Integration Tests',['../md_parlai_tasks_integration_tests_README.html',1,'']]],
  ['task_3a_20interactive',['Task: Interactive',['../md_parlai_tasks_interactive_README.html',1,'']]],
  ['task_3a_20iwslt14',['Task: IWSLT14',['../md_parlai_tasks_iwslt14_README.html',1,'']]],
  ['task_3a_20light_2ddialogue',['Task: LIGHT-Dialogue',['../md_parlai_tasks_light_dialog_README.html',1,'']]],
  ['task_3a_20mctest',['Task: MCTest',['../md_parlai_tasks_mctest_README.html',1,'']]],
  ['task_3a_20mnist_5fqa',['Task: MNIST_QA',['../md_parlai_tasks_mnist_qa_README.html',1,'']]],
  ['task_3a_20movie_20dialog_20qa',['Task: Movie Dialog QA',['../md_parlai_tasks_moviedialog_README.html',1,'']]],
  ['task_3a_20ms_5fmarco',['Task: MS_MARCO',['../md_parlai_tasks_ms_marco_README.html',1,'']]],
  ['task_3a_20mturk_20wikimovies',['Task: MTurk WikiMovies',['../md_parlai_tasks_mturkwikimovies_README.html',1,'']]],
  ['task_3a_20multinli',['Task: MultiNLI',['../md_parlai_tasks_multinli_README.html',1,'']]],
  ['task_3a_20mutualfriends',['Task: MutualFriends',['../md_parlai_tasks_mutualfriends_README.html',1,'']]],
  ['task_3a_20mwsc_20pronoun_20resolution',['Task: MWSC pronoun resolution',['../md_parlai_tasks_mwsc_README.html',1,'']]],
  ['task_3a_20narrativeqa',['Task: NarrativeQA',['../md_parlai_tasks_narrative_qa_README.html',1,'']]],
  ['task_3a_20nlvr',['Task: nlvr',['../md_parlai_tasks_nlvr_README.html',1,'']]],
  ['task_3a_20open_20subtitles',['Task: Open Subtitles',['../md_parlai_tasks_opensubtitles_README.html',1,'']]],
  ['task_3a_20persona_2dchat',['Task: Persona-Chat',['../md_parlai_tasks_personachat_README.html',1,'']]],
  ['task_3a_20personality_5fcaptions',['Task: Personality_Captions',['../md_parlai_tasks_personality_captions_README.html',1,'']]],
  ['task_3a_20personalized_20dialog_20full_20set',['Task: Personalized Dialog Full Set',['../md_parlai_tasks_personalized_dialog_README.html',1,'']]],
  ['task_3a_20qa_20cnn',['Task: QA CNN',['../md_parlai_tasks_qacnn_README.html',1,'']]],
  ['task_3a_20qa_20daily_20mail',['Task: QA Daily Mail',['../md_parlai_tasks_qadailymail_README.html',1,'']]],
  ['task_3a_20qangaroo',['Task: QAngaroo',['../md_parlai_tasks_qangaroo_README.html',1,'']]],
  ['task_3a_20qa_2dsrl_20semantic_20role_20labeling',['Task: QA-SRL Semantic Role Labeling',['../md_parlai_tasks_qasrl_README.html',1,'']]],
  ['task_3a_20qa_2dzre_20relation_20extraction',['Task: QA-ZRE Relation Extraction',['../md_parlai_tasks_qazre_README.html',1,'']]],
  ['task_3a_20question_20answering_20in_20context',['Task: Question Answering in Context',['../md_parlai_tasks_quac_README.html',1,'']]],
  ['task_3a_20scan',['Task: SCAN',['../md_parlai_tasks_scan_README.html',1,'']]],
  ['task_3a_20self_2dfeeding_20chatbot',['Task: Self-Feeding Chatbot',['../md_parlai_tasks_self_feeding_README.html',1,'']]],
  ['task_3a_20simple_20questions',['Task: Simple Questions',['../md_parlai_tasks_simplequestions_README.html',1,'']]],
  ['task_3a_20the_20stanford_20natural_20language_20inference_20_28snli_29_20corpus',['Task: The Stanford Natural Language Inference (SNLI) Corpus',['../md_parlai_tasks_snli_README.html',1,'']]],
  ['task_3a_20squad2',['Task: SQuAD2',['../md_parlai_tasks_squad2_README.html',1,'']]],
  ['task_3a_20squad',['Task: SQuAD',['../md_parlai_tasks_squad_README.html',1,'']]],
  ['task_3a_20sst_20sentiment_20analysis',['Task: SST Sentiment Analysis',['../md_parlai_tasks_sst_README.html',1,'']]],
  ['task_3a_20talk_20the_20walk',['Task: Talk the Walk',['../md_parlai_tasks_talkthewalk_README.html',1,'']]],
  ['task_3a_20task_20n_27_20talk',['Task: Task N&apos; Talk',['../md_parlai_tasks_taskntalk_README.html',1,'']]],
  ['task_3a_20triviaqa',['Task: TriviaQA',['../md_parlai_tasks_triviaqa_README.html',1,'']]],
  ['task_3a_20twitter',['Task: Twitter',['../md_parlai_tasks_twitter_README.html',1,'']]],
  ['task_3a_20ubuntu',['Task: Ubuntu',['../md_parlai_tasks_ubuntu_README.html',1,'']]],
  ['task_3a_20visdial',['Task: VisDial',['../md_parlai_tasks_visdial_README.html',1,'']]],
  ['task_3a_20vqav1',['Task: VQAv1',['../md_parlai_tasks_vqa_v1_README.html',1,'']]],
  ['task_3a_20vqav2',['Task: VQAv2',['../md_parlai_tasks_vqa_v2_README.html',1,'']]],
  ['task_3a_20web_20questions',['Task: Web Questions',['../md_parlai_tasks_webquestions_README.html',1,'']]],
  ['task_3a_20wikimovies',['Task: WikiMovies',['../md_parlai_tasks_wikimovies_README.html',1,'']]],
  ['task_3a_20wikipedia',['Task: Wikipedia',['../md_parlai_tasks_wikipedia_README.html',1,'']]],
  ['task_3a_20wikiqa',['Task: WikiQA',['../md_parlai_tasks_wikiqa_README.html',1,'']]],
  ['task_3a_20wikisql_20semantic_20parsing_20task',['Task: WikiSQL semantic parsing task',['../md_parlai_tasks_wikisql_README.html',1,'']]],
  ['task_3a_20wizard_5fof_5fwikipedia',['Task: Wizard_of_Wikipedia',['../md_parlai_tasks_wizard_of_wikipedia_README.html',1,'']]],
  ['task_3a_20wmt',['Task: WMT',['../md_parlai_tasks_wmt_README.html',1,'']]],
  ['task_3a_20woz_20restuarant_20reservation_20_28goal_2doriented_20dialogue_29',['Task: WOZ restuarant reservation (Goal-Oriented Dialogue)',['../md_parlai_tasks_woz_README.html',1,'']]]
];
