#@package _global_
mephisto:
  blueprint:
    onboarding_qualification: test-parlai-qa-qualification
  task:
    task_name: parlai-qa-example
    task_title: "Test ParlAI QA Data Collection Task"
    task_description: >
      This is a ParlAI data collection task.
    task_reward: 0.3
    task_tags: "dynamic,question answering,testing"
