#@package _global_
monitoring_log_rate: 300
defaults:
  - /mephisto/blueprint: model_chat_blueprint
  - /mephisto/architect: local
  - /mephisto/provider: mock
mephisto:
  blueprint:
    task_description_file: ${task_dir}/task_config/task_description.html
    onboard_task_data_path: ${task_dir}/task_config/onboard_task_data.json
    world_file: ${task_dir}/multiparty_worlds.py
    annotations_config_path: ${task_dir}/task_config/annotations_config.json
    onboarding_qualification: model_chat_onboarding
    block_qualification: model_chat_block
    allowed_worker_qualification: multiparty-modelchat-allow
    chat_data_folder: ${task_dir}/model_chat/
    model_opt_path: ${task_dir}/task_config/model_opts.yaml
    custom_source_dir: ${task_dir}/frontend/
    num_conversations: 2
    num_turns: 2
    task_model_parallel: true
    check_acceptability: false
    include_persona: true
    conversation_start_mode: parlai.crowdsourcing.tasks.multi_model_chat.multiparty_worlds
    annotation_question: Does this comment from your partner have any of the following attributes? (Check all that apply)
    conversations_needed_string: "random_light_prod:2"
    override_opt:
      context_generator: parlai.crowdsourcing.tasks.multi_model_chat.multiparty_worlds
  task:
    allowed_concurrent: 2
    assignment_duration_in_seconds: 600
    max_num_concurrent_units: 0  # 0 means infinite; set this to a positive integer to limit concurrent HITs and prevent crashes
    maximum_units_per_worker: 3
    task_name: model_chat
    task_reward: 3
    task_tags: "chat,conversation,dialog,partner"
    task_title: "Chat with a fellow conversationalist!"
mturk:
  worker_blocklist_paths: null
