#@package _global_
defaults:
  - /mephisto/blueprint: turn_annotations_static_blueprint
  - /mephisto/architect: local
  - /mephisto/provider: mock
mephisto:
  blueprint:
    subtasks_per_unit: 6
    task_source: ${task_dir}/webapp/build/bundle.js
    data_jsonl: FIXME_TASK_DATA_PATH
    extra_source_dir: ${task_dir}/webapp/src/static
    units_per_assignment: 5
    onboarding_qualification: turn_annotations_static
    annotations_config_path: ${task_dir}/task_config/annotations_config.json
    response_field: False
    task_description_file: ${task_dir}/task_config/task_description.html
  task:
    allowed_concurrent: 1
    assignment_duration_in_seconds: 600
    max_num_concurrent_units: 0  # 0 means infinite; set this to a positive integer to limit concurrent HITs and prevent crashes
    maximum_units_per_worker: 5
    task_name: turn_annotations_static
    task_reward: 0.3
    task_tags: "chat,conversation,dialog,partner"
    task_title: "Chat with a fellow conversationalist"
mturk:
  worker_blocklist_paths: null
