bAbI 1k
^^^^^^^

**Tag**: ``#bAbI-1k``

**Full Path**: ``babi:All1k``

**Group Tags**: ``#all``, ``#QA``

**Description**: 20 synthetic tasks that each test a unique aspect of text and reasoning, and hence test different capabilities of learning models. From Weston et al. '16. Link: http://arxiv.org/abs/1502.05698

**Notes**: You can access just one of the bAbI tasks with e.g. 'babi:Task1k:3' for task 3.


bAbI 10k
^^^^^^^^

**Tag**: ``#bAbI-10k``

**Full Path**: ``babi:All10k``

**Group Tags**: ``#all``, ``#QA``

**Description**: 20 synthetic tasks that each test a unique aspect of text and reasoning, and hence test different capabilities of learning models. From Weston et al. '16. Link: http://arxiv.org/abs/1502.05698

**Notes**: You can access just one of the bAbI tasks with e.g. 'babi:Task10k:3' for task 3.


BookTest
^^^^^^^^

**Tag**: ``#BookTest``

**Full Path**: ``booktest``

**Group Tags**: ``#all``, ``#Cloze``

**Description**: Sentence completion given a few sentences as context from a book. A larger version of CBT. From Bajgar et al., 16. Link: https://arxiv.org/abs/1610.00956



Children's Book Test (CBT)
^^^^^^^^^^^^^^^^^^^^^^^^^^

**Tag**: ``#CBT``

**Full Path**: ``cbt``

**Group Tags**: ``#all``, ``#Cloze``

**Description**: Sentence completion given a few sentences as context from a children's book. From Hill et al., '16. Link: https://arxiv.org/abs/1511.02301



Cornell Movie
^^^^^^^^^^^^^

**Tag**: ``#CornellMovie``

**Full Path**: ``cornell_movie``

**Group Tags**: ``#all``, ``#ChitChat``

**Description**: Fictional conversations extracted from raw movie scripts. Link: https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html



Dialog Based Language Learning: bAbI Task
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Tag**: ``#DBLL-bAbI``

**Full Path**: ``dbll_babi``

**Group Tags**: ``#all``, ``#Goal``

**Description**: Short dialogs based on the bAbI tasks, but in the form of a question from a teacher, the answer from the student, and finally a comment on the answer from the teacher. The aim is to find learning models that use the comments to improve. From Weston '16. Link: https://arxiv.org/abs/1604.06045



Dialog Based Language Learning: WikiMovies Task
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Tag**: ``#DBLL-Movie``

**Full Path**: ``dbll_movie``

**Group Tags**: ``#all``, ``#Goal``

**Description**: Short dialogs based on WikiMovies, but in the form of a question from a teacher, the answer from the student, and finally a comment on the answer from the teacher. The aim is to find learning models that use the comments to improve. From Weston '16. Link: https://arxiv.org/abs/1604.06045



Dialog bAbI
^^^^^^^^^^^

**Tag**: ``#dialog-bAbI``

**Full Path**: ``dialog_babi``

**Group Tags**: ``#all``, ``#Goal``

**Description**: Simulated dialogs of restaurant booking, from Bordes et al. '16. Link: https://arxiv.org/abs/1605.07683



MCTest
^^^^^^

**Tag**: ``#MCTest``

**Full Path**: ``mctest``

**Group Tags**: ``#all``, ``#QA``

**Description**: Questions about short children's stories, from Richardson et al. '13. Link: https://www.microsoft.com/en-us/research/publication/mctest-challenge-dataset-open-domain-machine-comprehension-text/



Movie Dialog QA
^^^^^^^^^^^^^^^

**Tag**: ``#MovieDD-QA``

**Full Path**: ``moviedialog:Task:1``

**Group Tags**: ``#all``, ``#QA``, ``#MovieDD``

**Description**: Closed-domain QA dataset asking templated questions about movies, answerable from Wikipedia, similar to WikiMovies. From Dodge et al. '15. Link: https://arxiv.org/abs/1511.06931



Movie Dialog QA Recommendations
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Tag**: ``#MovieDD-QARecs``

**Full Path**: ``moviedialog:Task:3``

**Group Tags**: ``#all``, ``#Goal``, ``#MovieDD``

**Description**: Dialogs discussing questions about movies as well as recommendations. From Dodge et al. '15. Link: https://arxiv.org/abs/1511.06931



Movie Dialog Recommendations
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Tag**: ``#MovieDD-Recs``

**Full Path**: ``moviedialog:Task:2``

**Group Tags**: ``#all``, ``#QA``, ``#MovieDD``

**Description**: Questions asking for movie recommendations. From Dodge et al. '15. Link: https://arxiv.org/abs/1511.06931



Movie Dialog Reddit
^^^^^^^^^^^^^^^^^^^

**Tag**: ``#MovieDD-Reddit``

**Full Path**: ``moviedialog:Task:4``

**Group Tags**: ``#all``, ``#ChitChat``, ``#MovieDD``

**Description**: Dialogs discussing Movies from Reddit (the Movies SubReddit). From Dodge et al. '15. Link: https://arxiv.org/abs/1511.06931



MTurk WikiMovies
^^^^^^^^^^^^^^^^

**Tag**: ``#MTurkWikiMovies``

**Full Path**: ``mturkwikimovies``

**Group Tags**: ``#all``, ``#QA``

**Description**: Closed-domain QA dataset asking MTurk-derived questions about movies, answerable from Wikipedia. From Li et al. '16. Link: https://arxiv.org/abs/1611.09823



Open Subtitles
^^^^^^^^^^^^^^

**Tag**: ``#OpenSubtitles``

**Full Path**: ``opensubtitles``

**Group Tags**: ``#all``, ``#ChitChat``

**Description**: Dataset of dialogs from movie scripts: http://opus.lingfil.uu.se/OpenSubtitles.php. A variant of the dataset used in Vinyals & Le '15, https://arxiv.org/abs/1506.05869.



QA CNN
^^^^^^

**Tag**: ``#QACNN``

**Full Path**: ``qacnn``

**Group Tags**: ``#all``, ``#Cloze``

**Description**: Cloze dataset based on a missing (anonymized) entity phrase from a CNN article, Hermann et al. '15. Link: https://arxiv.org/abs/1506.03340



QA Daily Mail
^^^^^^^^^^^^^

**Tag**: ``#QADailyMail``

**Full Path**: ``qadailymail``

**Group Tags**: ``#all``, ``#Cloze``

**Description**: Cloze dataset based on a missing (anonymized) entity phrase from a Daily Mail article, Hermann et al. '15. Link: https://arxiv.org/abs/1506.03340



Simple Questions
^^^^^^^^^^^^^^^^

**Tag**: ``#SimpleQuestions``

**Full Path**: ``simplequestions``

**Group Tags**: ``#all``, ``#QA``

**Description**: Open-domain QA dataset based on Freebase triples from Bordes et al. '15. Link: https://arxiv.org/abs/1506.02075



SQuAD
^^^^^

**Tag**: ``#SQuAD``

**Full Path**: ``squad``

**Group Tags**: ``#all``, ``#QA``

**Description**: Open-domain QA dataset answerable from a given paragraph from Wikipedia, from Rajpurkar et al. '16. Link: https://arxiv.org/abs/1606.05250



Ubuntu
^^^^^^

**Tag**: ``#Ubuntu``

**Full Path**: ``ubuntu``

**Group Tags**: ``#all``, ``#ChitChat``

**Description**: Dialogs between an Ubunt user and an expert trying to fix issue, from Lowe et al. '15. Link: https://arxiv.org/abs/1506.08909



Web Questions
^^^^^^^^^^^^^

**Tag**: ``#WebQuestions``

**Full Path**: ``webquestions``

**Group Tags**: ``#all``, ``#QA``

**Description**: Open-domain QA dataset from Web queries from Berant et al. '13. Link: http://www.aclweb.org/anthology/D13-1160



WikiMovies
^^^^^^^^^^

**Tag**: ``#WikiMovies``

**Full Path**: ``wikimovies``

**Group Tags**: ``#all``, ``#QA``

**Description**: Closed-domain QA dataset asking templated questions about movies, answerable from Wikipedia. From Miller et al. '16. Link: https://arxiv.org/abs/1606.03126



WikiQA
^^^^^^

**Tag**: ``#WikiQA``

**Full Path**: ``wikiqa``

**Group Tags**: ``#all``, ``#QA``

**Description**: Open domain QA from Wikipedia dataset from Yang, et al. '15. Link: https://www.microsoft.com/en-us/research/publication/wikiqa-a-challenge-dataset-for-open-domain-question-answering/



