#@package _global_
mephisto:
  task:
    allowed_concurrent: 1
    assignment_duration_in_seconds: 600
    maximum_units_per_worker: 1
    task_description: "Evaluate quality of conversations through comparison."
    task_name: acute_eval_${current_time}
    task_reward: 0.5
    task_tags: "chat,evaluation,comparison,conversation"
    task_title: "Which Conversational Partner is Better?"
