#@package _global_
mephisto:
  blueprint:
    acute_eval_type: engaging
    config_path: ${fast_acute_task_dir}/task_config/model_config_no_self_chat.json
    models: model1,model2
    num_self_chats: 5
    root_dir: ${fast_acute_task_dir}/task_config
