ParlAI: tests.test_zootasks.TestZooAndTasks Class Reference
tests.test_zootasks.TestZooAndTasks Class Reference
Public Member Functions
def test_zoolist_fields (self)
def test_zoolist_types (self)
def test_tasklist_types (self)
def test_tasklist (self)
def test_zoolist (self)
Private Member Functions
def _assertZooString (self, member, container, animal_name=None)
def _check_directory (self, listname, thing_list, thing_dir, thing_key, ignore=None)
def _check_types (self, thing_list, listname)
Detailed Description
Make sure the package is alive.
Definition at line 22 of file test_zootasks.py.
Member Function Documentation
test_tasklist()
def tests.test_zootasks.TestZooAndTasks.test_tasklist (self)
Check the task list for issues.
Definition at line 60 of file test_zootasks.py.
References tests.test_zootasks.TestZooAndTasks._check_directory().
test_tasklist_types()
def tests.test_zootasks.TestZooAndTasks.test_tasklist_types (self)
Ensure no type errors in the task list.
Definition at line 56 of file test_zootasks.py.
References tests.test_zootasks.TestZooAndTasks._check_types().
test_zoolist()
def tests.test_zootasks.TestZooAndTasks.test_zoolist (self)
Check the zoo list for issues.
Definition at line 70 of file test_zootasks.py.
References tests.test_zootasks.TestZooAndTasks._check_directory().
test_zoolist_fields()
def tests.test_zootasks.TestZooAndTasks.test_zoolist_fields (self)
Ensure zoo entries conform to style standards.
Definition at line 32 of file test_zootasks.py.
References tests.test_zootasks.TestZooAndTasks._assertZooString().
test_zoolist_types()
def tests.test_zootasks.TestZooAndTasks.test_zoolist_types (self)
Ensure no type errors in the model zoo.
Definition at line 52 of file test_zootasks.py.
References tests.test_zootasks.TestZooAndTasks._check_types().
The documentation for this class was generated from the following file:
ParlAI/tests/test_zootasks.py