ParlAI: light_chats.graph.MoveAgentFunction Class Reference
light_chats.graph.MoveAgentFunction Class Reference
Public Member Functions
def __init__ (self)
def follow_agent (self, graph, args, followed)
def func (self, graph, args)
def parse_text_to_args (self, graph, actor_id, text)
def get_find_fail_text (self, arg_idx)
def get_action_observation_format (self, action, descs)
def parse_descs_to_args (self, graph, args)
Public Member Functions inherited from light_chats.graph.GraphFunction
def __init__ (self, function_name, possible_arg_nums, arg_split_words, arg_find_type, arg_constraints, func_constraints, callback_triggers)
def valid_args (self, graph, args)
def handle (self, graph, args)
def get_failure_action (self, graph, args, spec_fail='failed')
def get_improper_args_text (self, num_args)
def evaluate_constraint_set (self, graph, args, constraints)
def check_possibilites_vs_constraints (self, graph, output_args, arg_idx, possible_ids)
def try_callback_override_args (self, graph, args)
def parse_descs_to_args_helper (self, graph, args, output_args, arg_find_idx=None)
def get_name (self)
def get_canonical_form (self, graph, args)
def get_reverse (self, graph, args)
Public Attributes
formats
Public Attributes inherited from light_chats.graph.GraphFunction
name
possible_arg_nums
arg_split_words
arg_find_type
arg_constraints
func_constraints
callback_triggers
formats
Static Public Attributes
dictionary REPLACEMENTS
Static Public Attributes inherited from light_chats.graph.GraphFunction
format_observation = format_observation
Detailed Description
[actor, destination room or path name from actor's room]
Definition at line 711 of file graph.py.
Member Function Documentation
follow_agent()
def light_chats.graph.MoveAgentFunction.follow_agent (self, graph, args, followed)
handler for all following actions
Definition at line 745 of file graph.py.
References light_chats.graph.MoveAgentFunction.follow_agent(), and light_chats.graph.GraphFunction.get_name().
Referenced by light_chats.graph.MoveAgentFunction.follow_agent(), and light_chats.graph.MoveAgentFunction.func().
func()
def light_chats.graph.MoveAgentFunction.func (self, graph, args)
<Actor> moves to <location>
Reimplemented from light_chats.graph.GraphFunction.
Definition at line 822 of file graph.py.
References light_chats.graph.MoveAgentFunction.follow_agent(), and light_chats.graph.GraphFunction.get_name().
get_action_observation_format()
def light_chats.graph.MoveAgentFunction.get_action_observation_format (self, action, descs)
Given the action, return text to be filled by the parsed args
Allowed to alter the descriptions if necessary
Allowed to use the descriptions to determine the correct format as well
Reimplemented from light_chats.graph.GraphFunction.
Definition at line 916 of file graph.py.
get_find_fail_text()
def light_chats.graph.MoveAgentFunction.get_find_fail_text (self, arg_idx)
Text displayed when an arg find during parse_text_to_args call
fails to find valid targets for the function.
Can be overridden to provide different messages for different failed
arguments.
Reimplemented from light_chats.graph.GraphFunction.
Definition at line 913 of file graph.py.
parse_descs_to_args()
def light_chats.graph.MoveAgentFunction.parse_descs_to_args (self, graph, args)
iterates through the args and the constraints, solving dependency
order on the fly.
Reimplemented from light_chats.graph.GraphFunction.
Definition at line 931 of file graph.py.
References light_chats.graph.MoveAgentFunction.REPLACEMENTS.
parse_text_to_args()
def light_chats.graph.MoveAgentFunction.parse_text_to_args (self, graph, actor_id, text)
Wraps the super parse_text_to_args to be able to handle the special
case of "go back"
Reimplemented from light_chats.graph.GraphFunction.
Definition at line 898 of file graph.py.
Member Data Documentation
REPLACEMENTS
dictionary light_chats.graph.MoveAgentFunction.REPLACEMENTS static
Initial value:
=  {
        'e': 'east',
        'w': 'west',
        'n': 'north',
        's': 'south',
        'u': 'up',
        'd': 'down',
    }
Definition at line 922 of file graph.py.
Referenced by light_chats.graph.MoveAgentFunction.parse_descs_to_args().
The documentation for this class was generated from the following file:
ParlAI/parlai/mturk/tasks/light/light_chats/graph.py