ParlAI: parlai.tasks.insuranceqa.build.ParseInsuranceQAV1 Class Reference
parlai.tasks.insuranceqa.build.ParseInsuranceQAV1 Class Reference
Public Member Functions
def write_data_files (cls, dpext, out_path, d_vocab, d_label_answer)
def create_fb_format (cls, out_path, dtype, inpath, d_vocab, d_label_answer)
Public Member Functions inherited from parlai.tasks.insuranceqa.build.ParseInsuranceQA
def read_gz (cls, filename)
def readlines (cls, path)
def wids2sent (cls, wids, d_vocab)
def read_vocab (cls, vocab_path)
def read_label2answer (cls, label2answer_path_gz, d_vocab)
def create_fb_format (cls, out_path, dtype, inpath, d_vocab, d_label_answer)
def write_data_files (cls, dpext, out_path, d_vocab, d_label_answer)
def build (cls, dpath)
Static Public Attributes
string version = "V1"
string label2answer_fname = "answers.label.token_idx"
Static Public Attributes inherited from parlai.tasks.insuranceqa.build.ParseInsuranceQA
version = None
label2answer_fname = None
Detailed Description
Definition at line 100 of file build.py.
Member Function Documentation
create_fb_format()
def parlai.tasks.insuranceqa.build.ParseInsuranceQAV1.create_fb_format (cls, out_path, dtype, inpath, d_vocab, d_label_answer)
Definition at line 117 of file build.py.
References parlai.tasks.insuranceqa.build.ParseInsuranceQA.readlines(), and parlai.tasks.insuranceqa.build.ParseInsuranceQA.wids2sent().
write_data_files()
def parlai.tasks.insuranceqa.build.ParseInsuranceQAV1.write_data_files (cls, dpext, out_path, d_vocab, d_label_answer)
Definition at line 105 of file build.py.
References parlai.tasks.insuranceqa.build.ParseInsuranceQA.create_fb_format().
Member Data Documentation
label2answer_fname
string parlai.tasks.insuranceqa.build.ParseInsuranceQAV1.label2answer_fname = "answers.label.token_idx" static
Definition at line 102 of file build.py.
version
string parlai.tasks.insuranceqa.build.ParseInsuranceQAV1.version = "V1" static
Definition at line 101 of file build.py.
The documentation for this class was generated from the following file:
parlai/tasks/insuranceqa/build.py