ParlAI: tests.test_utils.TestUtils Class Reference
tests.test_utils.TestUtils Class Reference
Public Member Functions
def test_round_sigfigs (self)
def test_timer (self)
def test_setnamedtupledefaults (self)
def test_padded_tensor (self)
def test_argsort (self)
def test_opt (self)
Detailed Description
Definition at line 22 of file test_utils.py.
Member Function Documentation
test_argsort()
def tests.test_utils.TestUtils.test_argsort (self)
Definition at line 114 of file test_utils.py.
References parlai.agents.legacy_agents.seq2seq.utils_v1.argsort().
test_opt()
def tests.test_utils.TestUtils.test_opt (self)
Definition at line 127 of file test_utils.py.
test_padded_tensor()
def tests.test_utils.TestUtils.test_padded_tensor (self)
Definition at line 103 of file test_utils.py.
References parlai.agents.legacy_agents.seq2seq.utils_v1.padded_tensor().
test_round_sigfigs()
def tests.test_utils.TestUtils.test_round_sigfigs (self)
Definition at line 23 of file test_utils.py.
References parlai.agents.legacy_agents.seq2seq.utils_v0.round_sigfigs().
test_setnamedtupledefaults()
def tests.test_utils.TestUtils.test_setnamedtupledefaults (self)
Definition at line 77 of file test_utils.py.
References parlai.agents.legacy_agents.seq2seq.utils_v1.set_namedtuple_defaults().
test_timer()
def tests.test_utils.TestUtils.test_timer (self)
Definition at line 56 of file test_utils.py.
The documentation for this class was generated from the following file:
tests/test_utils.py