ParlAI: parlai.agents.bert_ranker.bert_dictionary.BertDictionaryAgent Class Reference
parlai.agents.bert_ranker.bert_dictionary.BertDictionaryAgent Class Reference
Public Member Functions
def __init__ (self, opt)
def txt2vec (self, text, vec_type=list)
def vec2txt (self, vec)
def act (self)
Public Member Functions inherited from parlai.core.dict.DictionaryAgent
def __init__ (self, opt, shared=None)
def add_token (self, word)
def __contains__ (self, key)
def __getitem__ (self, key)
def __len__ (self)
def __setitem__ (self, key, value)
def keys (self)
def copy_dict (self, dictionary)
def max_freq (self)
def freqs (self)
def spacy_tokenize (self, text, **kwargs)
def spacy_span_tokenize (self, text)
def nltk_tokenize (self, text, building=False)
def gpt2_tokenize (self, text)
def span_tokenize (self, text)
def tokenize (self, text, building=False)
def bpe_tokenize (self, text)
def add_to_dict (self, tokens)
def remove_tail (self, min_freq)
def resize_to_max (self, maxtokens)
def load (self, filename)
def save (self, filename=None, append=False, sort=True)
def sort (self, trim=True)
def parse (self, txt_or_vec, vec_type=list)
def vec2txt (self, vector, delimiter=' ')
def share (self)
def shutdown (self)
def __str__ (self)
Public Member Functions inherited from parlai.core.agents.Agent
def observe (self, observation)
def getID (self)
def epoch_done (self)
def reset (self)
def reset_metrics (self)
def save (self, path=None)
def upgrade_opt (cls, opt_from_disk)
Public Attributes
tokenizer
start_token
end_token
null_token
start_idx
end_idx
pad_idx
Public Attributes inherited from parlai.core.dict.DictionaryAgent
opt
minfreq
null_token
end_token
unk_token
start_token
max_ngram_size
tokenizer
lower
maxtokens
textfields
tokenizer_fun
freq
tok2ind
ind2tok
sent_tok
word_tok
NLP
bpehelper
gpt2_bpe
save_path
built
Public Attributes inherited from parlai.core.agents.Agent
id
opt
observation
Additional Inherited Members
Static Public Member Functions inherited from parlai.core.dict.DictionaryAgent
def add_cmdline_args (argparser)
def re_tokenize (text)
def split_tokenize (text)
def space_tokenize (text)
Static Public Attributes inherited from parlai.core.dict.DictionaryAgent
string default_lang = 'english'
int default_maxngram = -1
int default_minfreq = 0
int default_maxtokens = -1
string default_null = '__null__'
string default_start = '__start__'
string default_end = '__end__'
string default_unk = '__unk__'
string default_tok = 're'
bool default_lower = False
string default_textfields = 'text,labels'
Detailed Description
Allow to use the Torch Agent with the wordpiece dictionary of Hugging Face.
Definition at line 22 of file bert_dictionary.py.
Member Function Documentation
act()
def parlai.agents.bert_ranker.bert_dictionary.BertDictionaryAgent.act (self)
Add words in the last observation to the dictionary.
This checks any fields in the message present in the --dict-textfields
argument (e.g. "text,labels").
Reimplemented from parlai.core.dict.DictionaryAgent.
Definition at line 66 of file bert_dictionary.py.
Referenced by parlai.messenger.core.agents.MessengerAgent.act_blocking().
txt2vec()
def parlai.agents.bert_ranker.bert_dictionary.BertDictionaryAgent.txt2vec (self, text, vec_type = list)
Convert a string to a vector (list of ints).
First runs a sentence tokenizer, then a word tokenizer.
:param type vec_type:
    The type of the returned vector if the input is a string. Suggested
    ``list``, ``tuple``, ``set``, or ``np.ndarray``.
Reimplemented from parlai.core.dict.DictionaryAgent.
Definition at line 52 of file bert_dictionary.py.
References parlai.core.dict.DictionaryAgent.tokenize(), and parlai.agents.bert_ranker.bert_dictionary.BertDictionaryAgent.tokenizer.
Referenced by parlai.agents.legacy_agents.seq2seq.dict_v0.DictionaryAgent.parse(), parlai.agents.legacy_agents.seq2seq.dict_v1.DictionaryAgent.parse(), and parlai.core.dict.DictionaryAgent.parse().
The documentation for this class was generated from the following file:
ParlAI/parlai/agents/bert_ranker/bert_dictionary.py