ParlAI: parlai.agents.transformer.biencoder.BiencoderAgent Class Reference
parlai.agents.transformer.biencoder.BiencoderAgent Class Reference
Public Member Functions
def vectorize (self, *args, **kwargs)
Public Member Functions inherited from parlai.agents.transformer.transformer.TransformerRankerAgent
def add_cmdline_args (cls, argparser)
def __init__ (self, opt, shared=None)
def build_model (self, states=None)
def build_criterion (self)
def batchify (self, obs_batch, sort=False)
def encode_candidates (self, padded_cands)
def score_candidates (self, batch, cand_vecs, cand_encs=None)
Public Member Functions inherited from parlai.core.torch_ranker_agent.TorchRankerAgent
def set_interactive_mode (self, mode, shared=False)
def get_task_candidates_path (self)
def is_valid (self, obs)
def train_step (self, batch)
def eval_step (self, batch)
def block_repeats (self, cand_preds)
def share (self)
def reset_metrics (self)
def report (self)
def set_vocab_candidates (self, shared)
def set_fixed_candidates (self, shared)
def load_candidates (self, path, cand_type='vectors')
def vectorize_fixed_candidates (self, cands_batch, add_start=False, add_end=False)
Public Member Functions inherited from parlai.core.torch_agent.TorchAgent
def optim_opts (self)
def history_class (cls)
def build_history (self)
def build_dictionary (self)
def build_model (self)
def init_optim (self, params, optim_states=None, saved_optim_type=None)
def build_lr_scheduler (self, states=None, hard_reset=False)
def receive_metrics (self, metrics_dict)
def vectorize (self, obs, history, add_start=True, add_end=True, text_truncate=None, label_truncate=None)
def match_batch (self, batch_reply, valid_inds, output=None)
def last_reply (self, use_reply='label')
def observe (self, observation)
def state_dict (self)
def save (self, path=None)
def load_state_dict (self, state_dict)
def load (self, path)
def reset (self)
def act (self)
def batch_act (self, observations)
def backward (self, loss)
def update_params (self)
def zero_grad (self)
Public Member Functions inherited from parlai.core.agents.Agent
def getID (self)
def epoch_done (self)
def shutdown (self)
def upgrade_opt (cls, opt_from_disk)
Private Member Functions
def _vectorize_text (self, *args, **kwargs)
def _set_text_vec (self, *args, **kwargs)
Additional Inherited Members
Static Public Member Functions inherited from parlai.core.torch_agent.TorchAgent
def dictionary_class ()
Public Attributes inherited from parlai.agents.transformer.transformer.TransformerRankerAgent
data_parallel
model
Public Attributes inherited from parlai.core.torch_ranker_agent.TorchRankerAgent
criterion
model
rank_top_k
optimizer
candidates
encode_candidate_vecs
eval_candidates
ignore_bad_candidates
fixed_candidates_path
vocab_candidates
vocab_candidate_vecs
vocab_candidate_encs
fixed_candidates
fixed_candidate_vecs
fixed_candidate_encs
Public Attributes inherited from parlai.core.torch_agent.TorchAgent
use_cuda
fp16
replies
dict
metrics
opt
model
criterion
id
EMPTY
NULL_IDX
START_IDX
END_IDX
random
batch_idx
histsz
truncate
text_truncate
label_truncate
history
is_training
rank_candidates
add_person_tokens
optimizer
warmup_scheduler
scheduler
proj_rp
observation
Public Attributes inherited from parlai.core.agents.Agent
id
opt
observation
Static Public Attributes inherited from parlai.core.torch_agent.TorchAgent
string P1_TOKEN = '__p1__'
string P2_TOKEN = '__p2__'
Detailed Description
Bi-encoder Transformer Agent.
Equivalent of bert_ranker/biencoder but does not rely on an external
library (hugging face).
Definition at line 11 of file biencoder.py.
Member Function Documentation
_set_text_vec()
def parlai.agents.transformer.biencoder.BiencoderAgent._set_text_vec (self, * args, ** kwargs) private
Add the start and end token to the text.
Definition at line 32 of file biencoder.py.
References parlai.core.torch_agent.TorchAgent._add_start_end_tokens().
Referenced by parlai.core.torch_agent.TorchAgent.vectorize().
_vectorize_text()
def parlai.agents.transformer.biencoder.BiencoderAgent._vectorize_text (self, * args, ** kwargs) private
Override to add start end tokens. necessary for fixed cands.
Definition at line 25 of file biencoder.py.
Referenced by parlai.core.torch_agent.TorchAgent._set_label_cands_vec(), parlai.core.torch_agent.TorchAgent._set_label_vec(), wizard_transformer_ranker.wizard_transformer_ranker.WizardTransformerRankerAgent._vectorize_memories(), parlai.agents.bert_ranker.bi_encoder_ranker.BiEncoderRankerAgent.set_vocab_candidates(), parlai.agents.bert_ranker.bi_encoder_ranker.BiEncoderRankerAgent.vectorize_fixed_candidates(), and parlai.core.torch_ranker_agent.TorchRankerAgent.vectorize_fixed_candidates().
vectorize()
def parlai.agents.transformer.biencoder.BiencoderAgent.vectorize (self, * args, ** kwargs)
Add the start and end token to the text.
Reimplemented from parlai.agents.transformer.transformer.TransformerRankerAgent.
Definition at line 18 of file biencoder.py.
Referenced by self_feeding.self_feeding_agent.SelfFeedingAgent.observe(), and parlai.core.torch_agent.TorchAgent.observe().
The documentation for this class was generated from the following file:
ParlAI/parlai/agents/transformer/biencoder.py