ParlAI: tests.test_eval_model.TestEvalModel Class Reference
tests.test_eval_model.TestEvalModel Class Reference
Public Member Functions
def test_output (self)
def test_metrics_all (self)
def test_metrics_select (self)
def test_multitasking_metrics (self)
Detailed Description
Basic tests on the eval_model.py example.
Definition at line 13 of file test_eval_model.py.
Member Function Documentation
test_metrics_all()
def tests.test_eval_model.TestEvalModel.test_metrics_all (self)
Test output of running eval_model
Definition at line 47 of file test_eval_model.py.
References parlai.messenger.core.run.setup_args().
test_metrics_select()
def tests.test_eval_model.TestEvalModel.test_metrics_select (self)
Test output of running eval_model
Definition at line 78 of file test_eval_model.py.
References parlai.messenger.core.run.setup_args().
test_multitasking_metrics()
def tests.test_eval_model.TestEvalModel.test_multitasking_metrics (self)
Definition at line 113 of file test_eval_model.py.
test_output()
def tests.test_eval_model.TestEvalModel.test_output (self)
Test output of running eval_model
Definition at line 16 of file test_eval_model.py.
References parlai.messenger.core.run.setup_args().
The documentation for this class was generated from the following file:
tests/test_eval_model.py