ParlAI: parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper Class Reference
parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper Class Reference
Public Member Functions
def __init__ (self, codecs_filename)
def tokenize (self, text)
def finalize (self, frequencies, num_symbols=30000, minfreq=2)
Public Attributes
splitter
codecs
bpe
Detailed Description
Helper class for performing BPE subword tokenization.
For technical details, please refer to https://arxiv.org/abs/1508.07909.
This class just wraps around the official subword-nmt repository.
This API expects the user to call tokenize() onto the training data,
then call finalize() to learn the encodings, and then iterate over the data
in a second pass, calling tokenize() again to get processed output.
Definition at line 659 of file dict_v0.py.
Constructor & Destructor Documentation
__init__()
def parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.__init__ (self, codecs_filename)
Initialize the BPE module.
If `codecs_filename` already exists, loads the pretrained codecs.
If it does not, codecs will be saved there after a call to `finalize()`.
:param codecs_filename: place to save/load codecs.
Definition at line 670 of file dict_v0.py.
Member Function Documentation
finalize()
def parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.finalize (self, frequencies, num_symbols = 30000, minfreq = 2)
Build the codecs.
:param: dictionary of (token: frequency) pairs
:param num_symbols: Number of BPE symbols. Recommend 30000-40000.
    If <= 0, default 30000 will be used.
:param minfreq: Minimum frequency of a token before forced BPE
    decomposition. If <= 0 will use subword-nmt default of 2.
Definition at line 710 of file dict_v0.py.
References parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper._load_from_codecs(), parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.codecs, and parlai.messenger.core.shared_utils.format.
tokenize()
def parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.tokenize (self, text)
Tokenize the text with bpe if codecs are already finalized.
Otherwise, returns the regularly split tokens that will train the bpe.
:param text: str. Raw text to tokenize.
:return: a list of tokens. Will use BPE once finalized.
Definition at line 694 of file dict_v0.py.
References parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.bpe, and parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.splitter.
Referenced by parlai.agents.legacy_agents.seq2seq.dict_v1.DictionaryAgent.act(), parlai.core.dict.DictionaryAgent.act(), parlai.agents.legacy_agents.seq2seq.dict_v1.DictionaryAgent.span_tokenize(), parlai.core.dict.DictionaryAgent.span_tokenize(), parlai.agents.legacy_agents.seq2seq.dict_v1.DictionaryAgent.txt2vec(), and parlai.core.dict.DictionaryAgent.txt2vec().
Member Data Documentation
bpe
parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.bpe
Definition at line 692 of file dict_v0.py.
Referenced by parlai.core.gpt2_helper.Gpt2BpeHelper.encode(), parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.tokenize(), parlai.agents.legacy_agents.seq2seq.dict_v1._BPEHelper.tokenize(), and parlai.core.dict._BPEHelper.tokenize().
codecs
parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.codecs
Definition at line 686 of file dict_v0.py.
Referenced by parlai.core.dict._BPEHelper.copy_codecs_file(), parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.finalize(), parlai.agents.legacy_agents.seq2seq.dict_v1._BPEHelper.finalize(), and parlai.core.dict._BPEHelper.finalize().
splitter
parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.splitter
Definition at line 684 of file dict_v0.py.
Referenced by parlai.agents.legacy_agents.seq2seq.dict_v0._BPEHelper.tokenize(), parlai.agents.legacy_agents.seq2seq.dict_v1._BPEHelper.tokenize(), and parlai.core.dict._BPEHelper.tokenize().
The documentation for this class was generated from the following file:
parlai/agents/legacy_agents/seq2seq/dict_v0.py