ParlAI: parrot.ParrotAgent Class Reference
parrot.ParrotAgent Class Reference
Public Member Functions
def train_step (self, batch)
def eval_step (self, batch)
Public Member Functions inherited from parlai.core.torch_agent.TorchAgent
def optim_opts (self)
def history_class (cls)
def add_cmdline_args (cls, argparser)
def __init__ (self, opt, shared=None)
def build_history (self)
def build_dictionary (self)
def build_model (self)
def init_optim (self, params, optim_states=None, saved_optim_type=None)
def build_lr_scheduler (self, states=None, hard_reset=False)
def report (self)
def receive_metrics (self, metrics_dict)
def share (self)
def vectorize (self, obs, history, add_start=True, add_end=True, text_truncate=None, label_truncate=None)
def is_valid (self, obs)
def batchify (self, obs_batch, sort=False)
def match_batch (self, batch_reply, valid_inds, output=None)
def last_reply (self, use_reply='label')
def observe (self, observation)
def state_dict (self)
def save (self, path=None)
def load_state_dict (self, state_dict)
def load (self, path)
def reset (self)
def reset_metrics (self)
def act (self)
def batch_act (self, observations)
def set_interactive_mode (self, mode, shared)
def backward (self, loss)
def update_params (self)
def zero_grad (self)
Public Member Functions inherited from parlai.core.agents.Agent
def getID (self)
def epoch_done (self)
def shutdown (self)
def upgrade_opt (cls, opt_from_disk)
Additional Inherited Members
Static Public Member Functions inherited from parlai.core.torch_agent.TorchAgent
def dictionary_class ()
Public Attributes inherited from parlai.core.torch_agent.TorchAgent
use_cuda
fp16
replies
dict
metrics
opt
model
criterion
id
EMPTY
NULL_IDX
START_IDX
END_IDX
random
batch_idx
histsz
truncate
text_truncate
label_truncate
history
is_training
rank_candidates
add_person_tokens
optimizer
warmup_scheduler
scheduler
proj_rp
observation
Public Attributes inherited from parlai.core.agents.Agent
id
opt
observation
Static Public Attributes inherited from parlai.core.torch_agent.TorchAgent
string P1_TOKEN = '__p1__'
string P2_TOKEN = '__p2__'
Detailed Description
Definition at line 9 of file parrot.py.
Member Function Documentation
eval_step()
def parrot.ParrotAgent.eval_step (self, batch)
[Abstract] Process one batch but do not train on it.
Reimplemented from parlai.core.torch_agent.TorchAgent.
Definition at line 14 of file parrot.py.
Referenced by transresnet_multimodal.transresnet_multimodal.TransresnetMultimodalAgent.batch_act(), transresnet.transresnet.TransresnetAgent.batch_act(), parlai.agents.legacy_agents.seq2seq.torch_agent_v1.TorchAgent.batch_act(), and parlai.core.torch_agent.TorchAgent.batch_act().
train_step()
def parrot.ParrotAgent.train_step (self, batch)
[Abstract] Process one batch with training labels.
Reimplemented from parlai.core.torch_agent.TorchAgent.
Definition at line 10 of file parrot.py.
Referenced by transresnet_multimodal.transresnet_multimodal.TransresnetMultimodalAgent.batch_act(), transresnet.transresnet.TransresnetAgent.batch_act(), parlai.agents.legacy_agents.seq2seq.torch_agent_v1.TorchAgent.batch_act(), and parlai.core.torch_agent.TorchAgent.batch_act().
The documentation for this class was generated from the following file:
ParlAI/example_parlai_internal/agents/parrot/parrot.py