ParlAI: test_wizard_of_wikipedia.TestWoW Class Reference
test_wizard_of_wikipedia.TestWoW Class Reference
Public Member Functions
def test_output (self)
def run_display_test (self, kwargs)
Detailed Description
Basic tests on the train_model.py example.
Definition at line 23 of file test_wizard_of_wikipedia.py.
Member Function Documentation
run_display_test()
def test_wizard_of_wikipedia.TestWoW.run_display_test (self, kwargs)
Definition at line 75 of file test_wizard_of_wikipedia.py.
References parlai.core.worlds.create_task(), parlai.messenger.core.shared_utils.format, and parlai.messenger.core.run.setup_args().
Referenced by test_wizard_of_wikipedia.TestWoW.test_output().
test_output()
def test_wizard_of_wikipedia.TestWoW.test_output (self)
Definition at line 26 of file test_wizard_of_wikipedia.py.
References parlai.messenger.core.shared_utils.format, test_wizard_of_wikipedia.product_dict(), and test_wizard_of_wikipedia.TestWoW.run_display_test().
The documentation for this class was generated from the following file:
tests/tasks/test_wizard_of_wikipedia.py