ParlAI: parlai.core.worlds.DialogPartnerWorld Class Reference
parlai.core.worlds.DialogPartnerWorld Class Reference
Public Member Functions
def __init__ (self, opt, agents, shared=None)
def get_task_agent (self)
def parley (self)
def episode_done (self)
def epoch_done (self)
def report (self)
def num_examples (self)
def num_episodes (self)
def shutdown (self)
Public Member Functions inherited from parlai.core.worlds.World
def getID (self)
def display (self)
def share (self)
def get_agents (self)
def get_acts (self)
def get_time (self)
def get_total_exs (self)
def get_total_epochs (self)
def __enter__ (self)
def __exit__ (self, exc_type, exc_value, exc_traceback)
def reset (self)
def reset_metrics (self)
def update_counters (self)
Public Attributes
agents
acts
id
Public Attributes inherited from parlai.core.worlds.World
id
opt
agents
max_exs
total_exs
total_epochs
total_parleys
time
Static Public Attributes
maxsize
Detailed Description
Simple world for two agents communicating synchronously.
This basic world switches back and forth between two agents, giving each
agent one chance to speak per turn and passing that back to the other one.
Definition at line 250 of file worlds.py.
Member Function Documentation
episode_done()
def parlai.core.worlds.DialogPartnerWorld.episode_done (self)
Only the first agent indicates when the episode is done.
Reimplemented from parlai.core.worlds.World.
Definition at line 289 of file worlds.py.
References parlai.core.worlds.DialogPartnerWorld.acts.
epoch_done()
def parlai.core.worlds.DialogPartnerWorld.epoch_done (self)
Only the first agent indicates when the epoch is done.
Reimplemented from parlai.core.worlds.World.
Definition at line 296 of file worlds.py.
References parlai.core.worlds.World.get_task_agent().
get_task_agent()
def parlai.core.worlds.DialogPartnerWorld.get_task_agent (self)
Return task agent.
Reimplemented from parlai.core.worlds.World.
Definition at line 275 of file worlds.py.
References parlai.core.worlds.World.get_agents().
num_episodes()
def parlai.core.worlds.DialogPartnerWorld.num_episodes (self)
Return number of episodes.
Reimplemented from parlai.core.worlds.World.
Definition at line 324 of file worlds.py.
References parlai.core.worlds.World.get_task_agent().
Referenced by parlai.tasks.vqa_v1.agents.VQADataset._setup_image_data(), parlai.tasks.personality_captions.agents.DefaultDataset.add_cmdline_args(), and parlai.tasks.personality_captions.agents.DefaultDataset.num_examples().
num_examples()
def parlai.core.worlds.DialogPartnerWorld.num_examples (self)
Return number of examples.
Reimplemented from parlai.core.worlds.World.
Definition at line 318 of file worlds.py.
References parlai.core.worlds.World.get_task_agent().
parley()
def parlai.core.worlds.DialogPartnerWorld.parley (self)
Agent 0 goes first. Alternate between the two agents.
Reimplemented from parlai.core.worlds.World.
Reimplemented in parlai.tasks.wizard_of_wikipedia.worlds.InteractiveWorld, and parlai.tasks.convai2.worlds.InteractiveWorld.
Definition at line 279 of file worlds.py.
References parlai.core.worlds.DialogPartnerWorld.acts, parlai.core.worlds.World.agents, and parlai.core.worlds.World.update_counters().
report()
def parlai.core.worlds.DialogPartnerWorld.report (self)
Report all metrics of all subagents.
Definition at line 300 of file worlds.py.
References parlai.core.worlds.World.agents, and parlai.core.worlds.World.total_exs.
shutdown()
def parlai.core.worlds.DialogPartnerWorld.shutdown (self)
Shutdown each agent.
Reimplemented from parlai.core.worlds.World.
Definition at line 330 of file worlds.py.
References parlai.core.worlds.World.agents.
The documentation for this class was generated from the following file:
ParlAI/parlai/core/worlds.py