ParlAI: light_chats.graph.GraphFunction Class Reference
light_chats.graph.GraphFunction Class Reference
Public Member Functions
def __init__ (self, function_name, possible_arg_nums, arg_split_words, arg_find_type, arg_constraints, func_constraints, callback_triggers)
def valid_args (self, graph, args)
def handle (self, graph, args)
def func (self, graph, args)
def get_action_observation_format (self, action, descs)
def get_failure_action (self, graph, args, spec_fail='failed')
def get_find_fail_text (self, arg_idx)
def get_improper_args_text (self, num_args)
def evaluate_constraint_set (self, graph, args, constraints)
def check_possibilites_vs_constraints (self, graph, output_args, arg_idx, possible_ids)
def parse_text_to_args (self, graph, actor_id, text)
def try_callback_override_args (self, graph, args)
def parse_descs_to_args_helper (self, graph, args, output_args, arg_find_idx=None)
def parse_descs_to_args (self, graph, args)
def get_name (self)
def get_canonical_form (self, graph, args)
def get_reverse (self, graph, args)
Public Attributes
name
possible_arg_nums
arg_split_words
arg_find_type
arg_constraints
func_constraints
callback_triggers
formats
Static Public Attributes
format_observation = format_observation
Detailed Description
Initial description of function should only contain what the arguments
are as set up by init, establishing a number to type relationship like:
[Actor, item actor is carrying, container in same room as actor]
Definition at line 85 of file graph.py.
Constructor & Destructor Documentation
__init__()
def light_chats.graph.GraphFunction.__init__ (self, function_name, possible_arg_nums, arg_split_words, arg_find_type, arg_constraints, func_constraints, callback_triggers)
Create a new graph function
args:
function name - name or array of aliases for the function
possible_arg_nums - number or array of valid arg numbers for
    determining if given args are valid or for breaking text into
    a valid number of arguments before they're parsed into descs
arg_split_words - array of words to be used to split input args
arg_find_type - array of args for desc_to_nodes to use to find the
    argument at the given index, following the form
    {'type': <search type>, 'from': <arg idx of reference>}. If a
    list is given for each argument use the same element for each
arg_constraints - constraints on whether or not found arguments are
    valid to be matched during the parsing step. Form is array of
    arrays of constraint types
func_constraints - constraints on whether a function will pass with
    the given args, format is array of constraint types
callback_triggers - callback hook names and argument idxs for making
    calls to callback functions upon completion of this function call
Definition at line 91 of file graph.py.
References light_chats.graph.GraphFunction.arg_constraints, light_chats.graph.GraphFunction.arg_find_type, light_chats.graph.GraphFunction.arg_split_words, light_chats.graph.GraphFunction.callback_triggers, light_chats.graph.GraphFunction.evaluate_constraint_set(), light_chats.graph.GraphFunction.formats, light_chats.graph.GraphFunction.func(), light_chats.graph.GraphFunction.func_constraints, light_chats.graph.GraphFunction.get_failure_action(), light_chats.graph.GraphFunction.name, light_chats.graph.GraphFunction.parse_descs_to_args(), and light_chats.graph.GraphFunction.possible_arg_nums.
Member Function Documentation
check_possibilites_vs_constraints()
def light_chats.graph.GraphFunction.check_possibilites_vs_constraints (self, graph, output_args, arg_idx, possible_ids)
Iterate through the given possible ids for a particular arg index
and see if any match all the constraints for that argument
Returns (True, valid_ID) on success
Returns (False, violator_action) on failure
Definition at line 243 of file graph.py.
References light_chats.graph.GraphFunction.arg_constraints, and light_chats.graph.GraphFunction.evaluate_constraint_set().
Referenced by light_chats.graph.GraphFunction.parse_text_to_args().
evaluate_constraint_set()
def light_chats.graph.GraphFunction.evaluate_constraint_set (self, graph, args, constraints)
Check a particular set of arguments against the given constraints
returns (True, cons_passed, None) if the constraints all pass
returns (False, cons_passed, failure_action) if any constraint fails
Reimplemented in light_chats.graph.TellFunction.
Definition at line 221 of file graph.py.
Referenced by light_chats.graph.GraphFunction.__init__(), light_chats.graph.GraphFunction.check_possibilites_vs_constraints(), and light_chats.graph.TellFunction.format_observation().
func()
def light_chats.graph.GraphFunction.func (self, graph, args)
Execute action on the given graph
Notation for documentation should be in the form of an action with <>'s
around the incoming arguments in the order they are passed in. Optional
arguments can be denoted by putting the clause in []'s.
ex:
<Actor> does thing with <object> [and other <object>]
Reimplemented in light_chats.graph.UnfollowFunction, light_chats.graph.LookFunction, light_chats.graph.HealthFunction, light_chats.graph.InventoryFunction, light_chats.graph.WaitFunction, light_chats.graph.ExamineFunction, light_chats.graph.UnlockFunction, light_chats.graph.LockFunction, light_chats.graph.IngestFunction, light_chats.graph.RemoveObjectFunction, light_chats.graph.EquipObjectFunction, light_chats.graph.StealObjectFunction, light_chats.graph.GiveObjectFunction, light_chats.graph.DropObjectFunction, light_chats.graph.PutObjectInFunction, light_chats.graph.GetObjectFunction, light_chats.graph.HugFunction, light_chats.graph.HitFunction, light_chats.graph.FollowFunction, light_chats.graph.MoveAgentFunction, light_chats.graph.UseFunction, light_chats.graph.TellFunction, and light_chats.graph.SayFunction.
Definition at line 181 of file graph.py.
Referenced by light_chats.graph.GraphFunction.__init__().
get_action_observation_format()
def light_chats.graph.GraphFunction.get_action_observation_format (self, action, descs)
Given the action, return text to be filled by the parsed args
Allowed to alter the descriptions if necessary
Allowed to use the descriptions to determine the correct format as well
Reimplemented in light_chats.graph.HealthFunction, light_chats.graph.InventoryFunction, light_chats.graph.ExamineFunction, light_chats.graph.MoveAgentFunction, and light_chats.graph.UseFunction.
Definition at line 192 of file graph.py.
References light_chats.graph.GraphFunction.formats.
get_canonical_form()
def light_chats.graph.GraphFunction.get_canonical_form (self, graph, args)
Get canonical form for the given args on this function
Reimplemented in light_chats.graph.GetObjectFunction, and light_chats.graph.TellFunction.
Definition at line 435 of file graph.py.
References light_chats.graph.GraphFunction.arg_split_words, light_chats.graph.GraphFunction.get_name(), and light_chats.graph.GraphFunction.possible_arg_nums.
get_failure_action()
def light_chats.graph.GraphFunction.get_failure_action (self, graph, args, spec_fail = 'failed')
Returns an action for if the resolution of this function fails
Definition at line 201 of file graph.py.
References light_chats.graph.GraphFunction.get_name().
Referenced by light_chats.graph.GraphFunction.__init__().
get_find_fail_text()
def light_chats.graph.GraphFunction.get_find_fail_text (self, arg_idx)
Text displayed when an arg find during parse_text_to_args call
fails to find valid targets for the function.
Can be overridden to provide different messages for different failed
arguments.
Reimplemented in light_chats.graph.ExamineFunction, light_chats.graph.IngestFunction, light_chats.graph.RemoveObjectFunction, light_chats.graph.EquipObjectFunction, light_chats.graph.StealObjectFunction, light_chats.graph.GiveObjectFunction, light_chats.graph.DropObjectFunction, light_chats.graph.PutObjectInFunction, light_chats.graph.GetObjectFunction, light_chats.graph.HugFunction, light_chats.graph.HitFunction, light_chats.graph.MoveAgentFunction, and light_chats.graph.UseFunction.
Definition at line 210 of file graph.py.
Referenced by light_chats.graph.GraphFunction.parse_text_to_args().
get_name()
def light_chats.graph.GraphFunction.get_name (self)
Get the canonical name of this function
Reimplemented in light_chats.graph.TellFunction.
Definition at line 428 of file graph.py.
References light_chats.graph.GraphFunction.name.
Referenced by light_chats.graph.MoveAgentFunction.follow_agent(), light_chats.graph.SayFunction.func(), light_chats.graph.TellFunction.func(), light_chats.graph.UseFunction.func(), light_chats.graph.MoveAgentFunction.func(), light_chats.graph.FollowFunction.func(), light_chats.graph.HitFunction.func(), light_chats.graph.HugFunction.func(), light_chats.graph.GetObjectFunction.func(), light_chats.graph.PutObjectInFunction.func(), light_chats.graph.DropObjectFunction.func(), light_chats.graph.GiveObjectFunction.func(), light_chats.graph.StealObjectFunction.func(), light_chats.graph.EquipObjectFunction.func(), light_chats.graph.RemoveObjectFunction.func(), light_chats.graph.IngestFunction.func(), light_chats.graph.LockFunction.func(), light_chats.graph.UnlockFunction.func(), light_chats.graph.ExamineFunction.func(), light_chats.graph.WaitFunction.func(), light_chats.graph.InventoryFunction.func(), light_chats.graph.HealthFunction.func(), light_chats.graph.LookFunction.func(), light_chats.graph.UnfollowFunction.func(), light_chats.graph.GraphFunction.get_canonical_form(), and light_chats.graph.GraphFunction.get_failure_action().
get_reverse()
def light_chats.graph.GraphFunction.get_reverse (self, graph, args)
Function to parse the graph and args and return the reverse
function and args
Reimplemented in light_chats.graph.SoloFunction, light_chats.graph.ExamineFunction, light_chats.graph.UnlockFunction, light_chats.graph.LockFunction, light_chats.graph.RemoveObjectFunction, light_chats.graph.EquipObjectFunction, light_chats.graph.StealObjectFunction, light_chats.graph.GiveObjectFunction, light_chats.graph.DropObjectFunction, light_chats.graph.PutObjectInFunction, light_chats.graph.GetObjectFunction, light_chats.graph.HugFunction, and light_chats.graph.FollowFunction.
Definition at line 452 of file graph.py.
parse_descs_to_args()
def light_chats.graph.GraphFunction.parse_descs_to_args (self, graph, args)
iterates through the args and the constraints, solving dependency
order on the fly.
Reimplemented in light_chats.graph.StealObjectFunction, light_chats.graph.DropObjectFunction, light_chats.graph.GetObjectFunction, and light_chats.graph.MoveAgentFunction.
Definition at line 386 of file graph.py.
References light_chats.graph.GraphFunction.arg_find_type, light_chats.graph.GraphFunction.parse_descs_to_args_helper(), light_chats.graph.GraphFunction.possible_arg_nums, and light_chats.graph.GraphFunction.try_callback_override_args().
Referenced by light_chats.graph.GraphFunction.__init__(), light_chats.graph.TellFunction.format_observation(), light_chats.graph.GraphFunction.parse_text_to_args(), and light_chats.graph.TellFunction.parse_text_to_args().
parse_text_to_args()
def light_chats.graph.GraphFunction.parse_text_to_args (self, graph, actor_id, text)
Breaks text into function arguments based on this function's
delimiters
Returns:
(None, display text, None) if parsing failed to find valid candidates
(True, arg_ids, canonical_text_args) if parsing and constraints succeed
(False, Failure action, matched_args)
if parsing succeeds but constraints fail
Reimplemented in light_chats.graph.MoveAgentFunction, and light_chats.graph.TellFunction.
Definition at line 269 of file graph.py.
References light_chats.graph.GraphFunction.arg_constraints, light_chats.graph.GraphFunction.arg_find_type, light_chats.graph.GraphFunction.arg_split_words, light_chats.graph.GraphFunction.check_possibilites_vs_constraints(), light_chats.graph.GraphFunction.get_find_fail_text(), light_chats.graph.GraphFunction.get_improper_args_text(), light_chats.graph.GraphFunction.parse_descs_to_args(), light_chats.graph.GraphFunction.parse_descs_to_args_helper(), and light_chats.graph.GraphFunction.possible_arg_nums.
The documentation for this class was generated from the following file:
ParlAI/parlai/mturk/tasks/light/light_chats/graph.py