ParlAI: tests.test_pytorch_data_teacher.TestPytorchDataTeacher Class Reference
tests.test_pytorch_data_teacher.TestPytorchDataTeacher Class Reference
Public Member Functions
def test_shuffle (self)
def test_pyt_preprocess (self)
def test_valid_pyt_batchsort (self)
def test_pyt_batchsort_field (self)
def test_pyt_train (self)
def test_pyt_train_stream (self)
def test_pyt_train_stream_ordered (self)
def test_pyt_preprocess_train (self)
def test_pyt_batchsort_train (self)
def test_pyt_batchsort_train_stream (self)
def test_pyt_batchsort_train_preprocess (self)
def test_pytd_teacher (self)
def test_pyt_multitask (self)
Detailed Description
Various tests for PytorchDataTeacher
Unit Tests
Definition at line 62 of file test_pytorch_data_teacher.py.
Member Function Documentation
test_pyt_batchsort_field()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_batchsort_field (self)
Test that the batchsort actually works for Pytorch Data Teacher
That is, for every batch except the last one, check that the length
of each example (determined by batchsort_field) is within
`batch-length-range`
Definition at line 224 of file test_pytorch_data_teacher.py.
References parlai.core.agents.create_agent(), parlai.core.worlds.create_task(), parlai.core.pytorch_data_teacher.ep_length(), parlai.messenger.core.shared_utils.format, and tests.test_pytorch_data_teacher.solved_task().
test_pyt_batchsort_train()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_batchsort_train (self)
Definition at line 360 of file test_pytorch_data_teacher.py.
References tests.test_pytorch_data_teacher.TestPytorchDataTeacher._pyt_batchsort_train().
test_pyt_batchsort_train_preprocess()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_batchsort_train_preprocess (self)
Definition at line 368 of file test_pytorch_data_teacher.py.
References tests.test_pytorch_data_teacher.TestPytorchDataTeacher._pyt_batchsort_train().
test_pyt_batchsort_train_stream()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_batchsort_train_stream (self)
Definition at line 364 of file test_pytorch_data_teacher.py.
References tests.test_pytorch_data_teacher.TestPytorchDataTeacher._pyt_batchsort_train().
test_pyt_multitask()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_multitask (self)
Unit test for ensuring that PytorchDataTeacher correctly handles
multitasking.
This test will iterate through the following scenarios:
    1. 2 `pytorch_teacher_task`s
    2. 1 `pytorch_teacher_task`, 1 regular ParlAI task
    3. 1 `pytorch_teacher_task`, 1 `pytorch_teacher_dataset`
    4. 1 `pytorch_teacher_dataset`, 1 regular ParlAI task
    5. 2 `pytorch_teacher_dataset`s
Definition at line 412 of file test_pytorch_data_teacher.py.
References parlai.messenger.core.shared_utils.format.
test_pyt_preprocess()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_preprocess (self)
Test that the preprocess functionality works with the PytorchDataTeacher
with a sample TorchAgent (here, the Seq2seq model).
This tests whether the action provided by the preprocessed teacher
is equivalent to the agent's observation after the agent processes it.
Definition at line 106 of file test_pytorch_data_teacher.py.
References mastering_the_dungeon.mturk.tasks.MTD.run.bool, parlai.core.agents.create_agent(), parlai.core.agents.create_task_agent_from_taskname(), and parlai.messenger.core.shared_utils.format.
test_pyt_preprocess_train()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_preprocess_train (self)
Test that the preprocess functionality works with the PytorchDataTeacher
with a sample TorchAgent (here, the Seq2seq model).
This tests whether an agent can train to completion with
these preprocessed examples
Definition at line 318 of file test_pytorch_data_teacher.py.
References parlai.messenger.core.shared_utils.format, and tests.test_pytorch_data_teacher.solved_task().
test_pyt_train()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_train (self)
Definition at line 306 of file test_pytorch_data_teacher.py.
References tests.test_pytorch_data_teacher.TestPytorchDataTeacher._pyt_train().
test_pyt_train_stream()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_train_stream (self)
Definition at line 310 of file test_pytorch_data_teacher.py.
References tests.test_pytorch_data_teacher.TestPytorchDataTeacher._pyt_train().
test_pyt_train_stream_ordered()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_train_stream_ordered (self)
Definition at line 314 of file test_pytorch_data_teacher.py.
References tests.test_pytorch_data_teacher.TestPytorchDataTeacher._pyt_train().
test_pytd_teacher()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pytd_teacher (self)
Test that the pytorch teacher works with given Pytorch Datasets
as well
Definition at line 371 of file test_pytorch_data_teacher.py.
References parlai.core.agents.create_task_agent_from_taskname(), and parlai.messenger.core.shared_utils.format.
test_shuffle()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_shuffle (self)
Simple test to ensure that dataloader is initialized with correct
data sampler
Definition at line 67 of file test_pytorch_data_teacher.py.
References parlai.core.agents.create_task_agent_from_taskname(), and parlai.messenger.core.shared_utils.format.
test_valid_pyt_batchsort()
def tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_valid_pyt_batchsort (self)
Tests that batchsort *works* for two epochs; that is, that
every example is seen both epochs
Definition at line 157 of file test_pytorch_data_teacher.py.
References mastering_the_dungeon.mturk.tasks.MTD.run.bool, parlai.core.agents.create_agent(), parlai.core.worlds.create_task(), and parlai.agents.tfidf_retriever.build_tfidf.type.
The documentation for this class was generated from the following file:
tests/test_pytorch_data_teacher.py