ParlAI: parlai.agents.tfidf_retriever.doc_db.DocDB Class Reference
parlai.agents.tfidf_retriever.doc_db.DocDB Class Reference
Public Member Functions
def __init__ (self, db_path=None)
def __enter__ (self)
def __exit__ (self, args)
def path (self)
def close (self)
def get_doc_ids (self)
def get_doc_text (self, doc_id)
def get_doc_value (self, doc_id)
def add (self, triples)
Public Attributes
path
connection
Detailed Description
Sqlite backed document storage.
Implements get_doc_text(doc_id).
Definition at line 15 of file doc_db.py.
Constructor & Destructor Documentation
__init__()
def parlai.agents.tfidf_retriever.doc_db.DocDB.__init__ (self, db_path = None)
Definition at line 21 of file doc_db.py.
Member Function Documentation
__enter__()
def parlai.agents.tfidf_retriever.doc_db.DocDB.__enter__ (self)
Definition at line 25 of file doc_db.py.
__exit__()
def parlai.agents.tfidf_retriever.doc_db.DocDB.__exit__ (self, args)
Definition at line 28 of file doc_db.py.
References parlai.agents.tfidf_retriever.doc_db.DocDB.close().
add()
def parlai.agents.tfidf_retriever.doc_db.DocDB.add (self, triples)
Definition at line 67 of file doc_db.py.
References parlai.agents.tfidf_retriever.doc_db.DocDB.connection.
close()
def parlai.agents.tfidf_retriever.doc_db.DocDB.close (self)
Close the connection to the database.
Definition at line 35 of file doc_db.py.
References parlai.agents.tfidf_retriever.doc_db.DocDB.connection.
Referenced by parlai.agents.tfidf_retriever.doc_db.DocDB.__exit__().
get_doc_ids()
def parlai.agents.tfidf_retriever.doc_db.DocDB.get_doc_ids (self)
Fetch all ids of docs stored in the db.
Definition at line 39 of file doc_db.py.
References parlai.agents.tfidf_retriever.doc_db.DocDB.connection.
get_doc_text()
def parlai.agents.tfidf_retriever.doc_db.DocDB.get_doc_text (self, doc_id)
Fetch the raw text of the doc for 'doc_id'.
Definition at line 47 of file doc_db.py.
References parlai.agents.tfidf_retriever.doc_db.DocDB.connection.
get_doc_value()
def parlai.agents.tfidf_retriever.doc_db.DocDB.get_doc_value (self, doc_id)
Fetch the raw text of the doc for 'doc_id'.
Definition at line 57 of file doc_db.py.
References parlai.agents.tfidf_retriever.doc_db.DocDB.connection.
path()
def parlai.agents.tfidf_retriever.doc_db.DocDB.path (self)
Return the path to the file that backs this database.
Definition at line 31 of file doc_db.py.
References parlai.agents.tfidf_retriever.doc_db.DocDB.path.
Referenced by interactive.MyHandler.do_GET(), interactive.MyHandler.do_POST(), and interactive.MyHandler.respond().
Member Data Documentation
connection
parlai.agents.tfidf_retriever.doc_db.DocDB.connection
Definition at line 23 of file doc_db.py.
Referenced by parlai.agents.tfidf_retriever.doc_db.DocDB.add(), parlai.agents.tfidf_retriever.doc_db.DocDB.close(), parlai.agents.tfidf_retriever.doc_db.DocDB.get_doc_ids(), parlai.agents.tfidf_retriever.doc_db.DocDB.get_doc_text(), and parlai.agents.tfidf_retriever.doc_db.DocDB.get_doc_value().
path
parlai.agents.tfidf_retriever.doc_db.DocDB.path
Definition at line 22 of file doc_db.py.
Referenced by parlai.scripts.interactive_web.MyHandler.do_GET(), interactive.MyHandler.do_GET(), interactive.MyHandler.do_POST(), parlai.agents.tfidf_retriever.doc_db.DocDB.path(), and interactive.MyHandler.respond().
The documentation for this class was generated from the following file:
parlai/agents/tfidf_retriever/doc_db.py