ParlAI: parlai.core.pytorch_data_teacher.ParlAIConcatDataset Class Reference
parlai.core.pytorch_data_teacher.ParlAIConcatDataset Class Reference
Public Member Functions
def num_episodes (self)
def num_examples (self)
Static Public Attributes
maxsize
Detailed Description
Override to set num_eps and num_exs.
Definition at line 586 of file pytorch_data_teacher.py.
Member Function Documentation
num_episodes()
def parlai.core.pytorch_data_teacher.ParlAIConcatDataset.num_episodes (self)
Return the number of episodes.
Definition at line 590 of file pytorch_data_teacher.py.
Referenced by parlai.tasks.vqa_v1.agents.VQADataset._setup_image_data(), parlai.tasks.personality_captions.agents.DefaultDataset.add_cmdline_args(), and parlai.tasks.personality_captions.agents.DefaultDataset.num_examples().
num_examples()
def parlai.core.pytorch_data_teacher.ParlAIConcatDataset.num_examples (self)
Return the number of examples.
Definition at line 595 of file pytorch_data_teacher.py.
Referenced by parlai.core.worlds.HogwildWorld.get_total_epochs().
The documentation for this class was generated from the following file:
ParlAI/parlai/core/pytorch_data_teacher.py