ParlAI: parlai.agents.tfidf_retriever.tokenizers.tokenizer.Tokenizer Class Reference
parlai.agents.tfidf_retriever.tokenizers.tokenizer.Tokenizer Class Reference
Public Member Functions
def tokenize (self, text)
def shutdown (self)
def __del__ (self)
Detailed Description
Base tokenizer class.
Tokenizers implement tokenize, which should return a Tokens class.
Definition at line 132 of file tokenizer.py.
Constructor & Destructor Documentation
__del__()
def parlai.agents.tfidf_retriever.tokenizers.tokenizer.Tokenizer.__del__ (self)
Definition at line 143 of file tokenizer.py.
Member Function Documentation
shutdown()
def parlai.agents.tfidf_retriever.tokenizers.tokenizer.Tokenizer.shutdown (self)
Definition at line 140 of file tokenizer.py.
Referenced by parlai.core.worlds.World.__exit__(), parlai.core.worlds.HogwildWorld.display(), and parlai.core.worlds.HogwildWorld.episode_done().
tokenize()
def parlai.agents.tfidf_retriever.tokenizers.tokenizer.Tokenizer.tokenize (self, text)
Definition at line 137 of file tokenizer.py.
Referenced by parlai.core.dict.DictionaryAgent.act(), parlai.core.dict.DictionaryAgent.span_tokenize(), and parlai.core.dict.DictionaryAgent.txt2vec().
The documentation for this class was generated from the following file:
parlai/agents/tfidf_retriever/tokenizers/tokenizer.py