ParlAI: parlai.core.params Namespace Reference
parlai.core.params Namespace Reference
Classes
class CustomHelpFormatter
class ParlaiParser
Functions
def print_git_commit ()
def print_announcements (opt)
def get_model_name (opt)
def str2bool (value)
def str2floats (s)
def str2class (value)
def class2str (value)
def fix_underscores (args)
Function Documentation
class2str()
def parlai.core.params.class2str (value)
Inverse of params.str2class().
Definition at line 145 of file params.py.
References generate_task_READMEs.str.
Referenced by parlai.core.params.ParlaiParser.add_model_subargs().
fix_underscores()
def parlai.core.params.fix_underscores (args)
Convert underscores to hyphens in args.
For example, converts '--gradient_clip' to '--gradient-clip'.
:param args: iterable, possibly containing args strings with underscores.
Definition at line 153 of file params.py.
References parlai.agents.tfidf_retriever.build_tfidf.type.
Referenced by parlai.core.params.ParlaiParser.add_argument(), parlai.core.params.ParlaiParser.add_argument_group(), and parlai.core.params.ParlaiParser.parse_known_args().
get_model_name()
def parlai.core.params.get_model_name (opt)
Get the model name from either `--model` or `--model-file`.
Definition at line 100 of file params.py.
References parlai.utils.misc.load_opt_file(), and parlai.agents.legacy_agents.seq2seq.utils_v0.modelzoo_path().
Referenced by parlai.core.params.ParlaiParser.add_extra_args(), and parlai.core.agents.create_agent().
print_announcements()
def parlai.core.params.print_announcements (opt)
Output any announcements the ParlAI team wishes to make to users.
Also gives the user the option to suppress the output.
Definition at line 45 of file params.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.scripts.eval_model.eval_model(), and parlai.scripts.train_model.TrainLoop.train().
print_git_commit()
def parlai.core.params.print_git_commit ()
Print the current git commit of ParlAI and parlai_internal.
Definition at line 24 of file params.py.
str2bool()
def parlai.core.params.str2bool (value)
Convert 'yes', 'false', '1', etc. into a boolean.
Definition at line 115 of file params.py.
str2class()
def parlai.core.params.str2class (value)
From import path string, returns the class specified.
For example, the string 'parlai.agents.drqa.drqa:SimpleDictionaryAgent'
returns <class 'parlai.agents.drqa.drqa.SimpleDictionaryAgent'>.
Definition at line 131 of file params.py.
Referenced by parlai.scripts.build_dict.build_dict(), and parlai.scripts.build_dict.setup_args().
str2floats()
def parlai.core.params.str2floats (s)
Look for single float or comma-separated floats.
Definition at line 126 of file params.py.
References make_control_dataset.float.