ParlAI: parlai.scripts.eval_model Namespace Reference
parlai.scripts.eval_model Namespace Reference
Functions
def setup_args (parser=None)
def eval_model (opt, print_parser=None)
Variables
def parser = setup_args()
Function Documentation
eval_model()
def parlai.scripts.eval_model.eval_model (opt, print_parser = None)
Evaluates a model.
:param opt: tells the evaluation function how to run
:param bool print_parser: if provided, prints the options that are set within the
    model after loading the model
:return: the final result of calling report()
Definition at line 97 of file eval_model.py.
References parlai.core.metrics.aggregate_task_reports(), parlai.core.agents.create_agent(), parlai.messenger.core.shared_utils.format, and parlai.core.params.print_announcements().
setup_args()
def parlai.scripts.eval_model.setup_args (parser = None)
Definition at line 29 of file eval_model.py.
References parlai.core.worlds.create_task(), make_control_dataset.float, and parlai.messenger.core.shared_utils.format.
Variable Documentation
parser
def parlai.scripts.eval_model.parser = setup_args()
Definition at line 137 of file eval_model.py.