ParlAI: parlai.scripts.convert_data_to_fasttext_format Namespace Reference
parlai.scripts.convert_data_to_fasttext_format Namespace Reference
Functions
def dump_data (opt)
def main ()
Function Documentation
dump_data()
def parlai.scripts.convert_data_to_fasttext_format.dump_data (opt)
Definition at line 24 of file convert_data_to_fasttext_format.py.
References parlai.core.worlds.create_task(), and parlai.messenger.core.shared_utils.format.
Referenced by parlai.scripts.convert_data_to_fasttext_format.main().
main()
def parlai.scripts.convert_data_to_fasttext_format.main ()
Definition at line 67 of file convert_data_to_fasttext_format.py.
References parlai.scripts.convert_data_to_fasttext_format.dump_data().