ParlAI: parlai.scripts.verify_data Namespace Reference
parlai.scripts.verify_data Namespace Reference
Functions
def setup_args (parser=None)
def report (world, counts, log_time)
def warn (txt, act, opt)
def verify (opt, printargs=None, print_parser=None)
Variables
def parser = setup_args()
report_text
report_log
print_parser
Function Documentation
report()
def parlai.scripts.verify_data.report (world, counts, log_time)
Definition at line 34 of file verify_data.py.
Referenced by parlai.scripts.verify_data.verify().
setup_args()
def parlai.scripts.verify_data.setup_args (parser = None)
Definition at line 23 of file verify_data.py.
verify()
def parlai.scripts.verify_data.verify (opt, printargs = None, print_parser = None)
Definition at line 57 of file verify_data.py.
References parlai.core.worlds.create_task(), make_control_dataset.float, parlai.messenger.core.shared_utils.format, parlai.scripts.verify_data.report(), and parlai.scripts.verify_data.warn().
warn()
def parlai.scripts.verify_data.warn (txt, act, opt)
Definition at line 50 of file verify_data.py.
References generate_task_READMEs.str, and parlai.utils.misc.warn_once().
Referenced by parlai.scripts.verify_data.verify().
Variable Documentation
parser
def parlai.scripts.verify_data.parser = setup_args()
Definition at line 138 of file verify_data.py.
print_parser
parlai.scripts.verify_data.print_parser
Definition at line 140 of file verify_data.py.
report_log
parlai.scripts.verify_data.report_log
Definition at line 139 of file verify_data.py.
report_text
parlai.scripts.verify_data.report_text
Definition at line 139 of file verify_data.py.