ParlAI: parlai.agents.tfidf_retriever.utils Namespace Reference
parlai.agents.tfidf_retriever.utils Namespace Reference
Functions
def save_sparse_csr (filename, matrix, metadata=None)
def save_sparse_tensor (filename, matrix, metadata=None)
def load_sparse_csr (filename)
def load_sparse_tensor (filename)
def hash (token, num_buckets)
def normalize (text)
def filter_word (text)
def filter_ngram (gram, mode='any')
Variables
dictionary STOPWORDS
Function Documentation
filter_ngram()
def parlai.agents.tfidf_retriever.utils.filter_ngram (gram, mode = 'any')
Decide whether to keep or discard an n-gram.
Args:
    gram: list of tokens (length N)
    mode: Option to throw out ngram if
      'any': any single token passes filter_word
      'all': all tokens pass filter_word
      'ends': book-ended by filterable tokens
Definition at line 261 of file utils.py.
References parlai.agents.tfidf_retriever.utils.filter_word().
filter_word()
def parlai.agents.tfidf_retriever.utils.filter_word (text)
Take out english stopwords, punctuation, and compound endings.
Definition at line 251 of file utils.py.
References parlai.agents.tfidf_retriever.utils.normalize().
Referenced by parlai.agents.tfidf_retriever.utils.filter_ngram().
hash()
def parlai.agents.tfidf_retriever.utils.hash (token, num_buckets)
Unsigned 32 bit murmurhash for feature hashing.
Definition at line 68 of file utils.py.
load_sparse_csr()
def parlai.agents.tfidf_retriever.utils.load_sparse_csr (filename)
Definition at line 47 of file utils.py.
load_sparse_tensor()
def parlai.agents.tfidf_retriever.utils.load_sparse_tensor (filename)
Definition at line 55 of file utils.py.
normalize()
def parlai.agents.tfidf_retriever.utils.normalize (text)
Resolve different type of unicode encodings.
Definition at line 244 of file utils.py.
References parlai.agents.tfidf_retriever.build_tfidf.type.
Referenced by parlai.agents.tfidf_retriever.utils.filter_word().
save_sparse_csr()
def parlai.agents.tfidf_retriever.utils.save_sparse_csr (filename, matrix, metadata = None)
Definition at line 26 of file utils.py.
save_sparse_tensor()
def parlai.agents.tfidf_retriever.utils.save_sparse_tensor (filename, matrix, metadata = None)
Definition at line 37 of file utils.py.
Variable Documentation
STOPWORDS
dictionary parlai.agents.tfidf_retriever.utils.STOPWORDS
Definition at line 78 of file utils.py.