ParlAI: parlai.messenger.core.server_utils Namespace Reference
parlai.messenger.core.server_utils Namespace Reference
Functions
def setup_heroku_server (task_name)
def delete_heroku_server (task_name)
def setup_local_server (task_name)
def delete_local_server (task_name)
def setup_server (task_name, local=False)
def delete_server (task_name, local=False)
Variables
string region_name = 'us-east-1'
user_name = getpass.getuser()
parent_dir = os.path.dirname(os.path.abspath(__file__))
string server_source_directory_name = 'server'
string heroku_server_directory_name = 'heroku_server'
string local_server_directory_name = 'local_server'
string task_directory_name = 'task'
server_process = None
string heroku_url = 'https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli'
Function Documentation
delete_heroku_server()
def parlai.messenger.core.server_utils.delete_heroku_server (task_name)
Definition at line 208 of file server_utils.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.messenger.core.server_utils.delete_server(), and parlai.messenger.core.server_utils.setup_heroku_server().
delete_local_server()
def parlai.messenger.core.server_utils.delete_local_server (task_name)
Definition at line 273 of file server_utils.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.messenger.core.server_utils.delete_server().
delete_server()
def parlai.messenger.core.server_utils.delete_server (task_name, local = False)
Definition at line 291 of file server_utils.py.
References parlai.messenger.core.server_utils.delete_heroku_server(), and parlai.messenger.core.server_utils.delete_local_server().
setup_heroku_server()
def parlai.messenger.core.server_utils.setup_heroku_server (task_name)
Definition at line 33 of file server_utils.py.
References parlai.messenger.core.server_utils.delete_heroku_server(), parlai.messenger.core.shared_utils.format, and parlai.mturk.core.dev.test.test_full_system.input.
Referenced by parlai.messenger.core.server_utils.setup_server().
setup_local_server()
def parlai.messenger.core.server_utils.setup_local_server (task_name)
Definition at line 236 of file server_utils.py.
References parlai.messenger.core.shared_utils.format, and parlai.mturk.core.dev.test.test_full_system.input.
Referenced by parlai.messenger.core.server_utils.setup_server().
setup_server()
def parlai.messenger.core.server_utils.setup_server (task_name, local = False)
Definition at line 285 of file server_utils.py.
References parlai.messenger.core.server_utils.setup_heroku_server(), and parlai.messenger.core.server_utils.setup_local_server().
Variable Documentation
heroku_server_directory_name
string parlai.messenger.core.server_utils.heroku_server_directory_name = 'heroku_server'
Definition at line 24 of file server_utils.py.
heroku_url
string parlai.messenger.core.server_utils.heroku_url = 'https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli'
Definition at line 30 of file server_utils.py.
local_server_directory_name
string parlai.messenger.core.server_utils.local_server_directory_name = 'local_server'
Definition at line 25 of file server_utils.py.
parent_dir
parlai.messenger.core.server_utils.parent_dir = os.path.dirname(os.path.abspath(__file__))
Definition at line 22 of file server_utils.py.
region_name
string parlai.messenger.core.server_utils.region_name = 'us-east-1'
Definition at line 19 of file server_utils.py.
server_process
parlai.messenger.core.server_utils.server_process = None
Definition at line 28 of file server_utils.py.
server_source_directory_name
string parlai.messenger.core.server_utils.server_source_directory_name = 'server'
Definition at line 23 of file server_utils.py.
task_directory_name
string parlai.messenger.core.server_utils.task_directory_name = 'task'
Definition at line 26 of file server_utils.py.
user_name
parlai.messenger.core.server_utils.user_name = getpass.getuser()
Definition at line 20 of file server_utils.py.