ParlAI: parlai.agents.legacy_agents.seq2seq.utils_v1 Namespace Reference
parlai.agents.legacy_agents.seq2seq.utils_v1 Namespace Reference
Functions
def set_namedtuple_defaults (namedtuple, default=None)
def padded_tensor (items, pad_idx=0, use_cuda=False, left_padded=False, max_len=None)
def argsort (keys, lists, descending=False)
Variables
int NEAR_INF = 1e20
Function Documentation
argsort()
def parlai.agents.legacy_agents.seq2seq.utils_v1.argsort (keys, lists, descending = False)
Reorder each list in lists by the (descending) sorted order of keys.
:param iter keys: Keys to order by.
:param list[list] lists: Lists to reordered by keys's order.
                         Correctly handles lists and 1-D tensors.
:param bool descending: Use descending order if true.
:returns: The reordered items.
Definition at line 101 of file utils_v1.py.
Referenced by controllable_seq2seq.controllable_seq2seq.ControllableSeq2seqAgent.batchify(), parlai.agents.legacy_agents.seq2seq.torch_agent_v1.TorchAgent.batchify(), parlai.core.torch_agent.TorchAgent.batchify(), parlai.agents.fairseq.fairseq.FairseqAgent.eval_step(), and tests.test_utils.TestUtils.test_argsort().
padded_tensor()
def parlai.agents.legacy_agents.seq2seq.utils_v1.padded_tensor (items, pad_idx = 0, use_cuda = False, left_padded = False, max_len = None)
Create a right-padded matrix from an uneven list of lists.
Returns (padded, lengths), where padded is the padded matrix, and lengths
is a list containing the lengths of each row.
Matrix is right-padded (filled to the right) by default, but can be
left padded if the flag is set to True.
Matrix can also be placed on cuda automatically.
:param list[iter[int]] items: List of items
:param bool sort: If True, orders by the length
:param int pad_idx: the value to use for padding
:param bool use_cuda: if true, places `padded` on GPU
:param bool left_padded:
:param int max_len: if None, the max length is the maximum item length
:returns: (padded, lengths) tuple
:rtype: (Tensor[int64], list[int])
Definition at line 38 of file utils_v1.py.
Referenced by generator.agents.EndToEndAgent.batchify(), controllable_seq2seq.controllable_seq2seq.ControllableSeq2seqAgent.batchify(), parlai.agents.legacy_agents.seq2seq.torch_agent_v1.TorchAgent.batchify(), parlai.core.torch_agent.TorchAgent.batchify(), parlai.core.torch_ranker_agent.TorchRankerAgent.block_repeats(), parlai.agents.fairseq.fairseq.FairseqAgent.eval_step(), parlai.core.torch_generator_agent.TorchGeneratorAgent.eval_step(), self_feeding.self_feeding_agent.SelfFeedingAgent.load(), self_feeding.self_feeding_agent.SelfFeedingAgent.predict_satisfaction_by_uncertainty(), tests.test_utils.TestUtils.test_padded_tensor(), parlai.agents.legacy_agents.seq2seq.seq2seq_v1.Seq2seqAgent.train_step(), and controllable_seq2seq.controllable_seq2seq.ControllableSeq2seqAgent.train_step().
set_namedtuple_defaults()
def parlai.agents.legacy_agents.seq2seq.utils_v1.set_namedtuple_defaults (namedtuple, default = None)
Set *all* of the fields for a given nametuple to a singular value.
Modifies the tuple in place, but returns it anyway.
More info:
https://stackoverflow.com/a/18348004
:param namedtuple: A constructed collections.namedtuple
:param default: The default value to set.
:returns: the modified namedtuple
Definition at line 21 of file utils_v1.py.
Referenced by tests.test_utils.TestUtils.test_setnamedtupledefaults().
Variable Documentation
NEAR_INF
int parlai.agents.legacy_agents.seq2seq.utils_v1.NEAR_INF = 1e20
Definition at line 18 of file utils_v1.py.