ParlAI: parlai.agents.legacy_agents.seq2seq.dict_v0 Namespace Reference
parlai.agents.legacy_agents.seq2seq.dict_v0 Namespace Reference
Classes
class _BPEHelper
class DictionaryAgent
Functions
def escape (s)
def unescape (s)
def find_ngrams (token_dict, text, n)
Variables
bool BPE_INSTALLED = True
RETOK = re.compile(r'\w+|[^\w\s]|\n', re.UNICODE)
Function Documentation
escape()
def parlai.agents.legacy_agents.seq2seq.dict_v0.escape (s)
Replace potential special characters with escaped version.
For example, \n => \\n and \t => \\t
:param s: string to escape
Definition at line 30 of file dict_v0.py.
Referenced by parlai.agents.legacy_agents.seq2seq.dict_v0.DictionaryAgent.save().
find_ngrams()
def parlai.agents.legacy_agents.seq2seq.dict_v0.find_ngrams (token_dict, text, n)
Break text into ngrams that appear in ``token_dict``.
:param token_dict: ``dict`` to check for ngrams
:param text: ``str`` to look for ngrams in
:param n: ``int`` max size of ngrams
Definition at line 50 of file dict_v0.py.
Referenced by tests.test_dict.TestDictionary.test_find_ngrams(), and parlai.agents.legacy_agents.seq2seq.dict_v0.DictionaryAgent.tokenize().
unescape()
def parlai.agents.legacy_agents.seq2seq.dict_v0.unescape (s)
Revert escaped characters back to their special version.
For example, \\n => \n and \\t => \t
:param s: string to unescape
Definition at line 40 of file dict_v0.py.
Referenced by parlai.agents.legacy_agents.seq2seq.dict_v0.DictionaryAgent.load().
Variable Documentation
BPE_INSTALLED
bool parlai.agents.legacy_agents.seq2seq.dict_v0.BPE_INSTALLED = True
Definition at line 23 of file dict_v0.py.
RETOK
parlai.agents.legacy_agents.seq2seq.dict_v0.RETOK = re.compile(r'\w+|[^\w\s]|\n', re.UNICODE)
Definition at line 27 of file dict_v0.py.