ParlAI: parlai.scripts.train_model Namespace Reference
parlai.scripts.train_model Namespace Reference
Classes
class TrainLoop
Functions
def setup_args (parser=None)
def load_eval_worlds (agent, opt, datatype)
def run_eval (valid_worlds, opt, datatype, max_exs=-1, write_log=False)
Function Documentation
load_eval_worlds()
def parlai.scripts.train_model.load_eval_worlds (agent, opt, datatype)
Create a new eval world for the agent and the given opt.
Overrides the datatype options for doing this.  Handles some magic
overrides of other special options for the training script.
:param Agent agent:
    The model being trained.
:param Opt opt:
    The global CLI opts.
:param string datatype:
    The new datatype.
Definition at line 206 of file train_model.py.
References parlai.core.agents.create_agent_from_shared(), parlai.core.worlds.create_task(), and make_control_dataset.float.
Referenced by parlai.scripts.train_model.setup_args().
run_eval()
def parlai.scripts.train_model.run_eval (valid_worlds, opt, datatype, max_exs = -1, write_log = False)
Eval on validation/test data.
:param valid_world:
    list of the pre-created validation worlds.
:param opt:
    the options that specific the task, eval_task, etc
:param datatype:
    the datatype to use, such as "valid" or "test"
:param bool write_log:
    specifies to write metrics to file if the model_file is set
:param int max_exs:
    limits the number of examples if max_exs > 0
Definition at line 274 of file train_model.py.
References parlai.core.metrics.aggregate_task_reports(), and generate_task_READMEs.str.
Referenced by parlai.scripts.train_model.TrainLoop.train(), and parlai.scripts.train_model.TrainLoop.validate().
setup_args()
def parlai.scripts.train_model.setup_args (parser = None, ParlaiParser)
Build the ParlAI parser, adding command line args if necessary.
:param ParlaiParser parser:
    Preexisting parser to append options to. Will be created if needed.
:returns:
    the ParlaiParser with CLI options added.
Definition at line 51 of file train_model.py.
References parlai.utils.distributed.is_primary_worker(), and parlai.scripts.train_model.load_eval_worlds().
Referenced by parlai.scripts.train_model.TrainLoop.train().