ParlAI: parlai.core.pytorch_data_teacher Namespace Reference
parlai.core.pytorch_data_teacher Namespace Reference
Classes
class BatchSortCache
class DefaultTeacher
class LoaderProcess
class ParlAIConcatDataset
class ParlAIDataset
class PytorchDataTeacher
class StreamDataset
Functions
def ep_length (val)
def get_dataset_classes (opt)
def default_collate (batch)
def deserialize (obj)
def process (ex_or_batch)
Variables
list TORCH_DTYPES
dictionary STR_TO_TORCH_DTYPE = {str(d): d for d in TORCH_DTYPES}
Function Documentation
default_collate()
def parlai.core.pytorch_data_teacher.default_collate (batch)
Collate a batch.
Default collate function, used for ParlAIDataset and StreamDataset.
Definition at line 431 of file pytorch_data_teacher.py.
References parlai.agents.tfidf_retriever.build_tfidf.type.
deserialize()
def parlai.core.pytorch_data_teacher.deserialize (obj)
Deserializes lists into Tensors.
Definition at line 448 of file pytorch_data_teacher.py.
References parlai.agents.tfidf_retriever.build_tfidf.type.
Referenced by parlai.core.pytorch_data_teacher.process().
ep_length()
def parlai.core.pytorch_data_teacher.ep_length (val)
Determine the length of an episode, given the specified value.
Definition at line 281 of file pytorch_data_teacher.py.
Referenced by parlai.core.pytorch_data_teacher.BatchSortCache.batch_cache(), and tests.test_pytorch_data_teacher.TestPytorchDataTeacher.test_pyt_batchsort_field().
get_dataset_classes()
def parlai.core.pytorch_data_teacher.get_dataset_classes (opt)
Get datasets from the options.
To use a custom dataset (as opposed to the StreamDataset or ParlAIDataset),
you can subclass the pytorch Dataset class and specify its location on the
command line.
For example, the VQA v1 task provides a custom dataset, which can
be specified on the command line as follows: ``-pytd vqa_v1:VQADataset``
Note that if the dataset is named ``DefaultDataset``, then you do
not need to specify its name following the colon; e.g., it
would just be: ``-pytd vqa_v1``
Definition at line 295 of file pytorch_data_teacher.py.
References parlai.messenger.core.shared_utils.format, and parlai.core.agents.get_agent_module().
Referenced by parlai.core.pytorch_data_teacher.LoaderProcess.__init__(), and parlai.core.params.ParlaiParser.add_pyt_dataset_args().
process()
def parlai.core.pytorch_data_teacher.process (ex_or_batch)
Process examples/batches, i.e. deserialize if necessary.
Definition at line 460 of file pytorch_data_teacher.py.
References parlai.core.pytorch_data_teacher.deserialize(), and parlai.agents.tfidf_retriever.build_tfidf.type.
Referenced by parlai.core.pytorch_data_teacher.PytorchDataTeacher.next_batch(), and parlai.core.pytorch_data_teacher.PytorchDataTeacher.next_example().
Variable Documentation
STR_TO_TORCH_DTYPE
dictionary parlai.core.pytorch_data_teacher.STR_TO_TORCH_DTYPE = {str(d): d for d in TORCH_DTYPES}
Definition at line 428 of file pytorch_data_teacher.py.
TORCH_DTYPES
list parlai.core.pytorch_data_teacher.TORCH_DTYPES
Initial value:
 =  [
     torch.float32,
     torch.float64,
     torch.float16,
     torch.uint8,
     torch.int8,
     torch.int16,
     torch.int32,
     torch.int64,
 ]
Definition at line 418 of file pytorch_data_teacher.py.