ParlAI: parlai.messenger.core.run Namespace Reference
parlai.messenger.core.run Namespace Reference
Functions
def setup_args ()
def run (opt)
Variables
def opt = setup_args()
def config_path = opt.get('config_path')
config = utils.parse_configuration_file(config_path)
Function Documentation
run()
def parlai.messenger.core.run.run (opt)
Run MessengerManager.
Definition at line 21 of file run.py.
setup_args()
def parlai.messenger.core.run.setup_args ()
Set up args.
Definition at line 13 of file run.py.
Referenced by test_wizard_of_wikipedia.TestWoW.run_display_test(), parlai.scripts.interactive_web.setup_interactive(), tests.test_eval_model.TestEvalModel.test_metrics_all(), tests.test_eval_model.TestEvalModel.test_metrics_select(), tests.test_eval_model.TestEvalModel.test_output(), and test_new_tasks.TestNewTasks.test_verify_data().
Variable Documentation
config
parlai.messenger.core.run.config = utils.parse_configuration_file(config_path)
Definition at line 35 of file run.py.
config_path
def parlai.messenger.core.run.config_path = opt.get('config_path')
Definition at line 34 of file run.py.
opt
def parlai.messenger.core.run.opt = setup_args()
Definition at line 33 of file run.py.