ParlAI: run Namespace Reference
run Namespace Reference
Functions
def setup_retriever (opt)
def setup_title_to_passage (opt)
def setup_personas_with_wiki_links (opt)
def main ()
Function Documentation
main()
def run.main ()
    Wizard of Wikipedia Data Collection Task.
    The task involves two people holding a conversation. One dialog partner
    chooses a topic to discuss, and then dialog proceeds.
    One partner is the Wizard, who has access to retrieved external
    information conditioned on the last two utterances, as well as
    information regarding the chosen topic.
    The other partner is the Apprentice, who assumes the role of someone
    eager to learn about the chosen topic.
This task consists of one agent, model or MTurk worker, talking to an
MTurk worker to negotiate a deal.
Definition at line 90 of file run.py.
References parlai.messenger.core.shared_utils.format, setup_personas_with_wiki_links(), setup_retriever(), and setup_title_to_passage().
setup_personas_with_wiki_links()
def run.setup_personas_with_wiki_links (opt)
Definition at line 82 of file run.py.
References parlai.messenger.core.shared_utils.format.
Referenced by main().
setup_retriever()
def run.setup_retriever (opt)
Definition at line 25 of file run.py.
References parlai.core.agents.create_agent().
Referenced by main().
setup_title_to_passage()
def run.setup_title_to_passage (opt)
Definition at line 37 of file run.py.
References parlai.core.agents.create_task_agent_from_taskname(), and parlai.messenger.core.shared_utils.format.
Referenced by main().