ParlAI: parlai.tasks.talkthewalk.worlds Namespace Reference
parlai.tasks.talkthewalk.worlds Namespace Reference
Classes
class GoldstandardFeatures
class Map
class SimulateWorld
class Simulator
Functions
def is_action (msg, forward=False)
Variables
dictionary BOUNDARIES
Function Documentation
is_action()
def parlai.tasks.talkthewalk.worlds.is_action (msg, forward = False)
Definition at line 21 of file worlds.py.
Referenced by parlai.tasks.talkthewalk.worlds.Simulator.add_view_to_text(), parlai.tasks.talkthewalk.worlds.Simulator.execute(), and parlai.tasks.talkthewalk.worlds.SimulateWorld.parley().
Variable Documentation
BOUNDARIES
dictionary parlai.tasks.talkthewalk.worlds.BOUNDARIES
Initial value:
 =  {
     'hellskitchen': [3, 3],
     'williamsburg': [2, 8],
     'uppereast': [3, 3],
     'fidi': [2, 3],
     'eastvillage': [3, 4],
 }
Definition at line 12 of file worlds.py.