ParlAI: parlai.tasks.personality_captions.download_images Namespace Reference
parlai.tasks.personality_captions.download_images Namespace Reference
Functions
def download_images (opt, task='personality_captions')
Variables
parser = ParlaiParser()
Function Documentation
download_images()
def parlai.tasks.personality_captions.download_images.download_images (opt, task = 'personality_captions')
Definition at line 14 of file download_images.py.
References parlai.core.build_data.download(), parlai.messenger.core.shared_utils.format, and parlai.mturk.core.dev.test.test_full_system.input.
Referenced by parlai.tasks.image_chat.build.build(), and parlai.tasks.personality_captions.build.build().
Variable Documentation
parser
parlai.tasks.personality_captions.download_images.parser = ParlaiParser()
Definition at line 61 of file download_images.py.