ParlAI: parlai.utils.misc Namespace Reference
parlai.utils.misc Namespace Reference
Classes
class AttrDict
class NoLock
class Opt
class PaddingUtils
class Predictor
class TimeLogger
class Timer
Functions
def neginf (dtype)
def maintain_dialog_history (history, observation, reply='', historyLength=1, useReplies='label_else_model', dict=None, useStartEndIndices=True, splitSentences=False)
def load_cands (path, lines_have_ids=False, cands_are_replies=False)
def load_opt_file (optfile)
def round_sigfigs (x, sigfigs=4)
def no_lock ()
def clip_text (text, max_len)
def display_messages (msgs, prettify=False, ignore_fields='', max_len=1000)
def str_to_msg (txt, ignore_fields='')
def msg_to_str (msg, ignore_fields='')
def set_namedtuple_defaults (namedtuple, default=None)
def padded_tensor (items, pad_idx=0, use_cuda=False, left_padded=False, max_len=None, fp16friendly=False)
def padded_3d (tensors, pad_idx=0, use_cuda=0, dtype=TORCH_LONG, fp16friendly=False)
def argsort (keys, lists, descending=False)
def warn_once (msg, warningtype=None)
def fp16_optimizer_wrapper (optimizer, verbose=False, dynamic_loss_scale=True, loss_initial_scale=2.0 **17)
Variables
TORCH_LONG = torch.long
int NEAR_INF = 1e20
int NEAR_INF_FP16 = 65504
dictionary DISPLAY_MESSAGE_DEFAULT_FIELDS
single_nolock = NoLock()
Function Documentation
argsort()
def parlai.utils.misc.argsort (keys, lists, descending = False)
Reorder each list in lists by the (descending) sorted order of keys.
:param iter keys:
    Keys to order by.
:param list[list] lists:
    Lists to reordered by keys's order.  Correctly handles lists and 1-D
    tensors.
:param bool descending:
    Use descending order if true.
:returns:
    The reordered items.
Definition at line 961 of file misc.py.
clip_text()
def parlai.utils.misc.clip_text (text, max_len)
Clip text to max length, adding ellipses.
Definition at line 635 of file misc.py.
References parlai.messenger.core.shared_utils.format, and generate_task_READMEs.str.
Referenced by parlai.utils.misc.display_messages().
display_messages()
def parlai.utils.misc.display_messages (msgs, prettify = False, ignore_fields = '', max_len = 1000)
Return a string describing the set of messages provided.
If prettify is true, candidates are displayed using prettytable.
ignore_fields provides a list of fields in the msgs which should not be
displayed.
Definition at line 667 of file misc.py.
References parlai.utils.misc.clip_text(), parlai.messenger.core.shared_utils.format, generate_task_READMEs.str, and parlai.agents.tfidf_retriever.build_tfidf.type.
Referenced by convai.convai_bot.ConvAISampleAgent.act(), parlai.core.worlds.World.display(), convai.convai_world.ConvAIWorld.display(), convai.convai_bot.ConvAISampleAgent.observe(), and parlai.agents.local_human.local_human.LocalHumanAgent.observe().
fp16_optimizer_wrapper()
def parlai.utils.misc.fp16_optimizer_wrapper (optimizer, verbose = False, dynamic_loss_scale = True, loss_initial_scale = 2.0 ** 17)
Wrap the an optimizer with FP16 loss scaling protection.
Requires apex to be installed. Will throw an ImportError if it is not.
:param optimizer:
    Any torch optimizer
:param bool verbose:
    Enables verbose output in the FP16 optimizer. Turning this on can help
    debug when FP16 is underperforming.
:param bool dynamic_loss_scaling:
    FP16 requires loss scaling to avoid underflows. It is recommended this
    stays on, but advanced users may want it off.
:param float loss_initial_scale:
    Initial loss scaling. Default chosen empirically, but models with very low
    or high loss values may need this adjusted. Stick with powers of 2.
:returns:
    An APEX FP16 optimizer. Please note this has different requirements on
    how backward() and step() are called.
Definition at line 1007 of file misc.py.
Referenced by parlai.agents.bert_ranker.helpers.get_bert_optimizer(), and parlai.utils.misc.warn_once().
load_cands()
def parlai.utils.misc.load_cands (path, lines_have_ids = False, cands_are_replies = False)
Load global fixed set of candidate labels that the teacher provides.
Every example will include these as candidates. The true labels for a
specific example are also added to this set, so that it's possible to get
the right answer.
Definition at line 132 of file misc.py.
load_opt_file()
def parlai.utils.misc.load_opt_file (optfile)
Load an Opt from disk.
Definition at line 170 of file misc.py.
Referenced by parlai.core.agents.compare_init_model_opts(), parlai.core.params.get_model_name(), parlai.core.agents.load_agent_module(), and parlai.core.params.ParlaiParser.parse_known_args().
maintain_dialog_history()
def parlai.utils.misc.maintain_dialog_history (history, observation, reply = '', historyLength = 1, useReplies = 'label_else_model', dict = None, useStartEndIndices = True, splitSentences = False)
Keep track of dialog history, up to a truncation length.
Either includes replies from the labels, model, or not all using param
'replies'.
DEPRECATED. USE PARLAI.CORE.TORCH_AGENT INSTEAD.
Definition at line 71 of file misc.py.
Referenced by parlai.utils.misc.neginf().
msg_to_str()
def parlai.utils.misc.msg_to_str (msg, ignore_fields = '')
Convert ParlAI message dict to string.
:param msg:
    dict to convert into a string.
:param ignore_fields:
    (default '') comma-separated field names to not include in the string
    even if they're in the msg dict.
Definition at line 769 of file misc.py.
References generate_task_READMEs.str, and parlai.agents.tfidf_retriever.build_tfidf.type.
Referenced by parlai.scripts.convert_data_to_parlai_format.dump_data(), make_control_dataset.make_dataset(), and parlai.tasks.light_dialog.builder.write_dialog().
neginf()
def parlai.utils.misc.neginf (dtype)
Return a representable finite number near -inf for a dtype.
Definition at line 54 of file misc.py.
References parlai.utils.misc.maintain_dialog_history().
Referenced by controllable_seq2seq.controllable_seq2seq.Beam.advance(), generator.modules.ContextKnowledgeEncoder.forward(), parlai.agents.bert_ranker.helpers.BertWrapper.forward(), parlai.agents.memnn.modules.Hop.forward(), and parlai.agents.transformer.modules.MultiHeadAttention.forward().
no_lock()
def parlai.utils.misc.no_lock ()
Build a nolock for other classes to use for no-op locking.
Definition at line 440 of file misc.py.
Referenced by parlai.core.metrics.Metrics.__repr__(), and parlai.core.teachers.StreamDialogData.num_episodes().
padded_3d()
def parlai.utils.misc.padded_3d (tensors, pad_idx = 0, use_cuda = 0, dtype = TORCH_LONG, fp16friendly = False)
Make 3D padded tensor for list of lists of 1D tensors or lists.
:param tensors:
    list of lists of 1D tensors (or lists)
:param pad_idx:
    padding to fill tensor with
:param use_cuda:
    whether to call cuda() before returning
:param bool fp16friendly:
    if True, pads the final dimension to be a multiple of 8.
:returns:
    3D tensor with the maximum dimensions of the inputs
Definition at line 920 of file misc.py.
Referenced by parlai.core.torch_ranker_agent.TorchRankerAgent.block_repeats(), parlai.core.torch_ranker_agent.TorchRankerAgent.load_candidates(), and parlai.agents.transformer.transformer.TransformerRankerAgent.score_candidates().
padded_tensor()
def parlai.utils.misc.padded_tensor (items, pad_idx = 0, use_cuda = False, left_padded = False, max_len = None, fp16friendly = False)
Create a right-padded matrix from an uneven list of lists.
Returns (padded, lengths), where padded is the padded matrix, and lengths
is a list containing the lengths of each row.
Matrix is right-padded (filled to the right) by default, but can be
left padded if the flag is set to True.
Matrix can also be placed on cuda automatically.
:param list[iter[int]] items: List of items
:param bool sort: If True, orders by the length
:param int pad_idx: the value to use for padding
:param bool use_cuda: if true, places `padded` on GPU
:param bool left_padded:
:param int max_len: if None, the max length is the maximum item length
:param bool fp16friendly: if True, pads the time dimension to be a multiple of 8.
:returns: (padded, lengths) tuple
:rtype: (Tensor[int64], list[int])
Definition at line 851 of file misc.py.
Referenced by parlai.utils.misc.set_namedtuple_defaults().
round_sigfigs()
def parlai.utils.misc.round_sigfigs (x, sigfigs = 4)
Round value to specified significant figures.
:param x: input number
:param sigfigs: number of significant figures to return
:returns: float number rounded to specified sigfigs
Definition at line 398 of file misc.py.
References make_control_dataset.float.
set_namedtuple_defaults()
def parlai.utils.misc.set_namedtuple_defaults (namedtuple, default = None)
Set *all* of the fields for a given nametuple to a singular value.
Additionally removes the default docstring for each field.
Modifies the tuple in place, but returns it anyway.
More info:
https://stackoverflow.com/a/18348004
:param namedtuple: A constructed collections.namedtuple
:param default: The default value to set.
:returns: the modified namedtuple
Definition at line 823 of file misc.py.
References parlai.utils.misc.padded_tensor().
str_to_msg()
def parlai.utils.misc.str_to_msg (txt, ignore_fields = '')
Convert formatted string to ParlAI message dict.
:param txt:
    formatted string to convert. String format is tab-separated fields,
    with colon separating field name and contents.
:param ignore_fields:
    (default '') comma-separated field names to not
    include in the msg dict even if they're in the string.
Definition at line 715 of file misc.py.
References mastering_the_dungeon.mturk.tasks.MTD.run.bool, and generate_task_READMEs.str.
Referenced by parlai.core.teachers.ParlAIDialogTeacher.get().
warn_once()
def parlai.utils.misc.warn_once (msg, warningtype = None)
Raise a warning, but only once.
:param str msg: Message to display
:param Warning warningtype: Type of warning, e.g. DeprecationWarning
Definition at line 992 of file misc.py.
References parlai.utils.misc.fp16_optimizer_wrapper().
Referenced by parlai.core.metrics.aggregate_task_reports(), parlai.core.torch_ranker_agent.TorchRankerAgent.block_repeats(), parlai.core.torch_generator_agent.TorchGeneratorAgent.eval_step(), self_feeding.self_feeding_agent.SelfFeedingAgent.feedback_step(), parlai.agents.transformer.modules.TransformerEncoder.forward(), parlai.agents.transformer.modules.TransformerDecoder.forward(), parlai.agents.seq2seq.seq2seq.Seq2seqAgent.is_valid(), parlai.core.torch_ranker_agent.TorchRankerAgent.is_valid(), self_feeding.self_feeding_agent.SelfFeedingAgent.load(), parlai.core.agents.load_agent_module(), parlai.core.torch_agent.TorchAgent.receive_metrics(), parlai.core.torch_agent.TorchAgent.state_dict(), parlai.scripts.train_model.TrainLoop.train(), parlai.core.torch_ranker_agent.TorchRankerAgent.train_step(), parlai.agents.bert_classifier.bert_classifier.BertClassifierAgent.upgrade_opt(), parlai.core.torch_generator_agent.TorchGeneratorAgent.upgrade_opt(), self_feeding.self_feeding_agent.SelfFeedingAgent.upgrade_opt(), and parlai.scripts.verify_data.warn().
Variable Documentation
DISPLAY_MESSAGE_DEFAULT_FIELDS
dictionary parlai.utils.misc.DISPLAY_MESSAGE_DEFAULT_FIELDS
Initial value:
 =  {
     'episode_done',
     'id',
     'image',
     'text',
     'labels',
     'eval_labels',
     'label_candidates',
     'text_candidates',
     'reward',
     'eval_labels_vec',
     'text_vec',
     'label_candidates_vecs',
 }
Definition at line 38 of file misc.py.
NEAR_INF
int parlai.utils.misc.NEAR_INF = 1e20
Definition at line 34 of file misc.py.
NEAR_INF_FP16
int parlai.utils.misc.NEAR_INF_FP16 = 65504
Definition at line 35 of file misc.py.
single_nolock
parlai.utils.misc.single_nolock = NoLock()
Definition at line 437 of file misc.py.
TORCH_LONG
parlai.utils.misc.TORCH_LONG = torch.long
Definition at line 26 of file misc.py.