ParlAI: controllable_seq2seq.util Namespace Reference
controllable_seq2seq.util Namespace Reference
Classes
class ConvAI2History
Functions
def remove_prefix (utt, prefix)
def fix_personaline_period (line)
def show_beam_cands (n_best_beam_preds, history, dictionary)
def reorder_extrep2gram_qn (n_best_beam_preds, history, dictionary, verbose)
Function Documentation
fix_personaline_period()
def controllable_seq2seq.util.fix_personaline_period (line)
Sometimes the tokenized persona lines have a period at the end but no space before
the period. This function fixes it, e.g. changes
  'my favorite color is blue.' to 'my favorite color is blue .'
Definition at line 90 of file util.py.
Referenced by controllable_seq2seq.util.ConvAI2History.__init__().
remove_prefix()
def controllable_seq2seq.util.remove_prefix (utt, prefix)
Check that utt begins with prefix+" ", and then remove.
Inputs:
  utt: string
  prefix: string
Returns:
  new utt: utt with the prefix+" " removed.
Definition at line 69 of file util.py.
Referenced by controllable_seq2seq.util.ConvAI2History.__init__().
reorder_extrep2gram_qn()
def controllable_seq2seq.util.reorder_extrep2gram_qn (n_best_beam_preds, history, dictionary, verbose)
Inputs:
    n_best_beam_preds: list length num_candidates of (prediction, score) pairs.
      prediction is a tensor of word indices, score is a single float tensor.
    history: ConvAI2History
    dictionary: parlai DictionaryAgent
    verbose: bool. If True, print out the selection process.
Outputs: (tensor, tensor) pair which is the chosen (prediction, score)
Definition at line 124 of file util.py.
Referenced by controllable_seq2seq.controllable_seq2seq.ControllableSeq2seqAgent.eval_step().
show_beam_cands()
def controllable_seq2seq.util.show_beam_cands (n_best_beam_preds, history, dictionary)
Pretty-print the n-best candidates from beam search, along with their probabilities
Inputs:
  n_best_beam_preds: list length num_candidates of (prediction, score) pairs.
    prediction is a tensor of word indices, score is a single float tensor.
  history: ConvAI2History
  dictionary: parlai DictionaryAgent
Definition at line 102 of file util.py.
Referenced by controllable_seq2seq.controllable_seq2seq.ControllableSeq2seqAgent.eval_step().