ParlAI: parlai.scripts.multiprocessing_train Namespace Reference
parlai.scripts.multiprocessing_train Namespace Reference
Functions
def multiprocess_train (rank, opt, port=61337, rank_offset=0, gpu=None, hostname='localhost')
def launch_and_train (opt, port)
def setup_args ()
def main ()
Function Documentation
launch_and_train()
def parlai.scripts.multiprocessing_train.launch_and_train (opt, port)
Perform a fork() to many processes.
Definition at line 97 of file multiprocessing_train.py.
References parlai.scripts.multiprocessing_train.multiprocess_train().
Referenced by parlai.scripts.multiprocessing_train.main().
main()
def parlai.scripts.multiprocessing_train.main ()
Definition at line 128 of file multiprocessing_train.py.
References parlai.scripts.multiprocessing_train.launch_and_train(), and parlai.scripts.multiprocessing_train.setup_args().
multiprocess_train()
def parlai.scripts.multiprocessing_train.multiprocess_train (rank, opt, port = 61337, rank_offset = 0, gpu = None, hostname = 'localhost')
Subprocess which initializes distributed training, and begins training.
This should be launched n times for n GPUs; this is handled either in main
or via srun.
:param int rank: This process's rank - 1. (Starts at -1 ... n - 2). See comments.
:param opt: command line options
:param int port: A TCP port to use. This will need to be changed to run
    multiple distributed training setups on the same machine.
:param int gpu: Which GPU to use. Defaults to using rank and local devices,
    but must be manually specified when using many-hosts.
:param str hostname: Hostname of the main server.
Definition at line 38 of file multiprocessing_train.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.scripts.multiprocessing_train.launch_and_train(), and parlai.scripts.distributed_train.main().
setup_args()
def parlai.scripts.multiprocessing_train.setup_args ()
Definition at line 121 of file multiprocessing_train.py.
Referenced by parlai.scripts.multiprocessing_train.main().