ParlAI: convai.convai_bot Namespace Reference
convai.convai_bot Namespace Reference
Classes
class ConvAISampleAgent
Functions
def setup_args ()
def run_convai_bot (opt)
def main ()
Function Documentation
main()
def convai.convai_bot.main ()
Definition at line 70 of file convai_bot.py.
References convai.convai_bot.run_convai_bot(), and convai.convai_bot.setup_args().
run_convai_bot()
def convai.convai_bot.run_convai_bot (opt)
Definition at line 60 of file convai_bot.py.
References parlai.core.agents.create_agent(), and parlai.messenger.core.shared_utils.format.
Referenced by convai.convai_bot.main().
setup_args()
def convai.convai_bot.setup_args ()
Definition at line 54 of file convai_bot.py.
Referenced by convai.convai_bot.main().