ParlAI: parlai.core.metrics Namespace Reference
parlai.core.metrics Namespace Reference
Classes
class Metrics
Functions
def normalize_answer (s)
def aggregate_task_reports (reports, tasks, micro=False)
def aggregate_metrics (reporters)
Variables
dictionary DEFAULT_METRICS = {'correct', 'bleu', 'accuracy', 'f1'}
dictionary ROUGE_METRICS = {'rouge-1', 'rouge-2', 'rouge-L'}
dictionary ALL_METRICS = DEFAULT_METRICS | ROUGE_METRICS
nltkbleu = None
rouge = None
re_art = re.compile(r'\b(a|an|the)\b')
re_punc = re.compile(r'[!"#$%&()*+,-./:;<=>?@\[\]\\^`{|}~_\']')
Function Documentation
aggregate_metrics()
def parlai.core.metrics.aggregate_metrics (reporters)
Aggregate metrics from multiple reports.
Definition at line 191 of file metrics.py.
References convai2.eval_f1.report, and parlai.agents.legacy_agents.seq2seq.utils_v0.round_sigfigs().
Referenced by parlai.core.agents.MultiTaskTeacher.report(), and parlai.core.worlds.MultiWorld.report().
aggregate_task_reports()
def parlai.core.metrics.aggregate_task_reports (reports, tasks, micro = False)
Aggregate separate task reports into a single report.
:param reports: list of report dicts from separate tasks
:param tasks: list of tasks
:param micro: average per example if True, else average over t
:return: aggregated report dicts
Definition at line 62 of file metrics.py.
References parlai.core.metrics.normalize_answer(), parlai.agents.legacy_agents.seq2seq.utils_v0.round_sigfigs(), and parlai.utils.misc.warn_once().
Referenced by parlai.scripts.eval_model.eval_model(), and parlai.scripts.train_model.run_eval().
normalize_answer()
def parlai.core.metrics.normalize_answer (s)
Lower text and remove punctuation, articles and extra whitespace.
Definition at line 44 of file metrics.py.
Referenced by parlai.core.metrics.Metrics.__repr__(), parlai.core.metrics.aggregate_task_reports(), parlai.scripts.eval_wordstat.eval_wordstat(), and eval_wordstat.eval_wordstat().
Variable Documentation
ALL_METRICS
dictionary parlai.core.metrics.ALL_METRICS = DEFAULT_METRICS | ROUGE_METRICS
Definition at line 23 of file metrics.py.
DEFAULT_METRICS
dictionary parlai.core.metrics.DEFAULT_METRICS = {'correct', 'bleu', 'accuracy', 'f1'}
Definition at line 21 of file metrics.py.
nltkbleu
parlai.core.metrics.nltkbleu = None
Definition at line 31 of file metrics.py.
re_art
parlai.core.metrics.re_art = re.compile(r'\b(a|an|the)\b')
Definition at line 40 of file metrics.py.
re_punc
parlai.core.metrics.re_punc = re.compile(r'[!"#$%&()*+,-./:;<=>?@\[\]\\^`{|}~_\']')
Definition at line 41 of file metrics.py.
rouge
parlai.core.metrics.rouge = None
Definition at line 38 of file metrics.py.
ROUGE_METRICS
dictionary parlai.core.metrics.ROUGE_METRICS = {'rouge-1', 'rouge-2', 'rouge-L'}
Definition at line 22 of file metrics.py.