ParlAI: get_bucket_lowerbounds Namespace Reference
get_bucket_lowerbounds Namespace Reference
Functions
def bucket_data (opt)
def main ()
Function Documentation
bucket_data()
def get_bucket_lowerbounds.bucket_data (opt)
Definition at line 21 of file get_bucket_lowerbounds.py.
References parlai.core.worlds.create_task(), make_control_dataset.float, and eval_ppl.int.
Referenced by main().
main()
def get_bucket_lowerbounds.main ()
Definition at line 107 of file get_bucket_lowerbounds.py.
References bucket_data().