ParlAI: controllable_seq2seq.arora Namespace Reference
controllable_seq2seq.arora Namespace Reference
Classes
class SentenceEmbedder
Functions
def remove_first_sv (emb, first_sv)
def get_word_counts (opt, count_inputs)
def learn_arora (opt)
def load_arora (opt)
Variables
string CONTROLLABLE_DIR = 'controllable_dialogue'
parser = ParlaiParser()
opt = parser.parse_args()
Function Documentation
get_word_counts()
def controllable_seq2seq.arora.get_word_counts (opt, count_inputs)
Goes through the dataset specified in opt, returns word counts and all utterances
Inputs:
  count_inputs: If True, include both input and reply when counting words and
    utterances. Otherwise, only include reply text.
Returns:
  word_counter: a Counter mapping each word to the total number of times it appears
  total_count: int. total word count, i.e. the sum of the counts for each word
  all_utts: list of strings. all the utterances that were used for counting words
Definition at line 241 of file arora.py.
References parlai.core.worlds.create_task().
Referenced by controllable_seq2seq.arora.learn_arora().
learn_arora()
def controllable_seq2seq.arora.learn_arora (opt)
Go through ConvAI2 data and collect word counts, thus compute the unigram
probability distribution. Use those probs to compute weighted sentence embeddings
for all utterances, thus compute first principal component.
Save all info to arora.pkl file.
Definition at line 294 of file arora.py.
References controllable_seq2seq.arora.get_word_counts(), parlai.agents.legacy_agents.seq2seq.utils_v0.modelzoo_path(), and controllable_seq2seq.arora.remove_first_sv().
load_arora()
def controllable_seq2seq.arora.load_arora (opt)
Load the data in the arora.pkl file in data/controllable_dialogue.
Definition at line 400 of file arora.py.
Referenced by controllable_seq2seq.controls.initialize_control_information().
remove_first_sv()
def controllable_seq2seq.arora.remove_first_sv (emb, first_sv)
Projects out the first singular value (first_sv) from the embedding (emb).
Inputs:
  emb: torch Tensor shape (glove_dim)
  first_sv: torch Tensor shape (glove_dim)
Returns:
  new emb: torch Tensor shape (glove_dim)
Definition at line 224 of file arora.py.
Referenced by controllable_seq2seq.arora.SentenceEmbedder.embed_sent(), and controllable_seq2seq.arora.learn_arora().
Variable Documentation
CONTROLLABLE_DIR
string controllable_seq2seq.arora.CONTROLLABLE_DIR = 'controllable_dialogue'
Definition at line 24 of file arora.py.
opt
controllable_seq2seq.arora.opt = parser.parse_args()
Definition at line 414 of file arora.py.
parser
controllable_seq2seq.arora.parser = ParlaiParser()
Definition at line 413 of file arora.py.