ParlAI: parlai.agents.bert_ranker.helpers Namespace Reference
parlai.agents.bert_ranker.helpers Namespace Reference
Classes
class AdamWithDecay
class BertWrapper
Functions
def add_common_args (parser)
def surround (idx_vector, start_idx, end_idx)
def get_bert_optimizer (models, type_optimization, learning_rate, fp16=False)
Variables
string MODEL_PATH = 'bert-base-uncased.tar.gz'
string VOCAB_PATH = 'bert-base-uncased-vocab.txt'
dictionary patterns_optimizer
Function Documentation
add_common_args()
def parlai.agents.bert_ranker.helpers.add_common_args (parser)
Add command line arguments for this agent.
Definition at line 32 of file helpers.py.
Referenced by parlai.agents.bert_ranker.both_encoder_ranker.BothEncoderRankerAgent.add_cmdline_args(), parlai.agents.bert_ranker.bi_encoder_ranker.BiEncoderRankerAgent.add_cmdline_args(), and parlai.agents.bert_ranker.cross_encoder_ranker.CrossEncoderRankerAgent.add_cmdline_args().
get_bert_optimizer()
def parlai.agents.bert_ranker.helpers.get_bert_optimizer (models, type_optimization, learning_rate, fp16 = False)
Optimizes the network with AdamWithDecay.
Definition at line 195 of file helpers.py.
References parlai.utils.misc.fp16_optimizer_wrapper(), and generate_task_READMEs.str.
surround()
def parlai.agents.bert_ranker.helpers.surround (idx_vector, start_idx, end_idx)
Surround the vector by start_idx and end_idx.
Definition at line 173 of file helpers.py.
Referenced by parlai.agents.bert_ranker.cross_encoder_ranker.CrossEncoderRankerAgent.dictionary_class(), and parlai.agents.bert_ranker.bi_encoder_ranker.BiEncoderRankerAgent.encode_candidates().
Variable Documentation
MODEL_PATH
string parlai.agents.bert_ranker.helpers.MODEL_PATH = 'bert-base-uncased.tar.gz'
Definition at line 28 of file helpers.py.
patterns_optimizer
dictionary parlai.agents.bert_ranker.helpers.patterns_optimizer
Initial value:
 =  {
     'additional_layers': ['additional'],
     'top_layer': ['additional', 'bert_model.encoder.layer.11.'],
     'top4_layers': [
         'additional',
         'bert_model.encoder.layer.11.',
         'encoder.layer.10.',
         'encoder.layer.9.',
         'encoder.layer.8',
     ],
     'all_encoder_layers': ['additional', 'bert_model.encoder.layer'],
     'all': ['additional', 'bert_model.encoder.layer', 'bert_model.embeddings'],
 }
Definition at line 180 of file helpers.py.
VOCAB_PATH
string parlai.agents.bert_ranker.helpers.VOCAB_PATH = 'bert-base-uncased-vocab.txt'
Definition at line 29 of file helpers.py.