ParlAI: parlai.tasks.twitter.build Namespace Reference
parlai.tasks.twitter.build Namespace Reference
Functions
def replace_emoji (x)
def split_punctuation (x)
def create_fb_format (data, dpath)
def build (opt)
Function Documentation
build()
def parlai.tasks.twitter.build.build (opt)
Definition at line 72 of file build.py.
References parlai.tasks.twitter.build.create_fb_format().
create_fb_format()
def parlai.tasks.twitter.build.create_fb_format (data, dpath)
Definition at line 40 of file build.py.
References parlai.messenger.core.shared_utils.format, and parlai.tasks.twitter.build.split_punctuation().
Referenced by parlai.tasks.twitter.build.build().
replace_emoji()
def parlai.tasks.twitter.build.replace_emoji (x)
Definition at line 18 of file build.py.
split_punctuation()
def parlai.tasks.twitter.build.split_punctuation (x)
Definition at line 25 of file build.py.
Referenced by parlai.tasks.twitter.build.create_fb_format().