ParlAI: controllable_seq2seq.controls Namespace Reference
controllable_seq2seq.controls Namespace Reference
Classes
class NIDFFeats
Functions
def initialize_control_information (opt, build_task=True)
def flatten (list_of_lists)
def intrep_frac (lst)
def extrep_frac (lst1, lst2)
def get_ngrams (text, n)
def matching_ngram_completions (comparison_seq, hypothesis, n)
def intrep_word_used_before (dict, hypothesis, history, wt, feat, remove_stopwords)
def intrep_ngram_used_before (dict, hypothesis, history, wt, feat, n)
def extrep_word_used_before (dict, hypothesis, history, wt, feat, remove_stopwords, person)
def extrep_ngram_used_before (dict, hypothesis, history, wt, feat, n, person)
def nidf (dict, hypothesis, history, wt, feat)
def qn_words (dict, hypothesis, history, wt, feat)
def lastutt_sim_arora_word (dict, hypothesis, history, wt, feat)
Variables
list QN_WORDS = ['who', 'what', 'where', 'why', 'when', 'how', 'which', 'whom', 'whose', '?']
word2nidf = None
nidf_feats = None
arora_data = None
sent_embedder = None
Function Documentation
extrep_frac()
def controllable_seq2seq.controls.extrep_frac (lst1, lst2)
Returns the fraction of items in lst1 that are in lst2
Definition at line 132 of file controls.py.
Referenced by controllable_seq2seq.controls.lastutt_sim_arora_word().
extrep_ngram_used_before()
def controllable_seq2seq.controls.extrep_ngram_used_before (dict, hypothesis, history, wt, feat, n, person)
Weighted decoding feature function. See explanation above.
This feature is 1 for words that, if added to hypothesis, would create a n-gram that
has already been used earlier in the conversation; otherwise 0.
Additional inputs:
  n: int, the size of the n-grams considered.
  person: If 'self', identify n-grams that have already been used by self (bot).
    If 'partner', identify n-grams that have already been used by partner (human).
Definition at line 270 of file controls.py.
References controllable_seq2seq.controls.flatten(), and controllable_seq2seq.controls.matching_ngram_completions().
Referenced by controllable_seq2seq.controls.lastutt_sim_arora_word().
extrep_word_used_before()
def controllable_seq2seq.controls.extrep_word_used_before (dict, hypothesis, history, wt, feat, remove_stopwords, person)
Weighted decoding feature function. See explanation above.
This feature is 1 for words that have already been used earlier in the conversation;
otherwise 0.
Additional inputs:
  remove_stopwords: bool. If True, stopwords are not included when identifying words
    that have already appeared.
  person: If 'self', identify words that have already been used by self (bot).
    If 'partner', identify words that have already been used by partner (human).
Definition at line 241 of file controls.py.
References controllable_seq2seq.controls.flatten().
Referenced by controllable_seq2seq.controls.intrep_ngram_used_before(), and controllable_seq2seq.controls.lastutt_sim_arora_word().
flatten()
def controllable_seq2seq.controls.flatten (list_of_lists)
Flatten a list of lists
Definition at line 116 of file controls.py.
Referenced by parlai.core.pytorch_data_teacher.BatchSortCache.batch_cache(), controllable_seq2seq.controls.extrep_ngram_used_before(), controllable_seq2seq.controls.extrep_word_used_before(), controllable_seq2seq.controls.lastutt_sim_arora_word(), and mastering_the_dungeon.mturk.tasks.MTD.run.overall_split().
get_ngrams()
def controllable_seq2seq.controls.get_ngrams (text, n)
Returns all ngrams that are in the text.
Inputs:
    text: string
    n: int
Returns:
    list of strings (each is a ngram)
Definition at line 140 of file controls.py.
Referenced by controllable_seq2seq.controls.lastutt_sim_arora_word().
initialize_control_information()
def controllable_seq2seq.controls.initialize_control_information (opt, build_task = True)
Loads information from word2count.pkl, arora.pkl in data/controllable_dialogue, and
uses it to initialize objects for computing NIDF and response-relatedness controls.
By default (build_task=True) we will also build the controllable_dialogue task i.e.
download data/controllable_dialogue if necessary.
Definition at line 79 of file controls.py.
References controllable_seq2seq.arora.load_arora(), controllable_seq2seq.nidf.load_word2nidf(), and parlai.agents.legacy_agents.seq2seq.utils_v0.modelzoo_path().
Referenced by controllable_seq2seq.controllable_seq2seq.ControllableSeq2seqAgent.__init__(), eval_wordstat.eval_wordstat(), and make_control_dataset.make_dataset().
intrep_frac()
def controllable_seq2seq.controls.intrep_frac (lst)
Returns the fraction of items in the list that are repeated
Definition at line 121 of file controls.py.
Referenced by controllable_seq2seq.controls.lastutt_sim_arora_word().
intrep_ngram_used_before()
def controllable_seq2seq.controls.intrep_ngram_used_before (dict, hypothesis, history, wt, feat, n)
Weighted decoding feature function. See explanation above.
This feature is 1 for words that, if added to the hypothesis, will create a n-gram
that has already appeared in the hypothesis; otherwise 0.
Additional inputs:
  n: int, the size of the n-grams considered.
Definition at line 223 of file controls.py.
References controllable_seq2seq.controls.extrep_word_used_before(), and controllable_seq2seq.controls.matching_ngram_completions().
Referenced by controllable_seq2seq.controls.lastutt_sim_arora_word().
intrep_word_used_before()
def controllable_seq2seq.controls.intrep_word_used_before (dict, hypothesis, history, wt, feat, remove_stopwords)
Weighted decoding feature function. See explanation above.
This feature is 1 for words that have already appeared within the hypothesis,
0 otherwise.
Additional inputs:
  remove_stopwords: bool. If True, stopwords are not included when identifying words
    that have already appeared.
Definition at line 205 of file controls.py.
Referenced by controllable_seq2seq.controls.lastutt_sim_arora_word().
lastutt_sim_arora_word()
def controllable_seq2seq.controls.lastutt_sim_arora_word (dict, hypothesis, history, wt, feat)
Weighted decoding feature function. See explanation above.
Given a word w, this feature is equal to
  cos_sim(word_emb(w), sent_emb(l))
the cosine similarity between the GloVe vector for word w, and the Arora-style
sentence embedding for the partner's last utterance l.
Definition at line 322 of file controls.py.
References mastering_the_dungeon.mturk.tasks.MTD.run.bool, controllable_seq2seq.controls.extrep_frac(), controllable_seq2seq.controls.extrep_ngram_used_before(), controllable_seq2seq.controls.extrep_word_used_before(), controllable_seq2seq.controls.flatten(), make_control_dataset.float, controllable_seq2seq.controls.get_ngrams(), eval_ppl.int, controllable_seq2seq.controls.intrep_frac(), controllable_seq2seq.controls.intrep_ngram_used_before(), controllable_seq2seq.controls.intrep_word_used_before(), controllable_seq2seq.controls.nidf(), controllable_seq2seq.controls.qn_words(), and generate_task_READMEs.str.
matching_ngram_completions()
def controllable_seq2seq.controls.matching_ngram_completions (comparison_seq, hypothesis, n)
Return the list of words that if appended to hypothesis, would create a n-gram that
already exists in comparison_seq. For efficiency, this function represents words
as integers not strings.
Inputs:
    comparison_seq: list of integers
    hypothesis: list of integers or None
    n: integer
Output:
    bad_words: list of integers
Definition at line 154 of file controls.py.
References eval_ppl.int.
Referenced by controllable_seq2seq.controls.extrep_ngram_used_before(), and controllable_seq2seq.controls.intrep_ngram_used_before().
nidf()
def controllable_seq2seq.controls.nidf (dict, hypothesis, history, wt, feat)
Weighted decoding feature function. See explanation above.
This feature is equal to the NIDF (normalized inverse document frequency) score for
each word. The score is always between 0 and 1.
Definition at line 302 of file controls.py.
Referenced by controllable_seq2seq.controls.lastutt_sim_arora_word().
qn_words()
def controllable_seq2seq.controls.qn_words (dict, hypothesis, history, wt, feat)
Weighted decoding feature function. See explanation above.
This feature is 1 for 'interrogative words', 0 otherwise.
Definition at line 312 of file controls.py.
Referenced by controllable_seq2seq.controls.lastutt_sim_arora_word().
Variable Documentation
arora_data
controllable_seq2seq.controls.arora_data = None
Definition at line 75 of file controls.py.
nidf_feats
controllable_seq2seq.controls.nidf_feats = None
Definition at line 74 of file controls.py.
QN_WORDS
list controllable_seq2seq.controls.QN_WORDS = ['who', 'what', 'where', 'why', 'when', 'how', 'which', 'whom', 'whose', '?']
Definition at line 22 of file controls.py.
sent_embedder
controllable_seq2seq.controls.sent_embedder = None
Definition at line 76 of file controls.py.
word2nidf
controllable_seq2seq.controls.word2nidf = None
Definition at line 73 of file controls.py.