ParlAI: parlai.agents.ir_baseline.ir_baseline Namespace Reference
parlai.agents.ir_baseline.ir_baseline Namespace Reference
Classes
class IrBaselineAgent
class MaxPriorityQueue
Functions
def score_match (query_rep, text, length_penalty, dictionary=None, debug=False)
def rank_candidates (query_rep, cands, length_penalty, dictionary=None)
Variables
dictionary stopwords
Function Documentation
rank_candidates()
def parlai.agents.ir_baseline.ir_baseline.rank_candidates (query_rep, cands, length_penalty, dictionary = None)
Rank candidates given representation of query.
:param query_rep: base query representation to match text again.
:param cands: strings to compare against query_rep for matching tokens
:param length_penalty: scores are divided by the norm taken to this power
:dictionary: optional dictionary to use to tokenize text
:returns: ordered list of candidate strings in score-ranked order
Definition at line 183 of file ir_baseline.py.
References parlai.agents.ir_baseline.ir_baseline.score_match().
Referenced by parlai.agents.ir_baseline.ir_baseline.IrBaselineAgent.act().
score_match()
def parlai.agents.ir_baseline.ir_baseline.score_match (query_rep, text, length_penalty, dictionary = None, debug = False)
Calculate the score match between the query representation the text.
:param query_rep: base query representation to match text again.
:param text: string to comapre against query_rep for matching tokens
:param length_penalty: scores are divided by the norm taken to this power
:dictionary: optional dictionary to use to tokenize text
:debug: flag to enable printing every match
:returns: float score of match
Definition at line 150 of file ir_baseline.py.
Referenced by parlai.agents.ir_baseline.ir_baseline.rank_candidates().
Variable Documentation
stopwords
dictionary parlai.agents.ir_baseline.ir_baseline.stopwords
Definition at line 83 of file ir_baseline.py.