ParlAI: interactive Namespace Reference
interactive Namespace Reference
Classes
class MyHandler
Functions
def setup_interactive ()
Variables
parser = setup_args()
opt = parser.parse_args()
print_parser
batchsize
beam_size
beam_min_n_best
type
default
model
model_file
interactive_mode
list fnames = ['kvmemnn.tgz']
dict_file
dict_lower
version
string HOST_NAME = "0.0.0.0"
int PORT = 8082
dictionary SHARED = {}
IMAGE_LOADER = None
string STYLE_SHEET = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.css"
string FONT_AWESOME = "https://use.fontawesome.com/releases/v5.3.1/js/all.js"
string WEB_HTML
server_class = HTTPServer
Handler = MyHandler
protocol_version
httpd = server_class((HOST_NAME, PORT), Handler)
Function Documentation
setup_interactive()
def interactive.setup_interactive ()
Set up the interactive script.
Definition at line 292 of file interactive.py.
References parlai.core.agents.create_agent(), parlai.core.worlds.create_task(), and self_feeding.interactive.setup_args().
Referenced by interactive.MyHandler.respond().
Variable Documentation
batchsize
interactive.batchsize
Definition at line 15 of file interactive.py.
beam_min_n_best
interactive.beam_min_n_best
Definition at line 15 of file interactive.py.
beam_size
interactive.beam_size
Definition at line 15 of file interactive.py.
default
interactive.default
Definition at line 17 of file interactive.py.
dict_file
interactive.dict_file
Definition at line 19 of file interactive.py.
dict_lower
interactive.dict_lower
Definition at line 20 of file interactive.py.
fnames
list interactive.fnames = ['kvmemnn.tgz']
Definition at line 25 of file interactive.py.
FONT_AWESOME
string interactive.FONT_AWESOME = "https://use.fontawesome.com/releases/v5.3.1/js/all.js"
Definition at line 27 of file interactive.py.
Handler
interactive.Handler = MyHandler
Definition at line 322 of file interactive.py.
HOST_NAME
string interactive.HOST_NAME = "0.0.0.0"
Definition at line 22 of file interactive.py.
httpd
interactive.httpd = server_class((HOST_NAME, PORT), Handler)
Definition at line 324 of file interactive.py.
IMAGE_LOADER
interactive.IMAGE_LOADER = None
Definition at line 25 of file interactive.py.
interactive_mode
interactive.interactive_mode
Definition at line 21 of file interactive.py.
model
interactive.model
Definition at line 19 of file interactive.py.
model_file
interactive.model_file
Definition at line 20 of file interactive.py.
opt
interactive.opt = parser.parse_args()
Definition at line 17 of file interactive.py.
parser
interactive.parser = setup_args()
Definition at line 16 of file interactive.py.
PORT
int interactive.PORT = 8082
Definition at line 23 of file interactive.py.
print_parser
interactive.print_parser
Definition at line 18 of file interactive.py.
protocol_version
interactive.protocol_version
Definition at line 323 of file interactive.py.
server_class
interactive.server_class = HTTPServer
Definition at line 321 of file interactive.py.
Referenced by interactive.MyHandler.respond().
SHARED
dictionary interactive.SHARED = {}
Definition at line 24 of file interactive.py.
STYLE_SHEET
string interactive.STYLE_SHEET = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.css"
Definition at line 26 of file interactive.py.
type
interactive.type
Definition at line 17 of file interactive.py.
version
interactive.version
Definition at line 34 of file interactive.py.
WEB_HTML
string interactive.WEB_HTML
Definition at line 28 of file interactive.py.