ParlAI: self_feeding.interactive Namespace Reference
self_feeding.interactive Namespace Reference
Functions
def setup_args (parser=None)
def interactive (opt, print_parser=None)
Variables
def parser = setup_args()
print_parser
Function Documentation
interactive()
def self_feeding.interactive.interactive (opt, print_parser = None)
Definition at line 34 of file interactive.py.
References parlai.core.agents.create_agent(), and parlai.core.worlds.create_task().
setup_args()
def self_feeding.interactive.setup_args (parser = None)
Definition at line 24 of file interactive.py.
Referenced by interactive.MyHandler.respond(), and interactive.setup_interactive().
Variable Documentation
parser
def self_feeding.interactive.parser = setup_args()
Definition at line 89 of file interactive.py.
print_parser
self_feeding.interactive.print_parser
Definition at line 90 of file interactive.py.