ParlAI: parlai.tasks.narrative_qa.build Namespace Reference
parlai.tasks.narrative_qa.build Namespace Reference
Functions
def get_rows_for_set (reader, req_set)
def read_csv_to_dict_list (filepath)
def write_dict_list_to_csv (dict_list, filepath)
def divide_csv_into_sets (csv_filepath, sets=('train', 'valid', 'test'))
def make_folders (base_path, sets=('train', 'valid', 'test'))
def move_files (base_path, sets=('train', 'valid', 'test'))
def try_downloading (directory, row)
def download_stories (path)
def build (opt)
Variables
string NARRATIVE_QA_DOWNLOAD_URL = 'https://github.com/deepmind/narrativeqa/archive/master.zip'
Function Documentation
build()
def parlai.tasks.narrative_qa.build.build (opt)
Definition at line 121 of file build.py.
References parlai.tasks.narrative_qa.build.divide_csv_into_sets(), parlai.tasks.narrative_qa.build.download_stories(), parlai.tasks.narrative_qa.build.make_folders(), and parlai.tasks.narrative_qa.build.move_files().
divide_csv_into_sets()
def parlai.tasks.narrative_qa.build.divide_csv_into_sets (csv_filepath, sets = ('train', 'valid', 'test'))
Definition at line 40 of file build.py.
References parlai.tasks.narrative_qa.build.get_rows_for_set(), parlai.tasks.narrative_qa.build.read_csv_to_dict_list(), and parlai.tasks.narrative_qa.build.write_dict_list_to_csv().
Referenced by parlai.tasks.narrative_qa.build.build().
download_stories()
def parlai.tasks.narrative_qa.build.download_stories (path)
Definition at line 103 of file build.py.
References parlai.tasks.narrative_qa.build.try_downloading().
Referenced by parlai.tasks.narrative_qa.build.build().
get_rows_for_set()
def parlai.tasks.narrative_qa.build.get_rows_for_set (reader, req_set)
Definition at line 19 of file build.py.
Referenced by parlai.tasks.narrative_qa.build.divide_csv_into_sets().
make_folders()
def parlai.tasks.narrative_qa.build.make_folders (base_path, sets = ('train', 'valid', 'test'))
Definition at line 55 of file build.py.
Referenced by parlai.tasks.narrative_qa.build.build().
move_files()
def parlai.tasks.narrative_qa.build.move_files (base_path, sets = ('train', 'valid', 'test'))
Definition at line 62 of file build.py.
Referenced by parlai.tasks.narrative_qa.build.build().
read_csv_to_dict_list()
def parlai.tasks.narrative_qa.build.read_csv_to_dict_list (filepath)
Definition at line 24 of file build.py.
Referenced by parlai.tasks.narrative_qa.build.divide_csv_into_sets().
try_downloading()
def parlai.tasks.narrative_qa.build.try_downloading (directory, row)
Definition at line 75 of file build.py.
Referenced by parlai.tasks.narrative_qa.build.download_stories().
write_dict_list_to_csv()
def parlai.tasks.narrative_qa.build.write_dict_list_to_csv (dict_list, filepath)
Definition at line 29 of file build.py.
Referenced by parlai.tasks.narrative_qa.build.divide_csv_into_sets().
Variable Documentation
NARRATIVE_QA_DOWNLOAD_URL
string parlai.tasks.narrative_qa.build.NARRATIVE_QA_DOWNLOAD_URL = 'https://github.com/deepmind/narrativeqa/archive/master.zip'
Definition at line 16 of file build.py.