ParlAI: parlai.utils.distributed Namespace Reference
parlai.utils.distributed Namespace Reference
Functions
def validate_params (opt)
def is_distributed ()
def num_workers ()
def is_primary_worker ()
def override_print (suppress=False, prefix=None)
def all_gather_list (data, max_size=16384)
def sync_object (data, max_size=16384)
def check_synced_parameters (model)
Variables
bool TORCH_AVAILABLE = True
Function Documentation
all_gather_list()
def parlai.utils.distributed.all_gather_list (data, max_size = 16384)
Gather arbitrary data from all nodes into a list.
Similar to `~torch.distributed.all_gather` but for arbitrary Python
data. Note that *data* must be picklable.
:param data:
    data from the local worker to be gathered on other workers
:param int max_size:
    maximum size of the data to be gathered across workers
:returns:
    a list containing [data1, data2, ...] of all workers
Definition at line 109 of file distributed.py.
References parlai.messenger.core.shared_utils.format, and parlai.utils.distributed.is_distributed().
Referenced by parlai.utils.distributed.check_synced_parameters(), and parlai.scripts.train_model.TrainLoop.validate().
check_synced_parameters()
def parlai.utils.distributed.check_synced_parameters (model)
Check that all parameters across all workers are the same.
Always returns True, or raises an AssertionError if they are not
synchronized.
:param torch.nn.Module model: A pytorch model.
:return: True
Definition at line 227 of file distributed.py.
References parlai.utils.distributed.all_gather_list(), make_control_dataset.float, parlai.messenger.core.shared_utils.format, parlai.utils.distributed.is_distributed(), and generate_task_READMEs.str.
is_distributed()
def parlai.utils.distributed.is_distributed ()
Return if we are in distributed mode.
Definition at line 54 of file distributed.py.
Referenced by parlai.utils.distributed.all_gather_list(), parlai.scripts.build_dict.build_dict(), parlai.utils.distributed.check_synced_parameters(), parlai.utils.distributed.is_primary_worker(), parlai.utils.distributed.num_workers(), parlai.utils.distributed.sync_object(), parlai.scripts.train_model.TrainLoop.train(), and parlai.scripts.train_model.TrainLoop.validate().
is_primary_worker()
def parlai.utils.distributed.is_primary_worker ()
Determine if we are the primary (master) worker.
Returns False if we are a secondary worker. Returns True if we are either
(1) not in distributed mode (2) or are the primary (rank 0) worker.
Definition at line 67 of file distributed.py.
References parlai.utils.distributed.is_distributed().
Referenced by parlai.scripts.train_model.TrainLoop.log(), parlai.scripts.train_model.TrainLoop.save_model(), parlai.scripts.train_model.setup_args(), parlai.utils.distributed.sync_object(), parlai.scripts.train_model.TrainLoop.train(), and parlai.scripts.train_model.TrainLoop.validate().
num_workers()
def parlai.utils.distributed.num_workers ()
Get the total number of workers.
Definition at line 59 of file distributed.py.
References parlai.utils.distributed.is_distributed().
Referenced by parlai.scripts.train_model.TrainLoop.save_model(), and parlai.scripts.train_model.TrainLoop.train().
override_print()
def parlai.utils.distributed.override_print (suppress = False, prefix = None)
Context manager to override the print to suppress or modify output.
Recommended usage is to call this with suppress=True for all non-primary workers,
or call with a prefix of rank on all workers.
>>> with override_print(prefix="rank{}".format(rank)):
...     my_computation()
:param bool suppress:
    if true, all future print statements are noops.
:param str prefix:
    if not None, this string is prefixed to all future print statements.
Definition at line 78 of file distributed.py.
sync_object()
def parlai.utils.distributed.sync_object (data, max_size = 16384)
Sync an object among all workers.
All workers will return the same value for `data` when returning from this
method, always using the primary worker's version. Useful for ensuring control
flow decisions are made the same.
:param object data:
    The object to synchronize. Must be pickleable.
:param int max_size:
    The maximum size of this object in bytes. Large values than 255^2 are not
    supported.
:return: the synchronized data
Definition at line 173 of file distributed.py.
References parlai.utils.distributed.is_distributed(), and parlai.utils.distributed.is_primary_worker().
Referenced by parlai.scripts.train_model.TrainLoop.train(), and parlai.scripts.train_model.TrainLoop.validate().
validate_params()
def parlai.utils.distributed.validate_params (opt)
Ensure sane combinations of command line parameters for distributed training.
Raises exceptions if anything is wrong, otherwise returns None.
Definition at line 28 of file distributed.py.
Variable Documentation
TORCH_AVAILABLE
bool parlai.utils.distributed.TORCH_AVAILABLE = True
Definition at line 23 of file distributed.py.