ParlAI: parlai.mturk.core.legacy_2018.server_utils Namespace Reference
parlai.mturk.core.legacy_2018.server_utils Namespace Reference
Functions
def setup_legacy_heroku_server (task_name, task_files_to_copy=None, heroku_team=None, use_hobby=False, tmp_dir=parent_dir)
def setup_heroku_server (task_name, task_files_to_copy=None, heroku_team=None, use_hobby=False, tmp_dir=parent_dir)
def delete_heroku_server (task_name, tmp_dir=parent_dir)
def setup_local_server (task_name, task_files_to_copy=None)
def delete_local_server (task_name)
def setup_legacy_server (task_name, task_files_to_copy, local=False, heroku_team=None, use_hobby=False, legacy=True, tmp_dir=parent_dir)
def setup_server (task_name, task_files_to_copy, local=False, heroku_team=None, use_hobby=False, legacy=True, tmp_dir=parent_dir)
def delete_server (task_name, local=False, tmp_dir=parent_dir)
Variables
string region_name = 'us-east-1'
user_name = getpass.getuser()
parent_dir = shared_utils.get_core_dir()
string legacy_server_source_directory_name = 'server_legacy'
string server_source_directory_name = 'react_server'
string heroku_server_directory_name = 'heroku_server'
string local_server_directory_name = 'local_server'
string task_directory_name = 'task'
server_process = None
string heroku_url = 'https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli'
Function Documentation
delete_heroku_server()
def parlai.mturk.core.legacy_2018.server_utils.delete_heroku_server (task_name, tmp_dir = parent_dir)
Definition at line 479 of file server_utils.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.mturk.core.legacy_2018.server_utils.delete_server(), parlai.mturk.core.legacy_2018.server_utils.setup_heroku_server(), and parlai.mturk.core.legacy_2018.server_utils.setup_legacy_heroku_server().
delete_local_server()
def parlai.mturk.core.legacy_2018.server_utils.delete_local_server (task_name)
Definition at line 560 of file server_utils.py.
References parlai.messenger.core.shared_utils.format, and parlai.mturk.core.legacy_2018.server_utils.setup_legacy_server().
Referenced by parlai.mturk.core.legacy_2018.server_utils.delete_server().
delete_server()
def parlai.mturk.core.legacy_2018.server_utils.delete_server (task_name, local = False, tmp_dir = parent_dir)
Definition at line 613 of file server_utils.py.
References parlai.mturk.core.legacy_2018.server_utils.delete_heroku_server(), and parlai.mturk.core.legacy_2018.server_utils.delete_local_server().
setup_heroku_server()
def parlai.mturk.core.legacy_2018.server_utils.setup_heroku_server (task_name, task_files_to_copy = None, heroku_team = None, use_hobby = False, tmp_dir = parent_dir)
Definition at line 224 of file server_utils.py.
References parlai.mturk.core.legacy_2018.server_utils.delete_heroku_server(), and parlai.messenger.core.shared_utils.format.
Referenced by parlai.mturk.core.legacy_2018.server_utils.setup_legacy_heroku_server(), and parlai.mturk.core.legacy_2018.server_utils.setup_server().
setup_legacy_heroku_server()
def parlai.mturk.core.legacy_2018.server_utils.setup_legacy_heroku_server (task_name, task_files_to_copy = None, heroku_team = None, use_hobby = False, tmp_dir = parent_dir)
Definition at line 41 of file server_utils.py.
References parlai.mturk.core.legacy_2018.server_utils.delete_heroku_server(), parlai.messenger.core.shared_utils.format, and parlai.mturk.core.legacy_2018.server_utils.setup_heroku_server().
Referenced by parlai.mturk.core.legacy_2018.server_utils.setup_legacy_server().
setup_legacy_server()
def parlai.mturk.core.legacy_2018.server_utils.setup_legacy_server (task_name, task_files_to_copy, local = False, heroku_team = None, use_hobby = False, legacy = True, tmp_dir = parent_dir)
Definition at line 581 of file server_utils.py.
References parlai.mturk.core.legacy_2018.server_utils.setup_legacy_heroku_server(), parlai.mturk.core.legacy_2018.server_utils.setup_local_server(), and parlai.mturk.core.legacy_2018.server_utils.setup_server().
Referenced by parlai.mturk.core.legacy_2018.server_utils.delete_local_server().
setup_local_server()
def parlai.mturk.core.legacy_2018.server_utils.setup_local_server (task_name, task_files_to_copy = None)
Definition at line 507 of file server_utils.py.
References parlai.messenger.core.shared_utils.format, and parlai.mturk.core.dev.test.test_full_system.input.
Referenced by parlai.mturk.core.legacy_2018.server_utils.setup_legacy_server().
setup_server()
def parlai.mturk.core.legacy_2018.server_utils.setup_server (task_name, task_files_to_copy, local = False, heroku_team = None, use_hobby = False, legacy = True, tmp_dir = parent_dir)
Definition at line 601 of file server_utils.py.
References parlai.mturk.core.legacy_2018.server_utils.setup_heroku_server().
Referenced by parlai.mturk.core.legacy_2018.server_utils.setup_legacy_server().
Variable Documentation
heroku_server_directory_name
string parlai.mturk.core.legacy_2018.server_utils.heroku_server_directory_name = 'heroku_server'
Definition at line 26 of file server_utils.py.
heroku_url
string parlai.mturk.core.legacy_2018.server_utils.heroku_url = 'https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli'
Definition at line 32 of file server_utils.py.
legacy_server_source_directory_name
string parlai.mturk.core.legacy_2018.server_utils.legacy_server_source_directory_name = 'server_legacy'
Definition at line 24 of file server_utils.py.
local_server_directory_name
string parlai.mturk.core.legacy_2018.server_utils.local_server_directory_name = 'local_server'
Definition at line 27 of file server_utils.py.
parent_dir
parlai.mturk.core.legacy_2018.server_utils.parent_dir = shared_utils.get_core_dir()
Definition at line 23 of file server_utils.py.
region_name
string parlai.mturk.core.legacy_2018.server_utils.region_name = 'us-east-1'
Definition at line 20 of file server_utils.py.
server_process
parlai.mturk.core.legacy_2018.server_utils.server_process = None
Definition at line 30 of file server_utils.py.
server_source_directory_name
string parlai.mturk.core.legacy_2018.server_utils.server_source_directory_name = 'react_server'
Definition at line 25 of file server_utils.py.
task_directory_name
string parlai.mturk.core.legacy_2018.server_utils.task_directory_name = 'task'
Definition at line 28 of file server_utils.py.
user_name
parlai.mturk.core.legacy_2018.server_utils.user_name = getpass.getuser()
Definition at line 21 of file server_utils.py.