ParlAI: parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas Namespace Reference
parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas Namespace Reference
Functions
def extract_and_save (opt)
def main (opt)
Variables
parser = ParlaiParser()
default
type
choices
help
False
opt = parser.parse_args()
Function Documentation
extract_and_save()
def parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.extract_and_save (opt)
Definition at line 13 of file extract_and_save_personas.py.
References parlai.core.worlds.create_task(), and parlai.messenger.core.shared_utils.format.
Referenced by parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.main().
main()
def parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.main (opt)
Definition at line 48 of file extract_and_save_personas.py.
References parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.extract_and_save(), and parlai.messenger.core.shared_utils.format.
Variable Documentation
choices
parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.choices
Definition at line 66 of file extract_and_save_personas.py.
Referenced by parlai.tasks.coco_caption.agents.DefaultDataset.__getitem__(), and parlai.tasks.coco_caption.agents.DefaultTeacher.get().
default
parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.default
Definition at line 64 of file extract_and_save_personas.py.
False
parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.False
Definition at line 70 of file extract_and_save_personas.py.
help
parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.help
Definition at line 67 of file extract_and_save_personas.py.
opt
parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.opt = parser.parse_args()
Definition at line 72 of file extract_and_save_personas.py.
parser
parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.parser = ParlaiParser()
Definition at line 61 of file extract_and_save_personas.py.
type
parlai.mturk.tasks.personachat.personachat_chat.extract_and_save_personas.type
Definition at line 65 of file extract_and_save_personas.py.