ParlAI: parlai.messenger.core.message_sender Namespace Reference
parlai.messenger.core.message_sender Namespace Reference
Classes
class MessageSender
Functions
def create_attachment (payload)
def create_reply_option (title, payload='')
def create_text_message (text, quick_replies=None)
def create_attachment_message (attachment_item, quick_replies=None)
def create_list_element (element)
def create_compact_list_message (raw_elems)
Variables
int MAX_QUICK_REPLIES = 10
int MAX_TEXT_CHARS = 640
int MAX_QUICK_REPLY_TITLE_CHARS = 20
int MAX_POSTBACK_CHARS = 1000
Function Documentation
create_attachment()
def parlai.messenger.core.message_sender.create_attachment (payload)
Create a simple url-based attachment
Definition at line 22 of file message_sender.py.
Referenced by parlai.messenger.core.message_sender.MessageSender.send_fb_payload().
create_attachment_message()
def parlai.messenger.core.message_sender.create_attachment_message (attachment_item, quick_replies = None)
Create a message list made with only an attachment.
quick_replies should be a list of options made with create_reply_option.
Definition at line 98 of file message_sender.py.
References parlai.messenger.core.shared_utils.format.
create_compact_list_message()
def parlai.messenger.core.message_sender.create_compact_list_message (raw_elems)
Definition at line 129 of file message_sender.py.
References parlai.messenger.core.message_sender.create_list_element().
Referenced by parlai.messenger.core.message_sender.MessageSender.send_fb_payload().
create_list_element()
def parlai.messenger.core.message_sender.create_list_element (element)
Definition at line 113 of file message_sender.py.
Referenced by parlai.messenger.core.message_sender.create_compact_list_message().
create_reply_option()
def parlai.messenger.core.message_sender.create_reply_option (title, payload = '')
Create a quick reply option. Takes in display title and optionally extra
custom data.
Definition at line 43 of file message_sender.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.messenger.core.message_sender.MessageSender.send_fb_message(), and parlai.messenger.core.message_sender.MessageSender.send_fb_payload().
create_text_message()
def parlai.messenger.core.message_sender.create_text_message (text, quick_replies = None)
Return a list of text messages from the given text. If the message is
too long it is split into multiple messages.
quick_replies should be a list of options made with create_reply_option.
Definition at line 60 of file message_sender.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.messenger.core.message_sender.MessageSender.send_fb_message().
Variable Documentation
MAX_POSTBACK_CHARS
int parlai.messenger.core.message_sender.MAX_POSTBACK_CHARS = 1000
Definition at line 15 of file message_sender.py.
MAX_QUICK_REPLIES
int parlai.messenger.core.message_sender.MAX_QUICK_REPLIES = 10
Definition at line 12 of file message_sender.py.
MAX_QUICK_REPLY_TITLE_CHARS
int parlai.messenger.core.message_sender.MAX_QUICK_REPLY_TITLE_CHARS = 20
Definition at line 14 of file message_sender.py.
MAX_TEXT_CHARS
int parlai.messenger.core.message_sender.MAX_TEXT_CHARS = 640
Definition at line 13 of file message_sender.py.