ParlAI: extract_and_save_personas Namespace Reference
extract_and_save_personas Namespace Reference
Functions
def extract_and_save (opt, save=True)
def main (opt)
def extract_and_save (opt)
Variables
parser = ParlaiParser()
default
type
choices
help
False
opt = parser.parse_args()
def personas = main(opt)
Function Documentation
extract_and_save() [1/2]
def extract_and_save_personas.extract_and_save (opt, save = True)
Definition at line 11 of file extract_and_save_personas.py.
References parlai.core.worlds.create_task(), and parlai.messenger.core.shared_utils.format.
Referenced by extract_and_save(), and main().
extract_and_save() [2/2]
def extract_and_save_personas.extract_and_save (opt)
Definition at line 13 of file extract_and_save_personas.py.
References parlai.core.worlds.create_task(), extract_and_save(), parlai.messenger.core.shared_utils.format, and main().
main()
def extract_and_save_personas.main (opt)
Definition at line 47 of file extract_and_save_personas.py.
References extract_and_save(), and parlai.messenger.core.shared_utils.format.
Referenced by extract_and_save().
Variable Documentation
choices
extract_and_save_personas.choices
Definition at line 70 of file extract_and_save_personas.py.
default
extract_and_save_personas.default
Definition at line 68 of file extract_and_save_personas.py.
False
extract_and_save_personas.False
Definition at line 74 of file extract_and_save_personas.py.
help
extract_and_save_personas.help
Definition at line 71 of file extract_and_save_personas.py.
opt
extract_and_save_personas.opt = parser.parse_args()
Definition at line 76 of file extract_and_save_personas.py.
parser
extract_and_save_personas.parser = ParlaiParser()
Definition at line 65 of file extract_and_save_personas.py.
personas
def extract_and_save_personas.personas = main(opt)
Definition at line 77 of file extract_and_save_personas.py.
type
extract_and_save_personas.type
Definition at line 69 of file extract_and_save_personas.py.