ParlAI: mastering_the_dungeon.agents.graph_world2.agents Namespace Reference
mastering_the_dungeon.agents.graph_world2.agents Namespace Reference
Classes
class DataAgentBase
class ModelAgentBase
class ObjectChecklistDataAgent
class ObjectChecklistModelAgent
class Seq2SeqDataAgent
class Seq2SeqModelAgent
Functions
def parse_action_tuple (insts)
def reverse_parse_action (action_tuple)
Variables
nlp = spacy.load('en')
Function Documentation
parse_action_tuple()
def mastering_the_dungeon.agents.graph_world2.agents.parse_action_tuple (insts)
Definition at line 28 of file agents.py.
Referenced by mastering_the_dungeon.agents.graph_world2.agents.ObjectChecklistDataAgent.get_data(), mastering_the_dungeon.agents.graph_world2.agents.Seq2SeqDataAgent.get_data(), and mastering_the_dungeon.agents.graph_world2.agents.DataAgentBase.get_mask().
reverse_parse_action()
def mastering_the_dungeon.agents.graph_world2.agents.reverse_parse_action (action_tuple)
Definition at line 59 of file agents.py.
References parlai.messenger.core.shared_utils.format.
Variable Documentation
nlp
mastering_the_dungeon.agents.graph_world2.agents.nlp = spacy.load('en')
Definition at line 25 of file agents.py.
Referenced by mastering_the_dungeon.agents.graph_world2.agents.ObjectChecklistDataAgent.get_room().