ParlAI: parlai.scripts.eval_wordstat Namespace Reference
parlai.scripts.eval_wordstat Namespace Reference
Functions
def setup_args (parser=None)
def get_word_stats (text, agent_dict, bins=(0, 100, 1000, 100000))
def eval_wordstat (opt, print_parser=None)
Variables
def parser = setup_args()
print_parser
Function Documentation
eval_wordstat()
def parlai.scripts.eval_wordstat.eval_wordstat (opt, print_parser = None)
Evaluates a model.
:param opt: tells the evaluation function how to run
:param print_parser: if provided, prints the options that are set within the
    model after loading the model
Definition at line 110 of file eval_wordstat.py.
References parlai.core.agents.create_agent(), parlai.core.worlds.create_task(), make_control_dataset.float, parlai.messenger.core.shared_utils.format, parlai.scripts.eval_wordstat.get_word_stats(), eval_ppl.int, and parlai.core.metrics.normalize_answer().
get_word_stats()
def parlai.scripts.eval_wordstat.get_word_stats (text, agent_dict, bins = (0, 100, 1000, 100000))
Function which takes text sequence and dict, returns word freq and length statistics
:param sequence: text sequence
:param agent_dict: can be external dict or dict from the model
:param bins: list with range boundaries
:return: freqs dictionary, num words, avg word length, avg char length
Definition at line 87 of file eval_wordstat.py.
Referenced by parlai.scripts.eval_wordstat.eval_wordstat().
setup_args()
def parlai.scripts.eval_wordstat.setup_args (parser = None)
Definition at line 46 of file eval_wordstat.py.
Variable Documentation
parser
def parlai.scripts.eval_wordstat.parser = setup_args()
Definition at line 275 of file eval_wordstat.py.
print_parser
parlai.scripts.eval_wordstat.print_parser
Definition at line 276 of file eval_wordstat.py.