ParlAI: train Namespace Reference
train Namespace Reference
Functions
def prepro (opt)
def validate (opt, agent)
def get_metrics (actions, gt_actions)
def get_accuracy (actions, gt_actions, graph)
def additional_validate (opt, model, data_agent, valid_data_file, constrain_=True, no_hits=False)
def log_print (s, out_file)
def main (opt, return_full=False, out_file=None)
def online_exp (opt, log_file=None)
def ablation_exp (opt)
Variables
parser = setup_args()
task
evaltask
model
model_file
dict_lower
dict_include_valid
dict_maxexs
datatype
hops
lins
embeddingsize
learningrate
share_embeddings
margin
tfidf
max_train_time
validation_every_n_secs
validation_metric
validation_metric_mode
validation_patience
validation_max_examples
log_every_n_secs
numthreads
dict_tokenizer
batchsize
hiddensize
attention
numlayers
rnn_class
dropout
gradient_clip
lookuptable
optimizer
embedding_type
momentum
bidirectional
context_length
embedding_file
tok
learning_rate
dropout_emb
dropout_rnn
argparser = ParlaiParser()
type
int
default
bool
float
str
opt = argparser.parse_args()
job_num = opt['job_num']
string input_file = 'job-in-{}.pkl'.format(job_num)
string output_file = 'job-out-{}.txt'.format(job_num)
string log_file = 'job-log-{}.txt'.format(job_num)
job_in_opt = pickle.load(f_in)
new_opt = deepcopy(opt)
fout = open(output_file, 'w')
dict_file
batch_sort
numsoftmax
truncate
Function Documentation
ablation_exp()
def train.ablation_exp (opt)
Definition at line 339 of file train.py.
References additional_validate(), and main().
Referenced by mastering_the_dungeon.mturk.tasks.MTD.run.overall_ablation().
additional_validate()
def train.additional_validate (opt, model, data_agent, valid_data_file, constrain_ = True, no_hits = False)
Definition at line 102 of file train.py.
References get_accuracy(), and get_metrics().
Referenced by ablation_exp(), mastering_the_dungeon.mturk.tasks.MTD.run.batch_valid(), mastering_the_dungeon.mturk.tasks.MTD.run.batch_valid_with_data(), and get_accuracy().
get_accuracy()
def train.get_accuracy (actions, gt_actions, graph)
Definition at line 93 of file train.py.
References additional_validate(), and float.
Referenced by additional_validate().
get_metrics()
def train.get_metrics (actions, gt_actions)
Definition at line 76 of file train.py.
Referenced by additional_validate().
log_print()
def train.log_print (s, out_file)
Definition at line 230 of file train.py.
Referenced by main().
main()
def train.main (opt, return_full = False, out_file = None)
Definition at line 239 of file train.py.
References parlai.core.worlds.create_task(), parlai.messenger.core.shared_utils.format, int, log_print(), prepro(), and validate().
Referenced by ablation_exp(), and online_exp().
online_exp()
def train.online_exp (opt, log_file = None)
Definition at line 300 of file train.py.
References parlai.messenger.core.shared_utils.format, and main().
prepro()
def train.prepro (opt)
Definition at line 36 of file train.py.
References parlai.core.worlds.create_task().
Referenced by main().
validate()
def train.validate (opt, agent)
Definition at line 54 of file train.py.
References parlai.core.worlds.create_task().
Referenced by main().
Variable Documentation
argparser
train.argparser = ParlaiParser()
Definition at line 357 of file train.py.
attention
train.attention
Definition at line 27 of file train.py.
batch_sort
train.batch_sort
Definition at line 38 of file train.py.
batchsize
train.batchsize
Definition at line 24 of file train.py.
bidirectional
train.bidirectional
Definition at line 37 of file train.py.
bool
train.bool
Definition at line 359 of file train.py.
context_length
train.context_length
Definition at line 38 of file train.py.
datatype
train.datatype
Definition at line 24 of file train.py.
default
train.default
Definition at line 358 of file train.py.
dict_file
train.dict_file
Definition at line 21 of file train.py.
dict_include_valid
train.dict_include_valid
Definition at line 22 of file train.py.
dict_lower
train.dict_lower
Definition at line 21 of file train.py.
dict_maxexs
train.dict_maxexs
Definition at line 23 of file train.py.
dict_tokenizer
train.dict_tokenizer
Definition at line 40 of file train.py.
dropout
train.dropout
Definition at line 31 of file train.py.
Referenced by parlai.agents.starspace.starspace.StarspaceAgent.input_dropout().
dropout_emb
train.dropout_emb
Definition at line 21 of file train.py.
dropout_rnn
train.dropout_rnn
Definition at line 22 of file train.py.
embedding_file
train.embedding_file
Definition at line 18 of file train.py.
embedding_type
train.embedding_type
Definition at line 35 of file train.py.
embeddingsize
train.embeddingsize
Definition at line 27 of file train.py.
evaltask
train.evaltask
Definition at line 18 of file train.py.
float
train.float
Definition at line 360 of file train.py.
Referenced by get_accuracy().
fout
train.fout = open(output_file, 'w')
Definition at line 416 of file train.py.
gradient_clip
train.gradient_clip
Definition at line 32 of file train.py.
hiddensize
train.hiddensize
Definition at line 25 of file train.py.
hops
train.hops
Definition at line 25 of file train.py.
input_file
string train.input_file = 'job-in-{}.pkl'.format(job_num)
Definition at line 400 of file train.py.
int
train.int
Definition at line 358 of file train.py.
Referenced by main().
job_in_opt
train.job_in_opt = pickle.load(f_in)
Definition at line 411 of file train.py.
job_num
train.job_num = opt['job_num']
Definition at line 399 of file train.py.
learning_rate
train.learning_rate
Definition at line 20 of file train.py.
learningrate
train.learningrate
Definition at line 28 of file train.py.
lins
train.lins
Definition at line 26 of file train.py.
log_every_n_secs
train.log_every_n_secs
Definition at line 38 of file train.py.
log_file
string train.log_file = 'job-log-{}.txt'.format(job_num)
Definition at line 402 of file train.py.
lookuptable
train.lookuptable
Definition at line 33 of file train.py.
margin
train.margin
Definition at line 30 of file train.py.
max_train_time
train.max_train_time
Definition at line 32 of file train.py.
model
train.model
Definition at line 19 of file train.py.
model_file
train.model_file
Definition at line 20 of file train.py.
momentum
train.momentum
Definition at line 36 of file train.py.
new_opt
train.new_opt = deepcopy(opt)
Definition at line 413 of file train.py.
numlayers
train.numlayers
Definition at line 28 of file train.py.
numsoftmax
train.numsoftmax
Definition at line 44 of file train.py.
numthreads
train.numthreads
Definition at line 39 of file train.py.
opt
train.opt = argparser.parse_args()
Definition at line 388 of file train.py.
optimizer
train.optimizer
Definition at line 34 of file train.py.
output_file
string train.output_file = 'job-out-{}.txt'.format(job_num)
Definition at line 401 of file train.py.
parser
train.parser = setup_args()
Definition at line 15 of file train.py.
rnn_class
train.rnn_class
Definition at line 29 of file train.py.
share_embeddings
train.share_embeddings
Definition at line 29 of file train.py.
str
train.str
Definition at line 373 of file train.py.
task
train.task
Definition at line 17 of file train.py.
tfidf
train.tfidf
Definition at line 31 of file train.py.
tok
train.tok
Definition at line 19 of file train.py.
truncate
train.truncate
Definition at line 45 of file train.py.
type
train.type
Definition at line 358 of file train.py.
validation_every_n_secs
train.validation_every_n_secs
Definition at line 33 of file train.py.
validation_max_examples
train.validation_max_examples
Definition at line 37 of file train.py.
validation_metric
train.validation_metric
Definition at line 34 of file train.py.
validation_metric_mode
train.validation_metric_mode
Definition at line 35 of file train.py.
validation_patience
train.validation_patience
Definition at line 36 of file train.py.