ParlAI: parlai.agents.drqa.utils Namespace Reference
parlai.agents.drqa.utils Namespace Reference
Classes
class AverageMeter
Functions
def normalize_text (text)
def load_embeddings (opt, word_dict)
def build_feature_dict (opt)
def vectorize (opt, ex, word_dict, feature_dict)
def batchify (batch, null=0, cuda=False)
Function Documentation
batchify()
def parlai.agents.drqa.utils.batchify (batch, null = 0, cuda = False)
Collate inputs into batches.
Definition at line 118 of file utils.py.
Referenced by parlai.agents.drqa.drqa.DrqaAgent.act(), and parlai.agents.drqa.drqa.DrqaAgent.batch_act().
build_feature_dict()
def parlai.agents.drqa.utils.build_feature_dict (opt)
Make mapping of feature option to feature index.
Definition at line 46 of file utils.py.
load_embeddings()
def parlai.agents.drqa.utils.load_embeddings (opt, word_dict)
Initialize embeddings from file of pretrained vectors.
Definition at line 22 of file utils.py.
References make_control_dataset.float, parlai.agents.legacy_agents.seq2seq.utils_v0.modelzoo_path(), and parlai.agents.drqa.utils.normalize_text().
Referenced by parlai.agents.drqa.model.DocReaderModel.set_embeddings().
normalize_text()
def parlai.agents.drqa.utils.normalize_text (text)
Definition at line 18 of file utils.py.
Referenced by parlai.agents.drqa.utils.load_embeddings().
vectorize()
def parlai.agents.drqa.utils.vectorize (opt, ex, word_dict, feature_dict)
Turn tokenized text inputs into feature vectors.
Definition at line 66 of file utils.py.
Referenced by parlai.agents.drqa.drqa.DrqaAgent.save().