ParlAI: parlai.scripts.eval_ppl Namespace Reference
parlai.scripts.eval_ppl Namespace Reference
Classes
class PerplexityWorld
Functions
def setup_args (parser=None)
def eval_ppl (opt, build_dict=None, dict_file=None)
Variables
def parser = setup_args()
def opt = parser.parse_args()
dict_file
Function Documentation
eval_ppl()
def parlai.scripts.eval_ppl.eval_ppl (opt, build_dict = None, dict_file = None)
Evaluates the the perplexity of a model.
This uses a dictionary which implements the following functions:
- tokenize(text): splits string up into list of tokens
- __in__(text): checks whether dictionary contains a token
- keys(): returns an iterator over all tokens in the dictionary
:param opt: option dict
:param build_dict: function which returns a dictionary class implementing
    the functions above.
:param dict_file: file used when loading the dictionary class set via the
    "dictionary_class" argument (defaults to
    parlai.core.dict:DictionaryAgent).
Either build_dict or dict_file must be set (both default to None) to
determine the dictionary used for the evaluation.
Definition at line 180 of file eval_ppl.py.
References parlai.core.agents.create_agent(), parlai.core.worlds.create_task(), make_control_dataset.float, parlai.messenger.core.shared_utils.format, eval_ppl.int, parlai.agents.legacy_agents.seq2seq.utils_v0.round_sigfigs(), and generate_task_READMEs.str.
setup_args()
def parlai.scripts.eval_ppl.setup_args (parser = None)
Definition at line 46 of file eval_ppl.py.
Variable Documentation
dict_file
parlai.scripts.eval_ppl.dict_file
Definition at line 257 of file eval_ppl.py.
opt
parlai.scripts.eval_ppl.opt = parser.parse_args()
Definition at line 256 of file eval_ppl.py.
parser
def parlai.scripts.eval_ppl.parser = setup_args()
Definition at line 254 of file eval_ppl.py.