ParlAI: convai2.eval_f1 Namespace Reference
convai2.eval_f1 Namespace Reference
Functions
def setup_args (parser=None)
def eval_f1 (opt, print_parser)
Variables
def parser = setup_args()
model
def opt = parser.parse_args()
def report = eval_f1(opt, parser)
Function Documentation
eval_f1()
def convai2.eval_f1.eval_f1 (opt, print_parser)
Definition at line 26 of file eval_f1.py.
References generate_task_READMEs.str.
setup_args()
def convai2.eval_f1.setup_args (parser = None)
Definition at line 14 of file eval_f1.py.
Referenced by eval_f1.main().
Variable Documentation
model
convai2.eval_f1.model
Definition at line 35 of file eval_f1.py.
opt
def convai2.eval_f1.opt = parser.parse_args()
Definition at line 36 of file eval_f1.py.
parser
def convai2.eval_f1.parser = setup_args()
Definition at line 34 of file eval_f1.py.
report
def convai2.eval_f1.report = eval_f1(opt, parser)
Definition at line 37 of file eval_f1.py.
Referenced by parlai.core.metrics.aggregate_metrics(), and parlai.scripts.train_model.TrainLoop.log().