ParlAI: parlai.scripts.extract_image_feature Namespace Reference
parlai.scripts.extract_image_feature Namespace Reference
Functions
def setup_args (parser=None)
def get_dataset_class (opt)
def extract_feats (opt)
Function Documentation
extract_feats()
def parlai.scripts.extract_image_feature.extract_feats (opt)
Definition at line 85 of file extract_image_feature.py.
References parlai.core.worlds.create_task(), parlai.messenger.core.shared_utils.format, parlai.scripts.extract_image_feature.get_dataset_class(), parlai.scripts.extract_image_feature.setup_args(), and generate_task_READMEs.str.
get_dataset_class()
def parlai.scripts.extract_image_feature.get_dataset_class (opt)
To use a custom Pytorch Dataset, specify it on the command line:
    ``--dataset parlai.tasks.vqa_v1.agents:VQADataset``
    Note that if the dataset is named ``DefaultDataset``, then you do
    not need to specify its name following the colon; e.g., it
    would just be:
    ``--dataset parlai.tasks.vqa_v1.agents``
Definition at line 65 of file extract_image_feature.py.
Referenced by parlai.scripts.extract_image_feature.extract_feats().
setup_args()
def parlai.scripts.extract_image_feature.setup_args (parser = None)
Definition at line 35 of file extract_image_feature.py.
Referenced by parlai.scripts.extract_image_feature.extract_feats().