ParlAI: generate Namespace Reference
generate Namespace Reference
Functions
def ghmarkdown (source)
def wrap_base (content, title)
def make_errorpage ()
def make_aboutpage ()
def make_homepage ()
def make_projects_landing ()
def make_projects_individual ()
def main ()
Variables
GIT_ROOT_LEVEL = git.Git().rev_parse('--show-toplevel')
WEBSITE_ROOT = os.path.join(GIT_ROOT_LEVEL, 'website')
TEMPLATES = os.path.join(WEBSITE_ROOT, 'templates')
OUT_DIR = os.path.join(WEBSITE_ROOT, 'build')
Function Documentation
ghmarkdown()
def generate.ghmarkdown (source)
Definition at line 22 of file generate.py.
References parlai.messenger.core.shared_utils.format.
Referenced by make_aboutpage(), make_homepage(), make_projects_individual(), and make_projects_landing().
main()
def generate.main ()
Definition at line 123 of file generate.py.
References make_aboutpage(), make_errorpage(), make_homepage(), make_projects_individual(), and make_projects_landing().
make_aboutpage()
def generate.make_aboutpage ()
Definition at line 62 of file generate.py.
References ghmarkdown(), and wrap_base().
Referenced by main().
make_errorpage()
def generate.make_errorpage ()
Definition at line 56 of file generate.py.
References wrap_base().
Referenced by main().
make_homepage()
def generate.make_homepage ()
Definition at line 76 of file generate.py.
References ghmarkdown(), and wrap_base().
Referenced by main().
make_projects_individual()
def generate.make_projects_individual ()
Definition at line 101 of file generate.py.
References parlai.messenger.core.shared_utils.format, ghmarkdown(), and wrap_base().
Referenced by main().
make_projects_landing()
def generate.make_projects_landing ()
Definition at line 86 of file generate.py.
References ghmarkdown(), and wrap_base().
Referenced by main().
wrap_base()
def generate.wrap_base (content, title)
Definition at line 49 of file generate.py.
Referenced by make_aboutpage(), make_errorpage(), make_homepage(), make_projects_individual(), and make_projects_landing().
Variable Documentation
GIT_ROOT_LEVEL
generate.GIT_ROOT_LEVEL = git.Git().rev_parse('--show-toplevel')
Definition at line 16 of file generate.py.
OUT_DIR
generate.OUT_DIR = os.path.join(WEBSITE_ROOT, 'build')
Definition at line 19 of file generate.py.
TEMPLATES
generate.TEMPLATES = os.path.join(WEBSITE_ROOT, 'templates')
Definition at line 18 of file generate.py.
WEBSITE_ROOT
generate.WEBSITE_ROOT = os.path.join(GIT_ROOT_LEVEL, 'website')
Definition at line 17 of file generate.py.