ParlAI: parlai.mturk.core.legacy_2018.test.test_mturk_manager Namespace Reference
parlai.mturk.core.legacy_2018.test.test_mturk_manager Namespace Reference
Classes
class InitTestMTurkManager
class MockSocket
class TestMTurkManagerConnectedFunctions
class TestMTurkManagerLifecycleFunctions
class TestMTurkManagerPoolHandling
class TestMTurkManagerTimeHandling
class TestMTurkManagerUnitFunctions
Functions
def assert_equal_by (val_func, val, max_time)
Variables
parent_dir = os.path.dirname(os.path.abspath(__file__))
mturk_utils
print_and_log
string TEST_WORKER_ID_1 = 'TEST_WORKER_ID_1'
string TEST_WORKER_ID_2 = 'TEST_WORKER_ID_2'
string TEST_WORKER_ID_3 = 'TEST_WORKER_ID_3'
string TEST_ASSIGNMENT_ID_1 = 'TEST_ASSIGNMENT_ID_1'
string TEST_ASSIGNMENT_ID_2 = 'TEST_ASSIGNMENT_ID_2'
string TEST_ASSIGNMENT_ID_3 = 'TEST_ASSIGNMENT_ID_3'
string TEST_HIT_ID_1 = 'TEST_HIT_ID_1'
string TEST_HIT_ID_2 = 'TEST_HIT_ID_2'
string TEST_HIT_ID_3 = 'TEST_HIT_ID_3'
string FAKE_ID = 'BOGUS'
buffer
Function Documentation
assert_equal_by()
def parlai.mturk.core.legacy_2018.test.test_mturk_manager.assert_equal_by (val_func, val, max_time)
Definition at line 44 of file test_mturk_manager.py.
Referenced by parlai.mturk.core.legacy_2018.test.test_mturk_manager.TestMTurkManagerLifecycleFunctions.test_full_lifecycle(), parlai.mturk.core.legacy_2018.test.test_mturk_manager.TestMTurkManagerUnitFunctions.test_onboarding_function(), parlai.mturk.core.legacy_2018.test.test_mturk_manager.TestMTurkManagerConnectedFunctions.test_restore_state(), and parlai.mturk.core.legacy_2018.test.test_mturk_manager.TestMTurkManagerUnitFunctions.test_wait_for_task_expirations().
Variable Documentation
buffer
parlai.mturk.core.legacy_2018.test.test_mturk_manager.buffer
Definition at line 1757 of file test_mturk_manager.py.
FAKE_ID
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.FAKE_ID = 'BOGUS'
Definition at line 41 of file test_mturk_manager.py.
mturk_utils
parlai.mturk.core.legacy_2018.test.test_mturk_manager.mturk_utils
Definition at line 27 of file test_mturk_manager.py.
parent_dir
parlai.mturk.core.legacy_2018.test.test_mturk_manager.parent_dir = os.path.dirname(os.path.abspath(__file__))
Definition at line 24 of file test_mturk_manager.py.
print_and_log
parlai.mturk.core.legacy_2018.test.test_mturk_manager.print_and_log
Definition at line 30 of file test_mturk_manager.py.
TEST_ASSIGNMENT_ID_1
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_ASSIGNMENT_ID_1 = 'TEST_ASSIGNMENT_ID_1'
Definition at line 35 of file test_mturk_manager.py.
TEST_ASSIGNMENT_ID_2
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_ASSIGNMENT_ID_2 = 'TEST_ASSIGNMENT_ID_2'
Definition at line 36 of file test_mturk_manager.py.
TEST_ASSIGNMENT_ID_3
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_ASSIGNMENT_ID_3 = 'TEST_ASSIGNMENT_ID_3'
Definition at line 37 of file test_mturk_manager.py.
TEST_HIT_ID_1
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_HIT_ID_1 = 'TEST_HIT_ID_1'
Definition at line 38 of file test_mturk_manager.py.
TEST_HIT_ID_2
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_HIT_ID_2 = 'TEST_HIT_ID_2'
Definition at line 39 of file test_mturk_manager.py.
TEST_HIT_ID_3
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_HIT_ID_3 = 'TEST_HIT_ID_3'
Definition at line 40 of file test_mturk_manager.py.
TEST_WORKER_ID_1
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_WORKER_ID_1 = 'TEST_WORKER_ID_1'
Definition at line 32 of file test_mturk_manager.py.
TEST_WORKER_ID_2
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_WORKER_ID_2 = 'TEST_WORKER_ID_2'
Definition at line 33 of file test_mturk_manager.py.
TEST_WORKER_ID_3
string parlai.mturk.core.legacy_2018.test.test_mturk_manager.TEST_WORKER_ID_3 = 'TEST_WORKER_ID_3'
Definition at line 34 of file test_mturk_manager.py.