ParlAI: parlai.mturk.core.legacy_2018.mturk_utils Namespace Reference
parlai.mturk.core.legacy_2018.mturk_utils Namespace Reference
Functions
def setup_aws_credentials ()
def calculate_mturk_cost (payment_opt)
def check_mturk_balance (balance_needed, is_sandbox)
def create_hit_config (opt, task_description, unique_worker, is_sandbox)
def get_mturk_client (is_sandbox)
def delete_qualification (qualification_id, is_sandbox)
def find_qualification (qualification_name, is_sandbox, must_be_owned=True)
def find_or_create_qualification (qualification_name, description, is_sandbox, must_be_owned=True)
def give_worker_qualification (worker_id, qualification_id, value=None, is_sandbox=True)
def remove_worker_qualification (worker_id, qualification_id, is_sandbox=True, reason='')
def create_hit_type (hit_title, hit_description, hit_keywords, hit_reward, assignment_duration_in_seconds, is_sandbox, qualifications=None, auto_approve_delay=7 *24 *3600)
def create_hit_with_hit_type (opt, page_url, hit_type_id, num_assignments, is_sandbox)
def expire_hit (is_sandbox, hit_id)
def setup_sns_topic (task_name, server_url, task_group_id)
def subscribe_to_hits (hit_type_id, is_sandbox, sns_arn)
def send_test_notif (topic_arn, event_type)
def delete_sns_topic (topic_arn)
Variables
string region_name = 'us-east-1'
string aws_profile_name = 'parlai_mturk'
client = None
parent_dir = os.path.dirname(os.path.abspath(__file__))
Function Documentation
calculate_mturk_cost()
def parlai.mturk.core.legacy_2018.mturk_utils.calculate_mturk_cost (payment_opt)
MTurk Pricing: https://requester.mturk.com/pricing
20% fee on the reward and bonus amount (if any) you pay Workers.
HITs with 10 or more assignments will be charged an additional
20% fee on the reward you pay Workers.
Example payment_opt format for paying reward:
{
    'type': 'reward',
    'num_total_assignments': 1,
    'reward': 0.05  # in dollars
}
Example payment_opt format for paying bonus:
{
    'type': 'bonus',
    'amount': 1000  # in dollars
}
Definition at line 73 of file mturk_utils.py.
check_mturk_balance()
def parlai.mturk.core.legacy_2018.mturk_utils.check_mturk_balance (balance_needed, is_sandbox)
Checks to see if there is at least balance_needed amount in the
requester account, returns True if the balance is greater than
balance_needed
Definition at line 101 of file mturk_utils.py.
References make_control_dataset.float, parlai.messenger.core.shared_utils.format, and parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
create_hit_config()
def parlai.mturk.core.legacy_2018.mturk_utils.create_hit_config (opt, task_description, unique_worker, is_sandbox)
Writes a HIT config to file
Definition at line 137 of file mturk_utils.py.
create_hit_type()
def parlai.mturk.core.legacy_2018.mturk_utils.create_hit_type (hit_title, hit_description, hit_keywords, hit_reward, assignment_duration_in_seconds, is_sandbox, qualifications = None, auto_approve_delay = 7 * 24 * 3600)
Create a HIT type to be used to generate HITs of the requested params
Definition at line 283 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client(), and generate_task_READMEs.str.
Referenced by parlai.mturk.core.legacy_2018.mturk_utils.remove_worker_qualification().
create_hit_with_hit_type()
def parlai.mturk.core.legacy_2018.mturk_utils.create_hit_with_hit_type (opt, page_url, hit_type_id, num_assignments, is_sandbox)
Creates the actual HIT given the type and page to direct clients to
Definition at line 327 of file mturk_utils.py.
References parlai.messenger.core.shared_utils.format, and parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
delete_qualification()
def parlai.mturk.core.legacy_2018.mturk_utils.delete_qualification (qualification_id, is_sandbox)
Deletes a qualification by id
Definition at line 177 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
delete_sns_topic()
def parlai.mturk.core.legacy_2018.mturk_utils.delete_sns_topic (topic_arn)
Definition at line 441 of file mturk_utils.py.
expire_hit()
def parlai.mturk.core.legacy_2018.mturk_utils.expire_hit (is_sandbox, hit_id)
Definition at line 366 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
find_or_create_qualification()
def parlai.mturk.core.legacy_2018.mturk_utils.find_or_create_qualification (qualification_name, description, is_sandbox, must_be_owned = True)
Query amazon to find the existing qualification name, return the Id. If
it exists and must_be_owned is true but we don't own it, this prints an
error and returns none. If it doesn't exist, the qualification is created
Definition at line 220 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.find_qualification(), and parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
Referenced by parlai.mturk.core.legacy_2018.mturk_utils.find_qualification().
find_qualification()
def parlai.mturk.core.legacy_2018.mturk_utils.find_qualification (qualification_name, is_sandbox, must_be_owned = True)
Query amazon to find the existing qualification name, return the Id,
otherwise return none.
If must_be_owned is true, it only returns qualifications owned by the user.
Will return False if it finds another's qualification
Definition at line 183 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.find_or_create_qualification(), parlai.messenger.core.shared_utils.format, and parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
Referenced by parlai.mturk.core.legacy_2018.mturk_utils.find_or_create_qualification().
get_mturk_client()
def parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client (is_sandbox)
Returns the appropriate mturk client given sandbox option
Definition at line 162 of file mturk_utils.py.
Referenced by parlai.mturk.core.legacy_2018.mturk_utils.check_mturk_balance(), parlai.mturk.core.legacy_2018.mturk_utils.create_hit_type(), parlai.mturk.core.legacy_2018.mturk_utils.create_hit_with_hit_type(), parlai.mturk.core.legacy_2018.mturk_utils.delete_qualification(), parlai.mturk.core.legacy_2018.mturk_utils.expire_hit(), parlai.mturk.core.legacy_2018.mturk_utils.find_or_create_qualification(), parlai.mturk.core.legacy_2018.mturk_utils.find_qualification(), parlai.mturk.core.legacy_2018.mturk_utils.give_worker_qualification(), parlai.mturk.core.legacy_2018.mturk_utils.remove_worker_qualification(), parlai.mturk.core.legacy_2018.mturk_utils.send_test_notif(), and parlai.mturk.core.legacy_2018.mturk_utils.subscribe_to_hits().
give_worker_qualification()
def parlai.mturk.core.legacy_2018.mturk_utils.give_worker_qualification (worker_id, qualification_id, value = None, is_sandbox = True)
Give a qualification to the given worker
Definition at line 244 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client(), and parlai.mturk.core.legacy_2018.mturk_utils.remove_worker_qualification().
remove_worker_qualification()
def parlai.mturk.core.legacy_2018.mturk_utils.remove_worker_qualification (worker_id, qualification_id, is_sandbox = True, reason = '')
Give a qualification to the given worker
Definition at line 266 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.create_hit_type(), and parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
Referenced by parlai.mturk.core.legacy_2018.mturk_utils.give_worker_qualification().
send_test_notif()
def parlai.mturk.core.legacy_2018.mturk_utils.send_test_notif (topic_arn, event_type)
Definition at line 424 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
setup_aws_credentials()
def parlai.mturk.core.legacy_2018.mturk_utils.setup_aws_credentials ()
Definition at line 23 of file mturk_utils.py.
References parlai.messenger.core.shared_utils.format, and parlai.mturk.core.dev.test.test_full_system.input.
setup_sns_topic()
def parlai.mturk.core.legacy_2018.mturk_utils.setup_sns_topic (task_name, server_url, task_group_id)
Definition at line 373 of file mturk_utils.py.
References parlai.messenger.core.shared_utils.format.
subscribe_to_hits()
def parlai.mturk.core.legacy_2018.mturk_utils.subscribe_to_hits (hit_type_id, is_sandbox, sns_arn)
Definition at line 405 of file mturk_utils.py.
References parlai.mturk.core.legacy_2018.mturk_utils.get_mturk_client().
Variable Documentation
aws_profile_name
string parlai.mturk.core.legacy_2018.mturk_utils.aws_profile_name = 'parlai_mturk'
Definition at line 17 of file mturk_utils.py.
client
parlai.mturk.core.legacy_2018.mturk_utils.client = None
Definition at line 18 of file mturk_utils.py.
parent_dir
parlai.mturk.core.legacy_2018.mturk_utils.parent_dir = os.path.dirname(os.path.abspath(__file__))
Definition at line 20 of file mturk_utils.py.
region_name
string parlai.mturk.core.legacy_2018.mturk_utils.region_name = 'us-east-1'
Definition at line 16 of file mturk_utils.py.