ParlAI: parlai.core.dict Namespace Reference
parlai.core.dict Namespace Reference
Classes
class _BPEHelper
class DictionaryAgent
Functions
def escape (s)
def unescape (s)
def find_ngrams (token_dict, text, n)
Variables
bool BPE_INSTALLED = True
RETOK = re.compile(r'\w+|[^\w\s]|\n', re.UNICODE)
Function Documentation
escape()
def parlai.core.dict.escape (s)
Replace potential special characters with escaped version.
For example, \n => \\n and \t => \\t
:param s:
    string to escape
Definition at line 31 of file dict.py.
Referenced by parlai.core.dict.DictionaryAgent.save().
find_ngrams()
def parlai.core.dict.find_ngrams (token_dict, text, n)
Break text into ngrams that appear in ``token_dict``.
:param token_dict:
    ``dict`` to check for ngrams
:param text:
    ``str`` to look for ngrams in
:param n:
    ``int`` max size of ngrams
Definition at line 55 of file dict.py.
Referenced by parlai.core.dict.DictionaryAgent.tokenize().
unescape()
def parlai.core.dict.unescape (s)
Revert escaped characters back to their special version.
For example, \\n => \n and \\t => \t
:param s:
    string to unescape
Definition at line 43 of file dict.py.
Referenced by parlai.core.dict.DictionaryAgent.load().
Variable Documentation
BPE_INSTALLED
bool parlai.core.dict.BPE_INSTALLED = True
Definition at line 24 of file dict.py.
RETOK
parlai.core.dict.RETOK = re.compile(r'\w+|[^\w\s]|\n', re.UNICODE)
Definition at line 28 of file dict.py.