ParlAI: self_feeding.utils Namespace Reference
self_feeding.utils Namespace Reference
Classes
class Parley
Functions
def sanitize_parley (parley)
def add_person_tokens (responses, first_speaker=None, last_speaker=1)
def extract_fb_episodes (datafile)
def extract_parlai_episodes (datafile)
def episode_to_examples (episode, histsz)
Function Documentation
add_person_tokens()
def self_feeding.utils.add_person_tokens (responses, first_speaker = None, last_speaker = 1)
Converts a list of responses into a single tag-separated string
Args:
    responses: list of responses (strings)
    first_speaker: either 1 or 2; the owner of the first response
    last_speaker: either 1 or 2; the owner of the last response
        NOTE: if first_speaker is provided, it overrides last_speaker
Output:
    text: the concatenated text
e.g.,
responses = ["How are you?", "I'm doing fine!", "I'm glad to hear it!"]
result = add_person_tokens(responses)
result: "__p1__ How are you? __p2__ I'm doing fine! __p1__ I'm glad to
    hear it!"
Definition at line 102 of file utils.py.
Referenced by self_feeding.utils.episode_to_examples(), convert_suggested_to_stitched.main(), convert_sliced_to_unfiltered.main(), convert_sliced_to_identity.main(), convert_chatted_to_identity.main(), convert_chatted_to_polarized.main(), convert_rated_to_polarized.main(), and convert_chatted_to_unfiltered.main().
episode_to_examples()
def self_feeding.utils.episode_to_examples (episode, histsz)
Converts an episode (list of Parleys) into self-feeding compatible examples
WARNING: we no longer require a histz when making a self-feeding file. Shortening of
the history is typically done in the teacher file or in interactive mode.
Definition at line 156 of file utils.py.
References self_feeding.utils.add_person_tokens().
Referenced by convert_fb_to_meta.main(), and split_convai2_topics.main().
extract_fb_episodes()
def self_feeding.utils.extract_fb_episodes (datafile)
Definition at line 129 of file utils.py.
References self_feeding.utils.sanitize_parley(), and parlai.tasks.aqua.agents.setup_data().
Referenced by convert_fb_to_meta.main(), and split_convai2_topics.main().
extract_parlai_episodes()
def self_feeding.utils.extract_parlai_episodes (datafile)
Definition at line 144 of file utils.py.
Referenced by convert_sliced_to_identity.main(), convert_suggested_to_stitched.main(), convert_sliced_to_unfiltered.main(), convert_rated_to_sliced.main(), convert_chatted_to_polarized.main(), convert_chatted_to_identity.main(), convert_rated_to_polarized.main(), and convert_chatted_to_unfiltered.main().
sanitize_parley()
def self_feeding.utils.sanitize_parley (parley)
Separate memories from context, pull out response, split context/memories lists
Definition at line 87 of file utils.py.
Referenced by self_feeding.utils.extract_fb_episodes().