ParlAI: parlai.utils.testing Namespace Reference
parlai.utils.testing Namespace Reference
Classes
class retry
class TeeStringIO
Functions
def is_this_circleci ()
def skipUnlessTorch (testfn, reason='pytorch is not installed')
def skipIfGPU (testfn, reason='Test is CPU-only')
def skipUnlessGPU (testfn, reason='Test requires a GPU')
def skipUnlessBPE (testfn, reason='Test requires a GPU')
def skipIfCircleCI (testfn, reason='Test disabled in CircleCI')
def git_ls_files (root=None, skip_nonexisting=True)
def git_ls_dirs (root=None)
def git_changed_files (skip_nonexisting=True)
def git_commit_messages ()
def is_new_task_filename (filename)
def capture_output ()
def tempdir ()
def train_model (opt)
def eval_model (opt, skip_valid=False, skip_test=False)
def display_data (opt)
def display_model (opt)
def download_unittest_models ()
Variables
bool TORCH_AVAILABLE = True
int GPU_AVAILABLE = torch.cuda.device_count() > 0
git_ = git.Git()
bool GIT_AVAILABLE = True
bool BPE_INSTALLED = True
bool DEBUG = False
Function Documentation
capture_output()
def parlai.utils.testing.capture_output ()
Suppress all logging output into a single buffer.
Use as a context manager.
>>> with capture_output() as output:
...     print('hello')
>>> output.getvalue()
'hello'
Definition at line 187 of file testing.py.
Referenced by parlai.utils.testing.display_data(), parlai.utils.testing.display_model(), parlai.utils.testing.download_unittest_models(), parlai.utils.testing.eval_model(), tests.test_torch_agent.TestLegacyVersioning.test_legacy_version(), tests.test_torch_agent.TestTorchAgent.test_resume_checkpoint(), and parlai.utils.testing.train_model().
display_data()
def parlai.utils.testing.display_data (opt)
Run through a display data run.
:return: (stdout_train, stdout_valid, stdout_test)
:rtype: (str, str, str)
Definition at line 289 of file testing.py.
References parlai.utils.testing.capture_output().
display_model()
def parlai.utils.testing.display_model (opt, Tuple, str, str)
Run display_model.py.
:return: (stdout_valid, stdout_test)
Definition at line 315 of file testing.py.
References parlai.utils.testing.capture_output().
download_unittest_models()
def parlai.utils.testing.download_unittest_models ()
Download the unittest pretrained models.
Definition at line 339 of file testing.py.
References parlai.utils.testing.capture_output(), and parlai.core.build_data.download_models().
eval_model()
def parlai.utils.testing.eval_model (opt, skip_valid = False, skip_test = False)
Run through an evaluation loop.
:param opt:
    Any non-default options you wish to set.
:param bool skip_valid:
    If true skips the valid evaluation, and the second return value will be None.
:param bool skip_test:
    If true skips the test evaluation, and the third return value will be None.
:return: (stdout, valid_results, test_results)
:rtype: (str, dict, dict)
If model_file is not in opt, then this helper will create a temporary directory
to store the model files, and clean up afterwards. You can keep the directory
by disabling autocleanup
Definition at line 252 of file testing.py.
References parlai.utils.testing.capture_output().
git_changed_files()
def parlai.utils.testing.git_changed_files (skip_nonexisting = True)
List all the changed files in the git repository.
:param bool skip_nonexisting:
    If true, ignore files that don't exist on disk. This is useful for
    disregarding files created in master, but don't exist in HEAD.
Definition at line 130 of file testing.py.
git_commit_messages()
def parlai.utils.testing.git_commit_messages ()
Output each commit message between here and master.
Definition at line 145 of file testing.py.
git_ls_dirs()
def parlai.utils.testing.git_ls_dirs (root = None)
List all folders tracked by git.
Definition at line 122 of file testing.py.
References parlai.utils.testing.git_ls_files().
git_ls_files()
def parlai.utils.testing.git_ls_files (root = None, skip_nonexisting = True)
List all files tracked by git.
Definition at line 114 of file testing.py.
Referenced by parlai.utils.testing.git_ls_dirs().
is_new_task_filename()
def parlai.utils.testing.is_new_task_filename (filename)
Check if a given filename counts as a new task.
Used in tests and test triggers, and only here to avoid redundancy.
Definition at line 152 of file testing.py.
is_this_circleci()
def parlai.utils.testing.is_this_circleci ()
Return if we are currently running in CircleCI.
Definition at line 48 of file testing.py.
References mastering_the_dungeon.mturk.tasks.MTD.run.bool.
Referenced by parlai.utils.testing.skipIfCircleCI().
skipIfCircleCI()
def parlai.utils.testing.skipIfCircleCI (testfn, reason = 'Test disabled in CircleCI')
Decorate a test to skip if running on CircleCI.
Definition at line 77 of file testing.py.
References parlai.utils.testing.is_this_circleci().
skipIfGPU()
def parlai.utils.testing.skipIfGPU (testfn, reason = 'Test is CPU-only')
Decorate a test to skip if a GPU is available.
Useful for disabling hogwild tests.
Definition at line 58 of file testing.py.
skipUnlessBPE()
def parlai.utils.testing.skipUnlessBPE (testfn, reason = 'Test requires a GPU')
Decorate a test to skip if BPE is not installed.
Definition at line 72 of file testing.py.
skipUnlessGPU()
def parlai.utils.testing.skipUnlessGPU (testfn, reason = 'Test requires a GPU')
Decorate a test to skip if no GPU is available.
Definition at line 67 of file testing.py.
skipUnlessTorch()
def parlai.utils.testing.skipUnlessTorch (testfn, reason = 'pytorch is not installed')
Decorate a test to skip if torch is not installed.
Definition at line 53 of file testing.py.
tempdir()
def parlai.utils.testing.tempdir ()
Create a temporary directory.
Use as a context manager so the directory is automatically cleaned up.
>>> with tempdir() as tmpdir:
...    print(tmpdir)  # prints a folder like /tmp/randomname
Definition at line 204 of file testing.py.
Referenced by tests.test_torch_agent.TestTorchAgent.test_resume_checkpoint(), and parlai.utils.testing.train_model().
train_model()
def parlai.utils.testing.train_model (opt)
Run through a TrainLoop.
If model_file is not in opt, then this helper will create a temporary
directory to store the model, dict, etc.
:return: (stdout, valid_results, test_results)
:rtype: (str, dict, dict)
Definition at line 218 of file testing.py.
References parlai.utils.testing.capture_output(), and parlai.utils.testing.tempdir().
Variable Documentation
BPE_INSTALLED
bool parlai.utils.testing.BPE_INSTALLED = True
Definition at line 40 of file testing.py.
DEBUG
bool parlai.utils.testing.DEBUG = False
Definition at line 45 of file testing.py.
git_
parlai.utils.testing.git_ = git.Git()
Definition at line 31 of file testing.py.
GIT_AVAILABLE
bool parlai.utils.testing.GIT_AVAILABLE = True
Definition at line 32 of file testing.py.
GPU_AVAILABLE
bool parlai.utils.testing.GPU_AVAILABLE = torch.cuda.device_count() > 0
Definition at line 23 of file testing.py.
TORCH_AVAILABLE
bool parlai.utils.testing.TORCH_AVAILABLE = True
Definition at line 22 of file testing.py.