ParlAI: eval_wordstat Namespace Reference
eval_wordstat Namespace Reference
Functions
def setup_args (parser=None)
def get_word_stats (text, agent_dict, bins=[0)
def update_sent_attr_stats (sent_attrs, history, prediction)
def eval_wordstat (opt, print_parser=None)
Variables
def parser = setup_args()
print_parser
model
task
external_dict
model_file
dict_file
dict_lower
batchsize
numthreads
opt = parser.parse_args(print_args=False)
list fnames
version
Function Documentation
eval_wordstat()
def eval_wordstat.eval_wordstat (opt, print_parser = None)
Evaluates a model.
:param opt: tells the evaluation function how to run
:param print_parser: if provided, prints the options that are set within the
    model after loading the model
Definition at line 119 of file eval_wordstat.py.
References parlai.core.agents.create_agent(), parlai.core.worlds.create_task(), make_control_dataset.float, parlai.messenger.core.shared_utils.format, get_word_stats(), controllable_seq2seq.controls.initialize_control_information(), eval_ppl.int, parlai.core.metrics.normalize_answer(), generate_task_READMEs.str, and update_sent_attr_stats().
get_word_stats()
def eval_wordstat.get_word_stats (text, agent_dict, bins = [0)
Function which takes text sequence and dict, returns word freq and length statistics
:param sequence: text sequence
:param agent_dict: can be external dict or dict from the model
:param bins: list with range boundaries
:return: freqs dictionary, num words, avg word length, avg char length
Definition at line 80 of file eval_wordstat.py.
Referenced by eval_wordstat().
setup_args()
def eval_wordstat.setup_args (parser = None)
Definition at line 36 of file eval_wordstat.py.
update_sent_attr_stats()
def eval_wordstat.update_sent_attr_stats (sent_attrs, history, prediction)
Update the sent_attrs dict with the attributes of a prediction with given history.
Inputs:
  sent_attrs: dictionary mapping each attr (a string) to a list of floats
    (the scores).
  history: a ConvAI2History
  prediction: string. the response text for which we measure sent attributes
Definition at line 103 of file eval_wordstat.py.
Referenced by eval_wordstat().
Variable Documentation
batchsize
eval_wordstat.batchsize
Definition at line 24 of file eval_wordstat.py.
dict_file
eval_wordstat.dict_file
Definition at line 22 of file eval_wordstat.py.
dict_lower
eval_wordstat.dict_lower
Definition at line 23 of file eval_wordstat.py.
external_dict
eval_wordstat.external_dict
Definition at line 20 of file eval_wordstat.py.
fnames
list eval_wordstat.fnames
Initial value:
 =  [
             'convai2_self_seq2seq_model.tgz',
             'convai2_self_seq2seq_model.dict',
             'convai2_self_seq2seq_model.opt',
         ]
Definition at line 33 of file eval_wordstat.py.
model
eval_wordstat.model
Definition at line 18 of file eval_wordstat.py.
model_file
eval_wordstat.model_file
Definition at line 21 of file eval_wordstat.py.
numthreads
eval_wordstat.numthreads
Definition at line 25 of file eval_wordstat.py.
opt
eval_wordstat.opt = parser.parse_args(print_args=False)
Definition at line 27 of file eval_wordstat.py.
parser
eval_wordstat.parser = setup_args()
Definition at line 298 of file eval_wordstat.py.
print_parser
eval_wordstat.print_parser
Definition at line 299 of file eval_wordstat.py.
task
eval_wordstat.task
Definition at line 19 of file eval_wordstat.py.
version
eval_wordstat.version
Definition at line 38 of file eval_wordstat.py.