ParlAI: parlai.agents.legacy_agents.memnn.memnn_v0 Namespace Reference
parlai.agents.legacy_agents.memnn.memnn_v0 Namespace Reference
Classes
class MemnnAgent
Functions
def to_tensors (sentences, dictionary)
def build_cands (exs, dict)
Function Documentation
build_cands()
def parlai.agents.legacy_agents.memnn.memnn_v0.build_cands (exs, dict)
Definition at line 475 of file memnn_v0.py.
Referenced by parlai.core.torch_ranker_agent.TorchRankerAgent.get_task_candidates_path().
to_tensors()
def parlai.agents.legacy_agents.memnn.memnn_v0.to_tensors (sentences, dictionary)
Definition at line 463 of file memnn_v0.py.
Referenced by agent.memnn_feedback.MemnnFeedbackAgent.parse_cands(), and parlai.agents.legacy_agents.memnn.memnn_v0.MemnnAgent.score().