ParlAI: parlai.scripts.interactive_web Namespace Reference
parlai.scripts.interactive_web Namespace Reference
Classes
class MyHandler
Functions
def setup_interactive (shared)
Variables
string HOST_NAME = 'localhost'
int PORT = 8080
dictionary SHARED = {}
string STYLE_SHEET = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.css"
string FONT_AWESOME = "https://use.fontawesome.com/releases/v5.3.1/js/all.js"
string WEB_HTML
def opt = setup_interactive(SHARED)
protocol_version
httpd = HTTPServer((HOST_NAME, opt['port']), MyHandler)
Function Documentation
setup_interactive()
def parlai.scripts.interactive_web.setup_interactive (shared)
Build and parse CLI opts.
Definition at line 219 of file interactive_web.py.
References parlai.core.agents.create_agent(), parlai.core.worlds.create_task(), and parlai.messenger.core.run.setup_args().
Variable Documentation
FONT_AWESOME
string parlai.scripts.interactive_web.FONT_AWESOME = "https://use.fontawesome.com/releases/v5.3.1/js/all.js"
Definition at line 20 of file interactive_web.py.
HOST_NAME
string parlai.scripts.interactive_web.HOST_NAME = 'localhost'
Definition at line 16 of file interactive_web.py.
httpd
parlai.scripts.interactive_web.httpd = HTTPServer((HOST_NAME, opt['port']), MyHandler)
Definition at line 241 of file interactive_web.py.
opt
def parlai.scripts.interactive_web.opt = setup_interactive(SHARED)
Definition at line 239 of file interactive_web.py.
PORT
int parlai.scripts.interactive_web.PORT = 8080
Definition at line 17 of file interactive_web.py.
protocol_version
parlai.scripts.interactive_web.protocol_version
Definition at line 240 of file interactive_web.py.
SHARED
dictionary parlai.scripts.interactive_web.SHARED = {}
Definition at line 18 of file interactive_web.py.
STYLE_SHEET
string parlai.scripts.interactive_web.STYLE_SHEET = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.css"
Definition at line 19 of file interactive_web.py.
WEB_HTML
string parlai.scripts.interactive_web.WEB_HTML
Definition at line 21 of file interactive_web.py.