ParlAI: parlai.agents.legacy_agents.seq2seq.modules_v0 Namespace Reference
parlai.agents.legacy_agents.seq2seq.modules_v0 Namespace Reference
Classes
class AttentionLayer
class Decoder
class Encoder
class Linear
class RandomProjection
class Ranker
class Seq2seq
Functions
def pad (tensor, length, dim=0)
Function Documentation
pad()
def parlai.agents.legacy_agents.seq2seq.modules_v0.pad (tensor, length, dim = 0)
Definition at line 18 of file modules_v0.py.
Referenced by parlai.agents.legacy_agents.seq2seq.modules_v0.Seq2seq.forward(), parlai.agents.legacy_agents.seq2seq.modules_v0.Ranker.forward(), and parlai.agents.fairseq.fairseq.FairseqAgent.receive_metrics().