ParlAI: parlai.mturk.core.legacy_2018.test.test_full_system Namespace Reference
parlai.mturk.core.legacy_2018.test.test_full_system Namespace Reference
Classes
class MockAgent
class MockSocket
class TestMTurkManagerWorkflows
Functions
def assert_equal_by (val_func, val, max_time)
Variables
parent_dir = os.path.dirname(os.path.abspath(__file__))
input
print_and_log
string TEST_WORKER_ID_1 = 'TEST_WORKER_ID_1'
string TEST_WORKER_ID_2 = 'TEST_WORKER_ID_2'
string TEST_ASSIGNMENT_ID_1 = 'TEST_ASSIGNMENT_ID_1'
string TEST_ASSIGNMENT_ID_2 = 'TEST_ASSIGNMENT_ID_2'
string TEST_ASSIGNMENT_ID_3 = 'TEST_ASSIGNMENT_ID_3'
string TEST_HIT_ID_1 = 'TEST_HIT_ID_1'
string TEST_HIT_ID_2 = 'TEST_HIT_ID_2'
string TEST_CONV_ID_1 = 'TEST_CONV_ID_1'
string FAKE_ID = 'BOGUS'
string MESSAGE_ID_1 = 'MESSAGE_ID_1'
string MESSAGE_ID_2 = 'MESSAGE_ID_2'
string MESSAGE_ID_3 = 'MESSAGE_ID_3'
string MESSAGE_ID_4 = 'MESSAGE_ID_4'
string COMMAND_ID_1 = 'COMMAND_ID_1'
MESSAGE_TYPE = data_model.MESSAGE_TYPE_MESSAGE
COMMAND_TYPE = data_model.MESSAGE_TYPE_COMMAND
dictionary MESSAGE_1 = {'message_id': MESSAGE_ID_1, 'type': MESSAGE_TYPE}
dictionary MESSAGE_2 = {'message_id': MESSAGE_ID_2, 'type': MESSAGE_TYPE}
dictionary COMMAND_1 = {'message_id': COMMAND_ID_1, 'type': COMMAND_TYPE}
string AGENT_ID = 'AGENT_ID'
dictionary ACT_1 = {'text': 'THIS IS A MESSAGE', 'id': AGENT_ID}
dictionary ACT_2 = {'text': 'THIS IS A MESSAGE AGAIN', 'id': AGENT_ID}
list active_statuses
list complete_statuses
list statuses = active_statuses + complete_statuses
string TASK_GROUP_ID_1 = 'TASK_GROUP_ID_1'
DEF_MISSED_PONGS
HEARTBEAT_RATE
DEF_DEAD_TIME
ACK_TIME
THREAD_SHORT_SLEEP
THREAD_MEDIUM_SLEEP
WORLD_START_TIMEOUT
string TOPIC_ARN = 'topic_arn'
string QUALIFICATION_ID = 'qualification_id'
string HIT_TYPE_ID = 'hit_type_id'
string MTURK_PAGE_URL = 'mturk_page_url'
string FAKE_HIT_ID = 'fake_hit_id'
buffer
Function Documentation
assert_equal_by()
def parlai.mturk.core.legacy_2018.test.test_full_system.assert_equal_by (val_func, val, max_time)
Definition at line 95 of file test_full_system.py.
Referenced by parlai.mturk.core.legacy_2018.test.test_full_system.TestMTurkManagerWorkflows.test_attempt_break_unique(), parlai.mturk.core.legacy_2018.test.test_full_system.TestMTurkManagerWorkflows.test_break_multi_convo(), parlai.mturk.core.legacy_2018.test.test_full_system.TestMTurkManagerWorkflows.test_disconnect_end(), parlai.mturk.core.legacy_2018.test.test_full_system.TestMTurkManagerWorkflows.test_expire_onboarding(), parlai.mturk.core.legacy_2018.test.test_full_system.TestMTurkManagerWorkflows.test_no_onboard_expire_waiting(), parlai.mturk.core.legacy_2018.test.test_full_system.TestMTurkManagerWorkflows.test_reconnect_complete(), parlai.mturk.core.legacy_2018.test.test_full_system.TestMTurkManagerWorkflows.test_return_to_waiting_on_world_start(), and parlai.mturk.core.legacy_2018.test.test_full_system.TestMTurkManagerWorkflows.test_successful_convo().
Variable Documentation
ACK_TIME
parlai.mturk.core.legacy_2018.test.test_full_system.ACK_TIME
Definition at line 80 of file test_full_system.py.
ACT_1
dictionary parlai.mturk.core.legacy_2018.test.test_full_system.ACT_1 = {'text': 'THIS IS A MESSAGE', 'id': AGENT_ID}
Definition at line 56 of file test_full_system.py.
ACT_2
dictionary parlai.mturk.core.legacy_2018.test.test_full_system.ACT_2 = {'text': 'THIS IS A MESSAGE AGAIN', 'id': AGENT_ID}
Definition at line 57 of file test_full_system.py.
active_statuses
list parlai.mturk.core.legacy_2018.test.test_full_system.active_statuses
Initial value:
 =  [
     AssignState.STATUS_NONE,
     AssignState.STATUS_ONBOARDING,
     AssignState.STATUS_WAITING,
     AssignState.STATUS_IN_TASK,
 ]
Definition at line 59 of file test_full_system.py.
AGENT_ID
string parlai.mturk.core.legacy_2018.test.test_full_system.AGENT_ID = 'AGENT_ID'
Definition at line 54 of file test_full_system.py.
buffer
parlai.mturk.core.legacy_2018.test.test_full_system.buffer
Definition at line 1008 of file test_full_system.py.
COMMAND_1
dictionary parlai.mturk.core.legacy_2018.test.test_full_system.COMMAND_1 = {'message_id': COMMAND_ID_1, 'type': COMMAND_TYPE}
Definition at line 52 of file test_full_system.py.
COMMAND_ID_1
string parlai.mturk.core.legacy_2018.test.test_full_system.COMMAND_ID_1 = 'COMMAND_ID_1'
Definition at line 45 of file test_full_system.py.
COMMAND_TYPE
parlai.mturk.core.legacy_2018.test.test_full_system.COMMAND_TYPE = data_model.MESSAGE_TYPE_COMMAND
Definition at line 48 of file test_full_system.py.
complete_statuses
list parlai.mturk.core.legacy_2018.test.test_full_system.complete_statuses
Initial value:
 =  [
     AssignState.STATUS_DONE,
     AssignState.STATUS_DISCONNECT,
     AssignState.STATUS_PARTNER_DISCONNECT,
     AssignState.STATUS_PARTNER_DISCONNECT_EARLY,
     AssignState.STATUS_EXPIRED,
     AssignState.STATUS_RETURNED,
 ]
Definition at line 65 of file test_full_system.py.
DEF_DEAD_TIME
parlai.mturk.core.legacy_2018.test.test_full_system.DEF_DEAD_TIME
Definition at line 79 of file test_full_system.py.
DEF_MISSED_PONGS
parlai.mturk.core.legacy_2018.test.test_full_system.DEF_MISSED_PONGS
Definition at line 77 of file test_full_system.py.
FAKE_HIT_ID
string parlai.mturk.core.legacy_2018.test.test_full_system.FAKE_HIT_ID = 'fake_hit_id'
Definition at line 92 of file test_full_system.py.
FAKE_ID
string parlai.mturk.core.legacy_2018.test.test_full_system.FAKE_ID = 'BOGUS'
Definition at line 39 of file test_full_system.py.
HEARTBEAT_RATE
parlai.mturk.core.legacy_2018.test.test_full_system.HEARTBEAT_RATE
Definition at line 78 of file test_full_system.py.
HIT_TYPE_ID
string parlai.mturk.core.legacy_2018.test.test_full_system.HIT_TYPE_ID = 'hit_type_id'
Definition at line 90 of file test_full_system.py.
input
parlai.mturk.core.legacy_2018.test.test_full_system.input
Definition at line 26 of file test_full_system.py.
MESSAGE_1
dictionary parlai.mturk.core.legacy_2018.test.test_full_system.MESSAGE_1 = {'message_id': MESSAGE_ID_1, 'type': MESSAGE_TYPE}
Definition at line 50 of file test_full_system.py.
MESSAGE_2
dictionary parlai.mturk.core.legacy_2018.test.test_full_system.MESSAGE_2 = {'message_id': MESSAGE_ID_2, 'type': MESSAGE_TYPE}
Definition at line 51 of file test_full_system.py.
MESSAGE_ID_1
string parlai.mturk.core.legacy_2018.test.test_full_system.MESSAGE_ID_1 = 'MESSAGE_ID_1'
Definition at line 41 of file test_full_system.py.
MESSAGE_ID_2
string parlai.mturk.core.legacy_2018.test.test_full_system.MESSAGE_ID_2 = 'MESSAGE_ID_2'
Definition at line 42 of file test_full_system.py.
MESSAGE_ID_3
string parlai.mturk.core.legacy_2018.test.test_full_system.MESSAGE_ID_3 = 'MESSAGE_ID_3'
Definition at line 43 of file test_full_system.py.
MESSAGE_ID_4
string parlai.mturk.core.legacy_2018.test.test_full_system.MESSAGE_ID_4 = 'MESSAGE_ID_4'
Definition at line 44 of file test_full_system.py.
MESSAGE_TYPE
parlai.mturk.core.legacy_2018.test.test_full_system.MESSAGE_TYPE = data_model.MESSAGE_TYPE_MESSAGE
Definition at line 47 of file test_full_system.py.
MTURK_PAGE_URL
string parlai.mturk.core.legacy_2018.test.test_full_system.MTURK_PAGE_URL = 'mturk_page_url'
Definition at line 91 of file test_full_system.py.
parent_dir
parlai.mturk.core.legacy_2018.test.test_full_system.parent_dir = os.path.dirname(os.path.abspath(__file__))
Definition at line 24 of file test_full_system.py.
print_and_log
parlai.mturk.core.legacy_2018.test.test_full_system.print_and_log
Definition at line 29 of file test_full_system.py.
QUALIFICATION_ID
string parlai.mturk.core.legacy_2018.test.test_full_system.QUALIFICATION_ID = 'qualification_id'
Definition at line 89 of file test_full_system.py.
statuses
list parlai.mturk.core.legacy_2018.test.test_full_system.statuses = active_statuses + complete_statuses
Definition at line 73 of file test_full_system.py.
TASK_GROUP_ID_1
string parlai.mturk.core.legacy_2018.test.test_full_system.TASK_GROUP_ID_1 = 'TASK_GROUP_ID_1'
Definition at line 75 of file test_full_system.py.
TEST_ASSIGNMENT_ID_1
string parlai.mturk.core.legacy_2018.test.test_full_system.TEST_ASSIGNMENT_ID_1 = 'TEST_ASSIGNMENT_ID_1'
Definition at line 33 of file test_full_system.py.
TEST_ASSIGNMENT_ID_2
string parlai.mturk.core.legacy_2018.test.test_full_system.TEST_ASSIGNMENT_ID_2 = 'TEST_ASSIGNMENT_ID_2'
Definition at line 34 of file test_full_system.py.
TEST_ASSIGNMENT_ID_3
string parlai.mturk.core.legacy_2018.test.test_full_system.TEST_ASSIGNMENT_ID_3 = 'TEST_ASSIGNMENT_ID_3'
Definition at line 35 of file test_full_system.py.
TEST_CONV_ID_1
string parlai.mturk.core.legacy_2018.test.test_full_system.TEST_CONV_ID_1 = 'TEST_CONV_ID_1'
Definition at line 38 of file test_full_system.py.
TEST_HIT_ID_1
string parlai.mturk.core.legacy_2018.test.test_full_system.TEST_HIT_ID_1 = 'TEST_HIT_ID_1'
Definition at line 36 of file test_full_system.py.
TEST_HIT_ID_2
string parlai.mturk.core.legacy_2018.test.test_full_system.TEST_HIT_ID_2 = 'TEST_HIT_ID_2'
Definition at line 37 of file test_full_system.py.
TEST_WORKER_ID_1
string parlai.mturk.core.legacy_2018.test.test_full_system.TEST_WORKER_ID_1 = 'TEST_WORKER_ID_1'
Definition at line 31 of file test_full_system.py.
TEST_WORKER_ID_2
string parlai.mturk.core.legacy_2018.test.test_full_system.TEST_WORKER_ID_2 = 'TEST_WORKER_ID_2'
Definition at line 32 of file test_full_system.py.
THREAD_MEDIUM_SLEEP
parlai.mturk.core.legacy_2018.test.test_full_system.THREAD_MEDIUM_SLEEP
Definition at line 83 of file test_full_system.py.
THREAD_SHORT_SLEEP
parlai.mturk.core.legacy_2018.test.test_full_system.THREAD_SHORT_SLEEP
Definition at line 82 of file test_full_system.py.
TOPIC_ARN
string parlai.mturk.core.legacy_2018.test.test_full_system.TOPIC_ARN = 'topic_arn'
Definition at line 88 of file test_full_system.py.
WORLD_START_TIMEOUT
parlai.mturk.core.legacy_2018.test.test_full_system.WORLD_START_TIMEOUT
Definition at line 85 of file test_full_system.py.