ParlAI: controllable_seq2seq.nidf Namespace Reference
controllable_seq2seq.nidf Namespace Reference
Functions
def get_word_counts (opt, count_inputs)
def learn_nidf (opt)
def load_word2nidf (opt)
Variables
string CONTROLLABLE_DIR = 'controllable_dialogue'
string PARLAI_FORMAT_DIR = 'controllable_dialogue/ConvAI2_parlaiformat'
parser = ParlaiParser()
opt = parser.parse_args()
Function Documentation
get_word_counts()
def controllable_seq2seq.nidf.get_word_counts (opt, count_inputs)
Goes through the dataset specified in opt and gets word counts.
Inputs:
  count_inputs: If True, include both input and reply when counting words
    and utterances. Otherwise, only include reply text.
Returns:
  word_counter_per_sent: a Counter mapping each word to the number of
    utterances in which it appears.
  num_sents: int. number of utterances counted
Definition at line 25 of file nidf.py.
References parlai.core.worlds.create_task().
Referenced by controllable_seq2seq.nidf.learn_nidf().
learn_nidf()
def controllable_seq2seq.nidf.learn_nidf (opt)
Go through ConvAI2 and Twitter data, and count word frequences.
Save word2count.pkl, which contains word2count, and total num_sents.
These are both needed to calculate NIDF later.
Definition at line 77 of file nidf.py.
References controllable_seq2seq.nidf.get_word_counts().
load_word2nidf()
def controllable_seq2seq.nidf.load_word2nidf (opt)
Loads word count stats from word2count.pkl file in data/controllable_dialogue,
computes NIDF for all words, and returns the word2nidf dictionary.
Returns:
  word2nidf: dict mapping words to their NIDF score (float between 0 and 1)
Definition at line 128 of file nidf.py.
Referenced by controllable_seq2seq.controls.initialize_control_information().
Variable Documentation
CONTROLLABLE_DIR
string controllable_seq2seq.nidf.CONTROLLABLE_DIR = 'controllable_dialogue'
Definition at line 21 of file nidf.py.
opt
controllable_seq2seq.nidf.opt = parser.parse_args()
Definition at line 155 of file nidf.py.
PARLAI_FORMAT_DIR
string controllable_seq2seq.nidf.PARLAI_FORMAT_DIR = 'controllable_dialogue/ConvAI2_parlaiformat'
Definition at line 22 of file nidf.py.
parser
controllable_seq2seq.nidf.parser = ParlaiParser()
Definition at line 154 of file nidf.py.