ParlAI: split_convai2_topics Namespace Reference
split_convai2_topics Namespace Reference
Functions
def setup_args ()
def includes_topic (episode, topic)
def main (opt)
Variables
list FAMILY
list variants = []
list SPORTS = ["ball", "sports"]
list TOPIC = SPORTS
string TOPIC_NAME = 'sports'
def opt = setup_args()
Function Documentation
includes_topic()
def split_convai2_topics.includes_topic (episode, topic)
Definition at line 103 of file split_convai2_topics.py.
Referenced by main().
main()
def split_convai2_topics.main (opt)
Converts a Fbdialog file of episodes into two self-feeding files (split by topic)
All conversations including a word in the provided topic's bag of words will be
separated from conversations without those words.
Definition at line 115 of file split_convai2_topics.py.
References self_feeding.utils.episode_to_examples(), self_feeding.utils.extract_fb_episodes(), and includes_topic().
setup_args()
def split_convai2_topics.setup_args ()
Definition at line 69 of file split_convai2_topics.py.
Variable Documentation
FAMILY
list split_convai2_topics.FAMILY
Definition at line 13 of file split_convai2_topics.py.
opt
def split_convai2_topics.opt = setup_args()
Definition at line 168 of file split_convai2_topics.py.
SPORTS
list split_convai2_topics.SPORTS = ["ball", "sports"]
Definition at line 59 of file split_convai2_topics.py.
TOPIC
list split_convai2_topics.TOPIC = SPORTS
Definition at line 65 of file split_convai2_topics.py.
TOPIC_NAME
string split_convai2_topics.TOPIC_NAME = 'sports'
Definition at line 66 of file split_convai2_topics.py.
variants
list split_convai2_topics.variants = []
Definition at line 53 of file split_convai2_topics.py.