ParlAI: parlai.tasks.taskmaster.tm_utils Namespace Reference
parlai.tasks.taskmaster.tm_utils Namespace Reference
Functions
def gen_ep_cheatsheet (convo)
def update_indexes (conversation)
def join_speech (utt1, utt2)
def smoothen_convo (conversation, opt)
Variables
int FIRST_USER_IDX = 0
                                                        #
Constants # #
int LAST_USER_IDX = 1
int FIRST_ASSISTANT_IDX = 2
int LAST_ASSISTANT_IDX = 3
int USER_NUM_EX = 4
int ASSIS_NUM_EX = 5
Function Documentation
gen_ep_cheatsheet()
def parlai.tasks.taskmaster.tm_utils.gen_ep_cheatsheet (convo)
Generates a cheatsheet for a particular conversation (episode).
The index and it's significance in the cheatsheet is shown below:
    0: First index of a USER that has an ASSISTANT reply to it
    1: Last index of a USER that has an ASSISTANT reply to it
    2: First index of an ASSISTANT that has a USER reply to it
    3: Last index of an ASSISTANT that has a USER reply to it
    4: Number of examples for USER speech  as text and ASSISTANT speech as label
    5: Number of examples for ASSISTANT speech as text and USER speech  as label
:param convo:
    The dialogue between USER and ASSISTANT [after smoothening]
Definition at line 39 of file tm_utils.py.
join_speech()
def parlai.tasks.taskmaster.tm_utils.join_speech (utt1, utt2)
Joins two conversations using a '\n'
Join texts and doesn't care about segments
Assumption: utt1 is the one being popped off from the stack and the utt2
            is the one trying to be added. This is so that I check for 'ctr'
            field only in one of the parameters.
:param utt1:
    An utterance (json object) from either USER or ASSISTANT
:param utt2:
    Next utterance(json object) from a speaker same as utt1
Definition at line 94 of file tm_utils.py.
Referenced by parlai.tasks.taskmaster.tm_utils.smoothen_convo().
smoothen_convo()
def parlai.tasks.taskmaster.tm_utils.smoothen_convo (conversation, opt)
Aggregates contiguous responses by the same speaker in the data so that data
eventually contains alternations between USER and ASSISTANT
:param conversation:
    The dialogue between USER and ASSISTANT with possible multiple contiguous
    speeches by the same speaker
:param opt:
    options dict, mainly useful for accessing value of exclude_invalid_data
Definition at line 117 of file tm_utils.py.
References parlai.tasks.taskmaster.tm_utils.join_speech(), and parlai.tasks.taskmaster.tm_utils.update_indexes().
update_indexes()
def parlai.tasks.taskmaster.tm_utils.update_indexes (conversation)
Re-assigns indexes after smoothening (mostly for clarity purposes)
Doesn't really matter since we never index by specifically using the "index"
field of the json obj
:param conversation:
    The dialogue between USER and ASSISTANT with inconsistent indices
Definition at line 80 of file tm_utils.py.
Referenced by parlai.tasks.taskmaster.tm_utils.smoothen_convo().
Variable Documentation
ASSIS_NUM_EX
int parlai.tasks.taskmaster.tm_utils.ASSIS_NUM_EX = 5
Definition at line 20 of file tm_utils.py.
FIRST_ASSISTANT_IDX
int parlai.tasks.taskmaster.tm_utils.FIRST_ASSISTANT_IDX = 2
Definition at line 17 of file tm_utils.py.
FIRST_USER_IDX
int parlai.tasks.taskmaster.tm_utils.FIRST_USER_IDX = 0
                                                        #
Constants # #
Definition at line 15 of file tm_utils.py.
LAST_ASSISTANT_IDX
int parlai.tasks.taskmaster.tm_utils.LAST_ASSISTANT_IDX = 3
Definition at line 18 of file tm_utils.py.
LAST_USER_IDX
int parlai.tasks.taskmaster.tm_utils.LAST_USER_IDX = 1
Definition at line 16 of file tm_utils.py.
USER_NUM_EX
int parlai.tasks.taskmaster.tm_utils.USER_NUM_EX = 4
Definition at line 19 of file tm_utils.py.