ParlAI: parlai.agents.legacy_agents.seq2seq.modules_v1 Namespace Reference
parlai.agents.legacy_agents.seq2seq.modules_v1 Namespace Reference
Classes
class AttentionLayer
class OutputLayer
class RNNDecoder
class RNNEncoder
class Seq2seq
class UnknownDropout
Functions
def opt_to_kwargs (opt)
def pad (tensor, length, dim=0, pad=0)
Function Documentation
opt_to_kwargs()
def parlai.agents.legacy_agents.seq2seq.modules_v1.opt_to_kwargs (opt)
Get kwargs for seq2seq from opt.
Definition at line 19 of file modules_v1.py.
Referenced by parlai.agents.memnn.memnn.MemnnAgent.build_model(), parlai.agents.seq2seq.seq2seq.Seq2seqAgent.build_model(), and controllable_seq2seq.controllable_seq2seq.ControllableSeq2seqAgent.build_model().
pad()
def parlai.agents.legacy_agents.seq2seq.modules_v1.pad (tensor, length, dim = 0, pad = 0)
Pad tensor to a specific length.
:param tensor: vector to pad
:param length: new length
:param dim: (default 0) dimension to pad
:returns: padded tensor if the tensor is shorter than length
Definition at line 40 of file modules_v1.py.