ParlAI: parlai.scripts.data_stats Namespace Reference
parlai.scripts.data_stats Namespace Reference
Functions
def setup_args (parser=None)
def report (world, counts, log_time)
def verify (opt, printargs=None, print_parser=None)
Variables
def parser = setup_args()
report_text
report_log
print_parser
Function Documentation
report()
def parlai.scripts.data_stats.report (world, counts, log_time)
Definition at line 52 of file data_stats.py.
References generate_task_READMEs.str.
Referenced by parlai.scripts.data_stats.verify().
setup_args()
def parlai.scripts.data_stats.setup_args (parser = None)
Definition at line 22 of file data_stats.py.
verify()
def parlai.scripts.data_stats.verify (opt, printargs = None, print_parser = None)
Definition at line 72 of file data_stats.py.
References parlai.core.worlds.create_task(), make_control_dataset.float, parlai.messenger.core.shared_utils.format, parlai.scripts.data_stats.report(), and parlai.agents.tfidf_retriever.build_tfidf.tokenize().
Referenced by test_new_tasks.TestNewTasks.test_verify_data().
Variable Documentation
parser
def parlai.scripts.data_stats.parser = setup_args()
Definition at line 171 of file data_stats.py.
print_parser
parlai.scripts.data_stats.print_parser
Definition at line 173 of file data_stats.py.
report_log
parlai.scripts.data_stats.report_log
Definition at line 172 of file data_stats.py.
report_text
parlai.scripts.data_stats.report_text
Definition at line 172 of file data_stats.py.