ParlAI: parlai.scripts.convo_render Namespace Reference
parlai.scripts.convo_render Namespace Reference
Functions
def gen_convo_ul (conversations)
def gen_html (conversations, height, width, title, other_speaker, human_speaker, user_icon, alt_icon)
def pre_process (fname, num_ex, alt_speaker)
def prBlueBG (text)
def display_cli (conversations, alt_speaker, human_speaker)
def create_parser ()
def check_icon_arg (src, default)
def validate_args (args)
Variables
string END_OF_CONVO = "EOC"
string CHROME_PATH = r'/Applications/Google\ Chrome.app/Contents/MacOS//Google\ Chrome'
string ALT_EMOJI_IMG = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/facebook/230/parrot_1f99c.png"
string HUMAN_EMOJI_IMG = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/apple/76/woman_1f469.png"
def parser = create_parser()
def args = parser.parse_args()
def extension = validate_args(args)
input_file
output_file
height
width
alt_speaker = input_file.split('/')[-1][:-6]
def dialogs = pre_process(input_file, args.num_examples, alt_speaker)
def html_str
file_handle = open(output_file, "w")
string fname = tmpdir + "/interim.html"
string cmd
stdout
PIPE
stderr
shell
Function Documentation
check_icon_arg()
def parlai.scripts.convo_render.check_icon_arg (src, default)
Checks if icon arguments are valid: either a URL or an absolute path
:param src: Source of the icon
:param default: default value of the icon
:return: src (possibly pre-pended with "file://")
Definition at line 246 of file convo_render.py.
Referenced by parlai.scripts.convo_render.validate_args().
create_parser()
def parlai.scripts.convo_render.create_parser ()
Creates a parser object with some pre-determined arguments.
Definition at line 206 of file convo_render.py.
display_cli()
def parlai.scripts.convo_render.display_cli (conversations, alt_speaker, human_speaker)
Display the conversations on the Command Line.
:param conversations: The dialogs to be displayed
:param alt_speaker: Name of other speaker to be used
:param human_speaker: Name of human speaker to be used
Definition at line 190 of file convo_render.py.
References parlai.scripts.convo_render.prBlueBG().
gen_convo_ul()
def parlai.scripts.convo_render.gen_convo_ul (conversations)
Generate the ul section of the HTML for the conversations.
:param conversation: The conversation to be rendered (after pre-processing)
:return: The string generating the list in HTML
Definition at line 23 of file convo_render.py.
References parlai.scripts.convo_render.gen_html().
gen_html()
def parlai.scripts.convo_render.gen_html (conversations, height, width, title, other_speaker, human_speaker, user_icon, alt_icon)
Generate HTML string for the given conversation.
:param conversation:
    The conversation to be rendered (after pre-processing)
:param height:
    Height of the HTML page
:param width:
    Width of the HTML page
:param title:
    Title of the HTML page
:param other_speaker:
    The title of the model (grey boxes)
:param human_speaker:
    Human speaker in the dialogs (blue boxes)
:return: HTML string for the desired conversation
Definition at line 60 of file convo_render.py.
Referenced by parlai.scripts.convo_render.gen_convo_ul().
prBlueBG()
def parlai.scripts.convo_render.prBlueBG (text)
Print given in text with a blue background.
:param text: The text to be printed
Definition at line 182 of file convo_render.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.scripts.convo_render.display_cli().
pre_process()
def parlai.scripts.convo_render.pre_process (fname, num_ex, alt_speaker)
Pre-process the given file to bring the conversation in a certain format.
:param fname: File name to be processed
:param num_ex: Number of conversations to be used
:param alt_speaker: Name of other speaker to be used
:return: List of tuples of the form: (speaker, speech)
Definition at line 154 of file convo_render.py.
validate_args()
def parlai.scripts.convo_render.validate_args (args)
Validate the cmdline args passed into the script
:param args: The arguments of te parser
:return: Returns extension of output file. None if no output file
Definition at line 267 of file convo_render.py.
References parlai.scripts.convo_render.check_icon_arg().
Variable Documentation
ALT_EMOJI_IMG
string parlai.scripts.convo_render.ALT_EMOJI_IMG = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/facebook/230/parrot_1f99c.png"
Definition at line 19 of file convo_render.py.
alt_speaker
parlai.scripts.convo_render.alt_speaker = input_file.split('/')[-1][:-6]
Definition at line 294 of file convo_render.py.
args
def parlai.scripts.convo_render.args = parser.parse_args()
Definition at line 290 of file convo_render.py.
CHROME_PATH
string parlai.scripts.convo_render.CHROME_PATH = r'/Applications/Google\ Chrome.app/Contents/MacOS//Google\ Chrome'
Definition at line 17 of file convo_render.py.
cmd
string parlai.scripts.convo_render.cmd
Initial value:
 =  f"{CHROME_PATH} --headless --crash-dumps-dir=/tmp \
                      --print-to-pdf=\"{output_file}\" {fname}"
Definition at line 325 of file convo_render.py.
dialogs
def parlai.scripts.convo_render.dialogs = pre_process(input_file, args.num_examples, alt_speaker)
Definition at line 296 of file convo_render.py.
END_OF_CONVO
string parlai.scripts.convo_render.END_OF_CONVO = "EOC"
Definition at line 16 of file convo_render.py.
extension
def parlai.scripts.convo_render.extension = validate_args(args)
Definition at line 291 of file convo_render.py.
file_handle
parlai.scripts.convo_render.file_handle = open(output_file, "w")
Definition at line 315 of file convo_render.py.
fname
string parlai.scripts.convo_render.fname = tmpdir + "/interim.html"
Definition at line 321 of file convo_render.py.
height
parlai.scripts.convo_render.height
Definition at line 293 of file convo_render.py.
html_str
def parlai.scripts.convo_render.html_str
Initial value:
 =  gen_html(
             dialogs,
             height,
             width,
             "Rendered HTML",
             alt_speaker,
             "human",
             args.user_icon,
             args.alt_icon,
         )
Definition at line 303 of file convo_render.py.
HUMAN_EMOJI_IMG
string parlai.scripts.convo_render.HUMAN_EMOJI_IMG = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/apple/76/woman_1f469.png"
Definition at line 20 of file convo_render.py.
input_file
parlai.scripts.convo_render.input_file
Definition at line 292 of file convo_render.py.
output_file
parlai.scripts.convo_render.output_file
Definition at line 292 of file convo_render.py.
parser
def parlai.scripts.convo_render.parser = create_parser()
Definition at line 289 of file convo_render.py.
PIPE
parlai.scripts.convo_render.PIPE
Definition at line 333 of file convo_render.py.
shell
parlai.scripts.convo_render.shell
Definition at line 333 of file convo_render.py.
stderr
parlai.scripts.convo_render.stderr
Definition at line 333 of file convo_render.py.
stdout
parlai.scripts.convo_render.stdout
Definition at line 333 of file convo_render.py.
width
parlai.scripts.convo_render.width
Definition at line 293 of file convo_render.py.