ParlAI: generate_cli Namespace Reference
generate_cli Namespace Reference
Functions
def indent (rawstr, indentstr=' ')
def get_scripts ()
def main ()
Function Documentation
get_scripts()
def generate_cli.get_scripts ()
Definition at line 19 of file generate_cli.py.
Referenced by main().
indent()
def generate_cli.indent (rawstr, indentstr = ' ')
Definition at line 13 of file generate_cli.py.
Referenced by main().
main()
def generate_cli.main ()
Definition at line 26 of file generate_cli.py.
References parlai.messenger.core.shared_utils.format, get_scripts(), and indent().