ParlAI: light_chats.graph Namespace Reference
light_chats.graph Namespace Reference
Classes
class DrinkFunction
class DropObjectFunction
class EatFunction
class EquipObjectFunction
class ExamineFunction
class FitsConstraint
class FollowFunction
class GetObjectFunction
class GiveObjectFunction
class Graph
class GraphConstraint
class GraphFunction
class HasPropConstraint
class HealthFunction
class HitFunction
class HugFunction
class IngestFunction
class InventoryFunction
class IsTypeConstraint
class LockableConstraint
class LockedConstraint
class LockedWithConstraint
class LockFunction
class LookFunction
class MoveAgentFunction
class NoPropConstraint
class NotLocationOfConstraint
class NotTypeConstraint
class PutObjectInFunction
class RemoveObjectFunction
class SayFunction
class SoloFunction
class StealObjectFunction
class TellFunction
class UnfollowFunction
class UnlockFunction
class UseFunction
class WaitFunction
class WearObjectFunction
class WieldObjectFunction
Functions
def rm (d, val)
def format_observation (self, graph, viewing_agent, action, telling_agent=None, is_constraint=False)
def is_held_item (item_idx)
def is_equipped_item (item_idx)
Variables
int INIT_HEALTH = 2
dictionary CONSTRAINTS = {}
dictionary GRAPH_FUNCTIONS = {}
list con_list
list func_list
dictionary CANNONICAL_GRAPH_FUNCTIONS = {}
names = f.name
list FUNC_IGNORE_LIST = ['tell', 'say']
Function Documentation
format_observation()
def light_chats.graph.format_observation (self, graph, viewing_agent, action, telling_agent = None, is_constraint = False)
Return the observation text to display for an action
Definition at line 33 of file graph.py.
References parlai.messenger.core.shared_utils.format.
Referenced by light_chats.graph.rm().
is_equipped_item()
def light_chats.graph.is_equipped_item (item_idx)
Definition at line 77 of file graph.py.
Referenced by light_chats.graph.RemoveObjectFunction.__init__().
is_held_item()
def light_chats.graph.is_held_item (item_idx)
Definition at line 70 of file graph.py.
Referenced by light_chats.graph.UseFunction.__init__(), light_chats.graph.PutObjectInFunction.__init__(), light_chats.graph.DropObjectFunction.__init__(), light_chats.graph.GiveObjectFunction.__init__(), light_chats.graph.StealObjectFunction.__init__(), light_chats.graph.EquipObjectFunction.__init__(), and light_chats.graph.IngestFunction.__init__().
rm()
def light_chats.graph.rm (d, val)
Definition at line 26 of file graph.py.
References light_chats.graph.format_observation().
Referenced by light_chats.graph.Graph.delete_node().
Variable Documentation
CANNONICAL_GRAPH_FUNCTIONS
dictionary light_chats.graph.CANNONICAL_GRAPH_FUNCTIONS = {}
Definition at line 2680 of file graph.py.
con_list
list light_chats.graph.con_list
Initial value:
 =  [
     FitsConstraint(),
     IsTypeConstraint(),
     HasPropConstraint(),
     NoPropConstraint(),
     LockableConstraint(),
     LockedConstraint(),
     LockedWithConstraint(),
     NotLocationOfConstraint(),
     NotTypeConstraint(),
 ]
Definition at line 2639 of file graph.py.
CONSTRAINTS
dictionary light_chats.graph.CONSTRAINTS = {}
Definition at line 22 of file graph.py.
FUNC_IGNORE_LIST
list light_chats.graph.FUNC_IGNORE_LIST = ['tell', 'say']
Definition at line 2690 of file graph.py.
func_list
list light_chats.graph.func_list
Initial value:
 =  [
     MoveAgentFunction(),
     GetObjectFunction(),
     PutObjectInFunction(),
     DropObjectFunction(),
     GiveObjectFunction(),
     StealObjectFunction(),
     WearObjectFunction(),
     WieldObjectFunction(),
     RemoveObjectFunction(),
     WaitFunction(),
     InventoryFunction(),
     HealthFunction(),
     EatFunction(),
     DrinkFunction(),
     LookFunction(),
     LockFunction(),
     UnlockFunction(),
     ExamineFunction(),
     FollowFunction(),
     UnfollowFunction(),
     HitFunction(),
     TellFunction(),
     HugFunction(),
     # UseFunction(),
     SayFunction(),
 ]
Definition at line 2650 of file graph.py.
GRAPH_FUNCTIONS
dictionary light_chats.graph.GRAPH_FUNCTIONS = {}
Definition at line 23 of file graph.py.
INIT_HEALTH
int light_chats.graph.INIT_HEALTH = 2
Definition at line 20 of file graph.py.
names
list light_chats.graph.names = f.name
Definition at line 2682 of file graph.py.