ParlAI: parlai.tasks.light_dialog.builder Namespace Reference
parlai.tasks.light_dialog.builder Namespace Reference
Functions
def use_feat (opt, field, ttype)
def fix_labels (act, opt)
def get_no_affordance_actions (in_room, carrying, other_carrying, other_name)
def gen_no_affordance_actions_for_dialogue (d)
def write_dialog (opt, fw, d, label_type, split)
def write_alldata (opt, db, dpath, ltype, split)
def add_negs (msg, d, ind, label_type, split, num_cands, use_affordances)
def write_out_candidates (db, dpath, dtype)
def build_from_db (opt, db_path, data_path, fname, fname2)
Variables
rand = random.Random(42)
int mx = 0
dictionary cands = {}
Function Documentation
add_negs()
def parlai.tasks.light_dialog.builder.add_negs (msg, d, ind, label_type, split, num_cands, use_affordances)
Definition at line 257 of file builder.py.
Referenced by parlai.tasks.light_dialog.builder.write_dialog().
build_from_db()
def parlai.tasks.light_dialog.builder.build_from_db (opt, db_path, data_path, fname, fname2)
Definition at line 317 of file builder.py.
References parlai.tasks.light_dialog.builder.write_alldata(), and parlai.tasks.light_dialog.builder.write_out_candidates().
Referenced by parlai.tasks.light_dialog.build.build().
fix_labels()
def parlai.tasks.light_dialog.builder.fix_labels (act, opt)
Definition at line 26 of file builder.py.
References eval_ppl.int.
Referenced by parlai.tasks.light_dialog.builder.write_dialog().
gen_no_affordance_actions_for_dialogue()
def parlai.tasks.light_dialog.builder.gen_no_affordance_actions_for_dialogue (d)
Definition at line 65 of file builder.py.
References parlai.tasks.light_dialog.builder.get_no_affordance_actions().
Referenced by parlai.tasks.light_dialog.builder.write_out_candidates().
get_no_affordance_actions()
def parlai.tasks.light_dialog.builder.get_no_affordance_actions (in_room, carrying, other_carrying, other_name)
Definition at line 42 of file builder.py.
References parlai.messenger.core.shared_utils.format.
Referenced by parlai.tasks.light_dialog.builder.gen_no_affordance_actions_for_dialogue().
use_feat()
def parlai.tasks.light_dialog.builder.use_feat (opt, field, ttype)
Definition at line 16 of file builder.py.
Referenced by parlai.tasks.light_dialog.builder.write_dialog().
write_alldata()
def parlai.tasks.light_dialog.builder.write_alldata (opt, db, dpath, ltype, split)
Definition at line 227 of file builder.py.
References parlai.tasks.light_dialog.builder.write_dialog().
Referenced by parlai.tasks.light_dialog.builder.build_from_db().
write_dialog()
def parlai.tasks.light_dialog.builder.write_dialog (opt, fw, d, label_type, split)
Definition at line 83 of file builder.py.
References parlai.tasks.light_dialog.builder.add_negs(), parlai.tasks.light_dialog.builder.fix_labels(), eval_ppl.int, parlai.utils.misc.msg_to_str(), generate_task_READMEs.str, and parlai.tasks.light_dialog.builder.use_feat().
Referenced by parlai.tasks.light_dialog.builder.write_alldata().
write_out_candidates()
def parlai.tasks.light_dialog.builder.write_out_candidates (db, dpath, dtype)
Definition at line 289 of file builder.py.
References parlai.tasks.light_dialog.builder.gen_no_affordance_actions_for_dialogue().
Referenced by parlai.tasks.light_dialog.builder.build_from_db().
Variable Documentation
cands
dictionary parlai.tasks.light_dialog.builder.cands = {}
Definition at line 286 of file builder.py.
mx
int parlai.tasks.light_dialog.builder.mx = 0
Definition at line 23 of file builder.py.
rand
parlai.tasks.light_dialog.builder.rand = random.Random(42)
Definition at line 13 of file builder.py.