ParlAI: parlai.tasks.light_dialog.build Namespace Reference
parlai.tasks.light_dialog.build Namespace Reference
Functions
def download (opt)
def build (opt)
Function Documentation
build()
def parlai.tasks.light_dialog.build.build (opt)
Definition at line 42 of file build.py.
References parlai.tasks.light_dialog.builder.build_from_db(), parlai.tasks.light_dialog.build.download(), and generate_task_READMEs.str.
download()
def parlai.tasks.light_dialog.build.download (opt)
Definition at line 12 of file build.py.
Referenced by parlai.tasks.light_dialog.build.build().