ParlAI: eval_f1 Namespace Reference
eval_f1 Namespace Reference
Functions
def main ()
Variables
parser = setup_args()
task
datatype
metrics
model
model_file
dict_lower
batchsize
opt = parser.parse_args(print_args=False)
list fnames = ['twitter_seq2seq_model.tgz']
version
use_model_type
print_parser
Function Documentation
main()
def eval_f1.main ()
Definition at line 14 of file eval_f1.py.
References parlai.core.build_data.download_models(), and convai2.eval_f1.setup_args().
Referenced by test_convai2.TestConvai2KVMemnn.test_kvmemnn_f1(), test_convai2.TestConvai2LanguageModel.test_languagemodel_f1(), and test_convai2.TestConvai2Seq2Seq.test_seq2seq_f1().
Variable Documentation
batchsize
eval_f1.batchsize
Definition at line 21 of file eval_f1.py.
datatype
eval_f1.datatype
Definition at line 16 of file eval_f1.py.
dict_lower
eval_f1.dict_lower
Definition at line 20 of file eval_f1.py.
fnames
list eval_f1.fnames = ['twitter_seq2seq_model.tgz']
Definition at line 26 of file eval_f1.py.
metrics
eval_f1.metrics
Definition at line 17 of file eval_f1.py.
model
eval_f1.model
Definition at line 18 of file eval_f1.py.
model_file
eval_f1.model_file
Definition at line 19 of file eval_f1.py.
opt
eval_f1.opt = parser.parse_args(print_args=False)
Definition at line 23 of file eval_f1.py.
parser
eval_f1.parser = setup_args()
Definition at line 13 of file eval_f1.py.
print_parser
eval_f1.print_parser
Definition at line 29 of file eval_f1.py.
task
eval_f1.task
Definition at line 15 of file eval_f1.py.
use_model_type
eval_f1.use_model_type
Definition at line 27 of file eval_f1.py.
version
eval_f1.version
Definition at line 27 of file eval_f1.py.