ParlAI: server Namespace Reference
server Namespace Reference
Classes
class AppHandler
class Application
class ApprovalHandler
class AssignmentHandler
class BaseHandler
class BlockHandler
class BonusHandler
class ErrorHandler
class PacketWrap
class RedirectHandler
class RejectionHandler
class ReverseHandler
class RunHandler
class RunListHandler
class TaskListHandler
class TaskRunHandler
class TaskSocketHandler
class WorkerHandler
class WorkerListHandler
Functions
def row_to_dict (row)
def get_rand_id ()
def force_dir (path)
def get_path (filename)
def get_mturk_task_module (task_name, target_module)
def get_run_module (task_name)
def get_config_module (task_name)
def broadcast_msg (handler, msg, target_subs=None)
def send_to_sources (handler, msg)
def merge_assignments_with_pairings (assignments, pairings, log_id)
def start_server (port=DEFAULT_PORT, hostname=DEFAULT_HOSTNAME, db_file=DEFAULT_DB_FILE, is_sandbox=False)
def crawl_dir_for_tasks (search_dir)
def rebuild_source ()
def main ()
Variables
parlai_path = parlai_path[0]
parlai_int_path = parlai_int_path[0]
int DEFAULT_PORT = 8095
string DEFAULT_HOSTNAME = "localhost"
string DEFAULT_DB_FILE = 'pmt_data.db'
string DEFAULT_SB_DB_FILE = 'pmt_sbdata.db'
bool IS_DEBUG = True
here = os.path.abspath(os.path.dirname(__file__))
dictionary tasks = {}
dictionary tornado_settings
Function Documentation
broadcast_msg()
def server.broadcast_msg (handler, msg, target_subs = None)
Definition at line 149 of file server.py.
crawl_dir_for_tasks()
def server.crawl_dir_for_tasks (search_dir)
Definition at line 646 of file server.py.
Referenced by rebuild_source().
force_dir()
def server.force_dir (path)
Make sure the parent dir exists for path so we can write a file.
Definition at line 67 of file server.py.
get_config_module()
def server.get_config_module (task_name)
Definition at line 95 of file server.py.
References get_mturk_task_module().
Referenced by server.TaskListHandler.get(), server.AssignmentHandler.get(), and server.TaskRunHandler.post().
get_mturk_task_module()
def server.get_mturk_task_module (task_name, target_module)
Definition at line 78 of file server.py.
Referenced by get_config_module(), and get_run_module().
get_path()
def server.get_path (filename)
Get the path to an asset.
Definition at line 72 of file server.py.
get_rand_id()
def server.get_rand_id ()
Definition at line 63 of file server.py.
References eval_ppl.int, and generate_task_READMEs.str.
get_run_module()
def server.get_run_module (task_name)
Definition at line 91 of file server.py.
References get_mturk_task_module().
Referenced by server.TaskRunHandler.post().
main()
def server.main ()
Definition at line 753 of file server.py.
References rebuild_source(), and start_server().
merge_assignments_with_pairings()
def server.merge_assignments_with_pairings (assignments, pairings, log_id)
Definition at line 271 of file server.py.
References parlai.messenger.core.shared_utils.format, and row_to_dict().
Referenced by server.RunHandler.get(), server.WorkerHandler.get(), and server.AssignmentHandler.get().
rebuild_source()
def server.rebuild_source ()
Definition at line 659 of file server.py.
References crawl_dir_for_tasks(), and parlai.messenger.core.shared_utils.format.
Referenced by main().
row_to_dict()
def server.row_to_dict (row)
Definition at line 59 of file server.py.
Referenced by server.RunListHandler.get(), server.RunHandler.get(), server.WorkerListHandler.get(), server.WorkerHandler.get(), and merge_assignments_with_pairings().
send_to_sources()
def server.send_to_sources (handler, msg)
Definition at line 156 of file server.py.
start_server()
def server.start_server (port = DEFAULT_PORT, hostname = DEFAULT_HOSTNAME, db_file = DEFAULT_DB_FILE, is_sandbox = False)
Definition at line 632 of file server.py.
Referenced by main(), and server.TaskRunHandler.post().
Variable Documentation
DEFAULT_DB_FILE
string server.DEFAULT_DB_FILE = 'pmt_data.db'
Definition at line 50 of file server.py.
DEFAULT_HOSTNAME
string server.DEFAULT_HOSTNAME = "localhost"
Definition at line 49 of file server.py.
DEFAULT_PORT
int server.DEFAULT_PORT = 8095
Definition at line 48 of file server.py.
DEFAULT_SB_DB_FILE
string server.DEFAULT_SB_DB_FILE = 'pmt_sbdata.db'
Definition at line 51 of file server.py.
here
server.here = os.path.abspath(os.path.dirname(__file__))
Definition at line 54 of file server.py.
IS_DEBUG
bool server.IS_DEBUG = True
Definition at line 52 of file server.py.
parlai_int_path
server.parlai_int_path = parlai_int_path[0]
Definition at line 43 of file server.py.
parlai_path
server.parlai_path = parlai_path[0]
Definition at line 38 of file server.py.
tasks
dictionary server.tasks = {}
Definition at line 56 of file server.py.
tornado_settings
dictionary server.tornado_settings
Initial value:
 =  {
     "autoescape": None,
     "debug": IS_DEBUG,
     "static_path": get_path('static'),
     "template_path": get_path('static'),
     "compiled_template_cache": False,
 }
Definition at line 99 of file server.py.